### ISSUE TITLE
xTeve v2 - Useful and not Buggy anymore

### ISSUE THREAD

**Issue by islanddog** [GhostWriters/DockSTARTer#1001]
# Feature request

**Is your feature request related to a problem? Please describe.**
No; love DockSTARTer and have been using it for a while now.

**Describe the solution you'd like**
xTeve - https://hub.docker.com/r/dnsforge/xteve

**Describe alternatives you've considered**
I tried all over DVR/IPTV integrations and xTeve v2 actually has a solid foundation now

**Additional context**
Thanks.

**Comment by angrycuban13** [comment]
I believe I worked on an override for someone on this so it shouldn't be hard to implement!
