### ISSUE TITLE
speedtest-tracker

### ISSUE THREAD

**Issue by rubadub-github** [GhostWriters/DockSTARTer#1017]
This is a app/function that exists on organizr for adding a speedtest to the homepage.

----------------------------------------------------------

  speedtest-tracker:
    hostname: ${DOCKERHOSTNAME}
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
     - TZ=${TZ}
     - OOKLA_EULA_GDPR=true
     - MAXMINDDB_LICENSE_KEY=XXXXXXXXXXXXXXXXXXXXXX
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8765:80
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERSHAREDDIR}:/shared
      - ${DOCKERCONFDIR}/speedtest-tracker:/config:rw
    container_name: speedtest-tracker

**Comment by angrycuban13** [comment]
This was already added in #987 

Make sure you update DS for latest changes! :)
