### ISSUE TITLE
Super simple lightweight http server to share files/pages -- http-server

### ISSUE THREAD

**Issue by rubadub-github** [GhostWriters/DockSTARTer#1018]
I use this container to host a file server (locally) to access my shared files, especially to sideload APKs to my FireTV boxes and the like.  Might be very limited in functionality and usefulness, but I figured I'd share my overrides for people to review.

these are not really needed, but I made my override identical to the default apps:
     - ${DOCKERSHAREDDIR}:/shared
     - ${DOCKERCONFDIR}/http-server:/config:rw

this might want to be a different location, but this is where I put mine:
     - ${DOWNLOADSDIR}/http-server:/html:rw
![Annotation 2020-07-29 091844](https://user-images.githubusercontent.com/68559237/88811779-968a0900-d17c-11ea-9261-9fc121296592.jpg)

-------------------------------------------------------

  http-server:
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
     - TZ=${TZ}
     - FILE_SERVER_TITLE=${DOCKERHOSTNAME} HTTP File Server
    hostname: ${DOCKERHOSTNAME}
    image: patrickdappollonio/docker-http-server
    ports:
     - 5000:5000
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ${DOCKERSHAREDDIR}:/shared
     - ${DOCKERCONFDIR}/http-server:/config:rw
     - ${DOWNLOADSDIR}/http-server:/html:rw
    container_name: http-server

**Comment by nemchik** [comment]
Interesting idea 👍

**Comment by angrycuban13** [comment]
That is quite interesting. Should be easier than any of the ones that are on my to-do
