### ISSUE TITLE
Deprecating organizrtools/organizr-v2

### ISSUE THREAD

**Issue by islanddog** [GhostWriters/DockSTARTer#1024]
# Bug report

**Describe the bug**
A recent notification on Organizr shows the following -

Organizrtools/organizr-v2 is being deprecated, breaking changes are coming to Organizr, which this container wont be updated to handle. Please refer to the migration note for details Container migration note

**To Reproduce**
Available under settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/16761753/89093276-b03e7280-d36d-11ea-89e2-bd8bb52419e7.png)

**System**
N/A

**Additional context**
https://github.com/Organizr/docker-organizr#migration

I guess a new container will need to be added or replaced?

**Comment by nemchik** [comment]
This was handled here https://github.com/GhostWriters/DockSTARTer/pull/904

Run
```
ds -u
ds -c pull
ds -c
```
And you should be updated.
