### ISSUE TITLE
Let's Encrypt Reverse Proxy

### ISSUE THREAD

**Issue by islanddog** [GhostWriters/DockSTARTer#1028]
I feel like this will be a simple answer but I don't know if I should ask here, on the docker-letsencrypt or somewhere else? I setup a reverse proxy for my Emby, Sonarr, etc. It works for 24hours and then dies. I see my Public IP being updated and if I go to it I can see LetsEncrypt default page running without issue. If I switch my records from CNAMEs to A records it works for another 24hours and dies. Something to do when my Public IP updates. 

Did I configure something on the Docker wrong?

Thanks
Chris

**Comment by nemchik** [comment]
It sounds like you need a dynamic dns updater. I would consider duckdns or ddclient.

duckdns is simpler. you sign up for a subdomain like islanddog.duckdns.com and run the container with your duckdns token and it keeps the subdomain up to date with your ip address. you point your real domain to the duckdns subdomain as a cname record.

ddclient would let you directly update whatever provider you have your domain through but the setup is more complex and your provider has to offer a way to perform the update that ddclient is capable of doing (it's pretty configurable, but again it's complex).

**Comment by islanddog** [comment]
Thanks for the assistance. I was using DDClient already but for some reason when my public IP changed on my home network my reverse proxy would stop working as well. I think I set up a record incorrectly at the TLD that was preventing the sub-domains from forwarding correctly. Going to keep an eye on it but **hopefully** its fixed now.

Again thanks for all the help!
