### ISSUE TITLE
PiHole ports seems to be wrongly generated in the /docker-compose.yml

### ISSUE THREAD

**Issue by bunkermagnus** [GhostWriters/DockSTARTer#1029]
# Bug report

**Describe the bug**

Installing Dockstarter on a raspberry pi, after picking my applications the Composer fails with the current error messages:

> ERROR: The Compose file './docker-compose.yml' is invalid because:
> services.pihole.ports contains an invalid type, it should be a number, or an object
> services.pihole.ports contains an invalid type, it should be a number, or an object
> services.pihole.ports contains an invalid type, it should be a number, or an object
> 2020-08-04 20:35:26 [FATAL ]   Docker Compose failed.
> 2020-08-04 20:35:26 [ERROR ]   DockSTARTer did not finish running successfully.

After some looking around it seems like the .yml file record for the ports section of the pihole app are wrong:

> pihole:
>     image: pihole/pihole
>     hostname: ${DOCKERHOSTNAME}
>     ports:
>       - ${PIHOLE_PORT_443}:443
>       - ${PIHOLE_PORT_80}:80
>       - ${PIHOLE_SERVERIP}:${PIHOLE_PORT_53}:53
>       - ${PIHOLE_SERVERIP}:${PIHOLE_PORT_53}:53/udp
>       - ${PIHOLE_SERVERIP}:${PIHOLE_PORT_67}:67/udp
> 

This is what my .env file looks like for pihole:

> PIHOLE_ENABLED=true
> PIHOLE_NETWORK_MODE=
> PIHOLE_PORT_443=446
> PIHOLE_PORT_53=53
> PIHOLE_PORT_67=67
> PIHOLE_PORT_80=8008
> PIHOLE_SERVERIP=192.168.x.x
> PIHOLE_WEBPASSWORD=
> 

**To Reproduce**

I followed the instructions to the letter, Composer works fine if I un-pick pihole from the list of selected apps. 

**System**

Raspberry Pi 3
Raspbian 32-bits 
Linux gollum 5.4.51-v7+ #1327 SMP Thu Jul 23 10:58:46 BST 2020 armv7l GNU/Linux
"Raspbian GNU/Linux 10 (buster)"

**Comment by nemchik** [comment]
Do you have `PIHOLE_SERVERIP` set to `192.168.x.x` (literally)? It needs to be the ip address of your server.

**Comment by bunkermagnus** [comment]
OK, I guess it's a bit confusing in what order the setup scripts have to be run, I will give it a try on occasion. you migth as well close the ticket then if this is the reason for the problems in the composer file.

thanks,
Magnus

**Comment by nemchik** [comment]
If you still need help with this after setting that variable feel free to reopen.

**Comment by LandonStewart** [comment]
I had the same problem (.env had the setting PIHOLE_SERVERIP=192.168.x.x) but with an override in docker-compose.override.yml to the actual IP address.  

Partial override in docker-compose.override.yml:
```
  pihole:
    environment:
      - ServerIP=192.168.1.199
```

After seeing this thread I changed the .env file to:
```
...
PIHOLE_SERVERIP=192.168.1.199
...
````

Things worked after that.
