### ISSUE TITLE
PiHole

### ISSUE THREAD

**Issue by fordsteve** [GhostWriters/DockSTARTer#1056]
# Bug report

**Describe the bug**
Couldnt install PiHole because ./docker-compose.yml is invalid because services.pihole.ports contains an invalid type, it should be a number or an object.

**To Reproduce**
After a clean install using DBTech's DockSTARTer guide on RPi4, Pihole created errors during install and broke the install chain. After deselecting PiHole in the apps install the automated setup could continue and i have containers etc installed in portainer. I went back to install PiHole via DS and the errors still appeared during install.

Can you please help?

Thanks

- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**System**
(please complete the following information):

- OS: [e.g. Debian]

**Additional context**

**Comment by dylanmtaylor** [comment]
Hi, this issue is caused by the PIHOLE_SERVER_IP variable not being set. It defaults to 192.168.x.x, which is not valid. Configure it to be the IP address of your machine and it will work.

**Comment by dylanmtaylor** [comment]
Maybe this could be changed? It does need to be set to work correctly https://github.com/GhostWriters/DockSTARTer/blob/master/compose/.apps/pihole/pihole.labels.yml#L13

**Comment by fordsteve** [comment]
Thank you!

**Comment by fordsteve** [comment]
I have corrected the IP addresses, but every time i run compose my changes get reset. How do i finish the setup process please?

**Comment by dylanmtaylor** [comment]
> I have corrected the IP addresses, but every time i run compose my changes get reset. How do i finish the setup process please?

Set the IP via the menu in DockSTARTer. There is a menu item to set application variables

**Comment by fordsteve** [comment]
thank you, i will update ds now.

**Comment by fordsteve** [comment]
Thats now installed PiHole after i changed the IP to my dockstarter ip address. I will leave it to do any updates for a while as Portainer is telling me the container is unhealthy for some reason. i only changed the one IP in the menu?

I appreciate your time all, thanks for your support!

**Comment by fordsteve** [comment]
I have just inspected the container in Portainer and there isn’t an IP address as shown below:

],
            "80/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8008"
                }
            ]

My IP has been set for the other ports though?

**Comment by fordsteve** [comment]
Here is my port configuration for the container.


Port configuration	
0.0.0.0:446  443/tcp 
192.168.0.25:53  53/tcp 
192.168.0.25:53  53/udp 
192.168.0.25:67  67/udp 
0.0.0.0:8008  80/tcp


Shall I remove the container and try again from fresh?

**Comment by fordsteve** [comment]
Health check over and i have managed to login to Pihole!!

Fantastic!! strange that the ports do not show the IP though, but i have been able to get in?

**Comment by nemchik** [comment]
I would avoid using portainer to make any changes. It's fine to look, but not too touch :)

**Comment by fordsteve** [comment]
Got it!!

Appreciate your help, thank you.

Steve Ford
UK Tequila Forum
www.uktequilaforum.co.uk
