### ISSUE TITLE
On the qBitTorrentVPN container, files do not get saved to the Downloads folder by default

### ISSUE THREAD

**Issue by dylanmtaylor** [GhostWriters/DockSTARTer#1082]
In order to save files to /mnt/downloads or whatever volume is mounted into the container, you need to manually set the download path within qBitTorrent to /downloads, the default is /config/qBittorrent/downloads/ and this writes downloads to a different location than expected.

**Comment by nemchik** [comment]
If there's an environment variable we could set for the default that might resolve the issue, but we wouldn't want to prevent users from setting up subfolders and pointing downloads there. DS uses the downloadsdir variable for all download clients, and some users prefer to setup subfolders for different types like usenet vs torrents or even client specific folders.

**Comment by dylanmtaylor** [comment]
> If there's an environment variable we could set for the default that might resolve the issue, but we wouldn't want to prevent users from setting up subfolders and pointing downloads there. DS uses the downloadsdir variable for all download clients, and some users prefer to setup subfolders for different types like usenet vs torrents or even client specific folders.

I just made a pull request to mount the $DOWNLOADSDIR variable to the default location for qBitTorrentVPN. This mirrors the behavior of qBitTorrent from a user's perspective

**Comment by dylanmtaylor** [comment]
This is what it looks like by default when you add a torrent:
![Screenshot from 2020-09-03 12-56-57](https://user-images.githubusercontent.com/277927/92144433-b3050b00-ede4-11ea-9867-6502dd65a410.png)


Most users would not know they need to change this to save to $DOWNLOADDIR, leading to for instance filling up a boot drive when expecting files to be written to a storage drive.

**Comment by dylanmtaylor** [comment]
Fixed in #1083
