### ISSUE TITLE
linuxserver/plexrequests no longer exists

### ISSUE THREAD

**Issue by dylanmtaylor** [GhostWriters/DockSTARTer#1085]
This container can't be pulled. https://hub.docker.com/search?q=linuxserver%2Fplexrequests&type=image

Looks to be archived. https://github.com/linuxserver-archive/docker-plexrequests#:~:text=linuxserver%2Fplexrequests,sonarr%20and%20sickrage%20etc...

**Comment by angrycuban13** [comment]
We are aware. It isn't part of our app list. 

Our website redirects you to the Ombi page as well.

**Comment by nemchik** [comment]
https://github.com/GhostWriters/DockSTARTer/blob/master/compose/.apps/plexrequests/plexrequests.labels.yml our labels have it as deprecated. the DS GUI doesn't list deprecated apps. you can still try to add it with `ds -a plexrequests` but will see deprecation warnings.

**Comment by dylanmtaylor** [comment]
Ah, I was trying to add logic to check the listed images to the CI and it picked up on this. That makes sense.
