### ISSUE TITLE
New App: PhotoStructure

### ISSUE THREAD

**Issue by jchelin-whispir** [GhostWriters/DockSTARTer#1087]
# Feature request

**Is your feature request related to a problem? Please describe.**

Nope. Just looking to have a new app included in DockSTARTerif possible.

**Describe the solution you'd like**

As a user of DockSTARTer, I want to be able to install Photostructure via the DockSTARTer interface, so that I can use Photostructure on my server.

https://photostructure.com/server/photostructure-for-docker-compose/

**Describe alternatives you've considered**

Doing the override myself. I can't figure it out :(

**Additional context**

I think this would be a great alternative to Piwigo!

**Comment by angrycuban13** [comment]
Just tested it locally. Will be issuing a PR soon. 

I like the layout of it.
