### ISSUE TITLE
Huginn

### ISSUE THREAD

**Issue by rufflepot** [GhostWriters/DockSTARTer#1098]
# Feature request

**Is your feature request related to a problem? Please describe.**
IFTTT, one of the largest automation services available, recently turned into a paid service, instead creating a "free tier" with access to only 3 applets total. An alternative is needed and Huginn seems a great contender. From their README.md: "Huginn is a system for building agents that perform automated tasks for you online. They can read the web, watch for events, and take actions on your behalf. Huginn's Agents create and consume events, propagating them along a directed graph. Think of it as a hackable version of IFTTT or Zapier on your own server. You always know who has your data. You do."

**Describe the solution you'd like**
Implementing Huginn in the DockSTARTer system.

**Describe alternatives you've considered**
Self-hosting Huginn directly on the server or via a regular Docker container, potentially with a full app override in order to function together with DockSTARTer. This is of course entirely viable. 

**Additional context**
Huginn on GitHub: https://github.com/huginn/huginn

![68747470733a2f2f7261772e6769746875622e636f6d2f687567696e6e2f687567696e6e2f6d61737465722f6d656469612f687567696e6e2d6c6f676f2e706e67](https://user-images.githubusercontent.com/23452475/92907476-a7899380-f425-11ea-8388-7d34ea2c6a35.png)

**Comment by angrycuban13** [comment]
I will look into this.
