### ISSUE TITLE
env variable not in the 'depreciated' list

### ISSUE THREAD

**Issue by rubadub-github** [GhostWriters/DockSTARTer#1101]
with the new release of DS and the move to /storage this was not moved to the depreciated list:
**MEDIADIR_PICTURES=/mnt/medialibrary/pictures**

likely added w/ Photoshow

**Comment by nemchik** [comment]
`MEDIADIR_PICTURES` has never been defined as a global in DS. If you added this to your .env on your own it would be sorted in with application variables at the bottom.

**Comment by rubadub-github** [comment]
OK - not sure where it came from then.  But it was in my list.  I don't think I added it manually.  Is there an easy way to see if it is actually being used?

**Comment by nemchik** [comment]
Look in your compose and override file in ~/.docker/compose

If you don't see that variable in those files it's not being used. If it's in the override file it's but not in the compose file is probably something you added (possibly via advice from our discord).

**Comment by rubadub-github** [comment]
~/.docker/compose$ grep -r MEDIADIR_PICTURES
.env:MEDIADIR_PICTURES=/mnt/medialibrary/pictures


weird -- I just deleted it, and did a ds -c up and it didn't come back
