### ISSUE TITLE
App Request: InvoiceNinja (CRM)

### ISSUE THREAD

**Issue by pseudohero** [GhostWriters/DockSTARTer#1118]
# Feature request

**Describe the solution you'd like**
Add InvoiceNinja (https://hub.docker.com/r/invoiceninja/invoiceninja) to the list of apps in DS.

**Additional context**
I understand there may be other CRMs available but having at least one would be ideal as even if people don’t use it, they can install it to see what the compose file looks like (especially if they are new to utilising databases).

**Comment by angrycuban13** [comment]
Okay so this one is a bit more "complicated" than what DS offers simply because you have to generate an `APP_KEY` per their documentation. We are looking into how to get this going though.

**Comment by angrycuban13** [comment]
@pseudohero have you gotten this to work in Docker at all? I can't even get it to create tables on the `mariadb` container I have and I can't access the Web GUI at all.

**Comment by pseudohero** [comment]
> @pseudohero have you gotten this to work in Docker at all? I can't even get it to create tables on the `mariadb` container I have and I can't access the Web GUI at all.

I gave up when I managed to break my whole setup. I’m not super au fait with DBs and the like which is why I made this post (in the hopes I didn’t have to mess things up by doing it myself). Sorry!

**Comment by angrycuban13** [comment]
We are still taking a crack at it, no worries. I wanted to know if I had made a mistake along the way.

**Comment by angrycuban13** [comment]
Me and someone else were not able to get it running at all. If you can somehow get it running please feel free to open a new issue with some steps to guide me right way.

Sorry!
