### ISSUE TITLE
Can't Install Tdarr

### ISSUE THREAD

**Issue by hdy2jsd3** [GhostWriters/DockSTARTer#1141]
# Bug report

**Describe the bug**
When attempting to install Tdarr container I receive the following compose error:

"ERROR: for tdarr  Cannot create container for service tdarr: create .: volume name is too short, names should be at least two alphanumeric characters"

**To Reproduce**
Steps to reproduce the behavior: Select Tdarr as an app and run compose.

**Expected behavior**
Tdarr container will be installed.

**Screenshots**

**System**
<img width="534" alt="Screen Shot 2020-10-09 at 12 22 49 PM" src="https://user-images.githubusercontent.com/51751426/95607853-51ab0a00-0a2a-11eb-97ab-fa2df4bf43f0.png">

- OS: Mint
- Version 20.0

**Additional context**
None.

**Comment by nemchik** [comment]
Check in `~/.docker/compose/.env` file (edit in any text editor) for `TDARR_TRANSCODE_CACHE` and make sure you have that set to a folder and not blank. Then run `ds -c`.

The defaults should probably be adjusted so I'll have a look at them and keep this open.

**Comment by angrycuban13** [comment]
I left that variable empty as some people might prefer to use a RAM disk or SSD but I can add it to the default appdata folder

**Comment by hdy2jsd3** [comment]
Argh! I've been messing with it forever... I think a default folder would help out a lot of people.

Working now. Thanks guys!

**Comment by hdy2jsd3** [comment]
Argh! I've been messing with it forever... I think a default folder would help out a lot of people.

Working now. Thanks guys!

**Comment by hdy2jsd3** [comment]
Argh! I've been messing with it forever... I think a default folder would help out a lot of people.

Working now. Thanks guys!
