### ISSUE TITLE
Adding filebrowser

### ISSUE THREAD

**Issue by LastReaction** [GhostWriters/DockSTARTer#1145]
# Feature request

**Describe the solution you'd like**
Adding filebrowser would be a nice asset to this software. It has a bunch of great features such as creating multiple users and adjusting permissions for each user, built in authentication, deleting, moving, copying and renaming files, and more. It already has a Docker image out of the box.

https://github.com/filebrowser/filebrowser

**Describe alternatives you've considered**
h5ai is good, but its fairly basic and doesn't have as many features as filebrowser. In other words, filebrowser would be a better alternative.

**Comment by angrycuban13** [comment]
Isn't FileBrowser the one that you have to pay to use or something like that?

**Comment by LastReaction** [comment]
I'm using it on my server right now with the docker override feature, its free.

**Comment by nemchik** [comment]
At some point in the past I declined adding this to DS because it was not actively maintained. It seems development has picked up and the project doesn't seem to have the warning in the readme anymore. I'm fine with this being added.

**Comment by nemchik** [comment]
https://github.com/GhostWriters/DockSTARTer/issues/296 Was where this was discussed. It looks like https://github.com/filebrowser/filebrowser/issues/532 is now closed as resolved (the project is now being actively maintained).

**Comment by LastReaction** [comment]
Swizzin uses it now in their repo, and its come along way since 2018. Its great if you don't want to SSH into your server but want to move files around quickly, or even for sharing files with friends or family.

**Comment by angrycuban13** [comment]
I'll work on it then 👍

**Comment by LastReaction** [comment]
Awesome, thank you for taking the time to add this!
