### ISSUE TITLE
Duplicacy

### ISSUE THREAD

**Issue by rufflepot** [GhostWriters/DockSTARTer#1151]
# Feature request

**Is your feature request related to a problem? Please describe.**
There are many ways of automatically backing up data into the cloud, and [Duplicacy](https://duplicacy.com/) is one of the better ones. It can be used both through cli for free, or by using the web UI for subscribing users. A huge amount of cloud storage providers are available out of the box (Microsoft Azure, Google Cloud, Wasabi, BackBlaze etc), as well as backing up to local storage. It uses content-defined chunking, as does most backup solutions, but is the only one that also does [lock free deduplication](https://github.com/gilbertchen/duplicacy/wiki/Lock-Free-Deduplication). This helps a lot with saving storage space for the backups as well as minimizing the risk for corrupt restorations (a common issue for Duplicati).

**Describe the solution you'd like**
Implementing Duplicacy in the DockSTARTer system. Additionally, for users already on a subscription, the MACHINE_ID environment variable could either be manually input via DockSTARTer or possibly have /var/lib/dbus-machine-id mounted read only by default for Duplicacy to scrape it on its own, if this is possible.

**Describe alternatives you've considered**
Self-hosting Duplicacy directly on the server (which is what I am doing right now) or via the regular [Docker container](https://hub.docker.com/r/erichough/duplicacy), potentially with a full app override in order to function together with DockSTARTer. This is of course entirely viable.

**Additional context**
Duplicacy website: https://duplicacy.com/
Docker container on GitHub: https://github.com/ehough/docker-duplicacy
Docker container on DockerHub: https://hub.docker.com/r/erichough/duplicacy

![dwe_dashboard](https://user-images.githubusercontent.com/23452475/95978934-286bee80-0e1b-11eb-9f40-0117fce2d75f.png)

**Comment by nemchik** [comment]
I think this just got added in https://github.com/GhostWriters/DockSTARTer/pull/1147

If you run `ds -u` you will update DS, and then you can run `ds -a duplicacy` to add the variables to your `.env` file. After setting them the way you want you can run `ds -c` to start the container. Please let us know if you have any issues with this.
