### ISSUE TITLE
Requesting LDAP

### ISSUE THREAD

**Issue by LeaderbotX400** [GhostWriters/DockSTARTer#1170]
# Feature request

**Is your feature request related to a problem? Please describe.**
it would be nice to have a LDAP system built in to the list for easier install

**Describe the solution you'd like**
add some form of LDAP container like linuxserver/ldap-auth

**Comment by nemchik** [comment]
I have no issue adding that specific image, but to be clear it is a connector piece between an LDAP server and an nginx instance. That image is not an LDAP server.

**Comment by angrycuban13** [comment]
Can you please find a well maintained container/project for LDAP and we'll look into adding it

**Comment by LeaderbotX400** [comment]
https://github.com/osixia/docker-openldap looks like a rather well maintained container for LDAP

**Comment by LeaderbotX400** [comment]
also adding the ldap-auth image would be nice for people who want to use LDAP with NGINX but its fine not to have it

**Comment by angrycuban13** [comment]
Sure, create a separate issue for LDAP-Auth in order for me to keep track of it better.

**Comment by LeaderbotX400** [comment]
ok
