### ISSUE TITLE
install not working

### ISSUE THREAD

**Issue by paul-asvb** [GhostWriters/DockSTARTer#1172]
# Bug report

**Describe the bug**
I created a new user with sudo rights.

**To Reproduce**
1. empty ubuntu 20 server
2. Follow README

**Expected behavior**
Error below

**Screenshots**
![Screenshot from 2020-11-05 19-21-18](https://user-images.githubusercontent.com/4126256/98280886-58329000-1f9c-11eb-8b0d-2fa36babeddb.png)

**System**
Ubuntu 20

**Comment by nemchik** [comment]
if you run `whoami` and it says `root` you are not logged in as the user with sudo, you're logged in as root. Verify that. If you are logged in as the user with sudo run `ds -fiv`.

**Comment by angrycuban13** [comment]
@paul-asvb is this issue still on-going?

**Comment by paul-asvb** [comment]
Reinstalled the OS. Then it worked. Thanks for the help
