### ISSUE TITLE
filebrowser mapping to port 80, instead of port 8080

### ISSUE THREAD

**Issue by amitsax** [GhostWriters/DockSTARTer#1175]
https://github.com/GhostWriters/DockSTARTer/blob/54457cb5bdef1803e89289e8c19fecb014ebb356/compose/.apps/filebrowser/filebrowser.ports.yml#L4

**Comment by amitsax** [comment]
Since FB_PORT is setting value to .env var FILEBROWSER_PORT_8080 - 
server in container starts on FILEBROWSER_PORT_8080 port; but here port FILEBROWSER_PORT_8080 is being mapped to default web port 80.
I think in YML it needs to be 
    ports:
    - ${FILEBROWSER_PORT_8080}:${FILEBROWSER_PORT_8080}
So that server starts at port that is being mapped for outside access.

**Comment by nemchik** [comment]
You are correct. I'm not entirely sure why we have 8080 involved at all. I'll fix this.
