### ISSUE TITLE
Failed to install the latest docker-compose

### ISSUE THREAD

**Issue by vitpachecol** [GhostWriters/DockSTARTer#1180]
In a fresh new install on a RPi 4+ 4GB is giving me issues whenever I run the compose command.
This is what I see when running `sudo ds -c`

```
Error: No such image: linuxserver/docker-compose:latest
2020-11-24 12:32:28 [ERROR ]   Failed to install the latest docker-compose.
2020-11-24 12:32:28 [FATAL ]   Failed to install the minimum required docker-compose.
2020-11-24 12:32:28 [ERROR ]   DockSTARTer did not finish running successfully.
```

**Comment by nemchik** [comment]
Can you try running the following:

```bash
curl -fsL "https://raw.githubusercontent.com/linuxserver/docker-docker-compose/master/run.sh" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
rm -f /usr/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

docker-compose --version
```

**Comment by vitpachecol** [comment]
There's something funky going on. I was able to to another fresh restart on my server and it's working. I believe I got some errors previously when I was installing DS.

I ended up having to reset my Pi and start from scratch because my Plex wouldn't connect, which I'm led to think because of an update that was pushed overnight.
I keep getting `No Soup for You`, with a few errors in the logs, but hard to say if this is a Plex issue, or DockStarter

**Comment by vitpachecol** [comment]
OK, I just figured out that, with the Plex update, I needed to change the tag to `bionic` instead of the default within the override file.

**Comment by nemchik** [comment]
I can adjust that in DS. That's a very recent change. Thanks for catching it.

**Comment by vitpachecol** [comment]
Thanks! It came from this thread https://github.com/linuxserver/docker-plex/issues/247

**Comment by vitpachecol** [comment]
On that note, do you know why image pulls have been so slow lately? A `docker pull` is a lot faster than when I run compose after enabling certain apps.

**Comment by nemchik** [comment]
By comparison to about a month ago:

DockerHub started limiting the number of pull request an anonymous user could make over a period of time. LSIO began releasing all of their images on GitHub Container Registry. DS switched to pulling LSIO images from GHCR. I have seen others mention it to be slower, but I have not had this issue personally.

Aside from that I could not say why the pull itself would be slow without a better frame of reference (slower compared to what/when?).

**Comment by vitpachecol** [comment]
It's hard to say as I haven't changed anything on my server for at least a month, so if I had to guestimate, it would be compared to last month. 
Pardon my ignorance, but where does `docker pull` pull from? I noticed that it's at least 10x faster than running `ds -c up x`

**Comment by vitpachecol** [comment]
Closing this issue now as it's been resolved. Thanks @nemchik
