### ISSUE TITLE
Home Assistant - detect which image to use

### ISSUE THREAD

**Issue by Tosko4** [GhostWriters/DockSTARTer#1202]
Currently, assuming that DS checks the architecture of the OS, it grabs the corrisponding image. (Aarch64 (64 bit) or the armv7l  (32 bit))

When the OS is armv7l, the corrisponding file is adressed: https://github.com/GhostWriters/DockSTARTer/blob/master/compose/.apps/homeassistant/homeassistant.armv7l.yml

But here the raspberrypi3 image specifically is used here.. i own a raspberrypi4 and had to use that one instead. So currently overwriting the config, but it would be neat to detect the raspberry it’s on. 

When you run the command on a raspberry, you get the version and model too: `cat /sys/firmware/devicetree/base/model`

![CF87D5EE-F98D-4324-8114-C3C759F56867](https://user-images.githubusercontent.com/1294707/102084907-266fdd00-3e16-11eb-962e-7300225d549e.jpeg)

Would be nice to have an automated proces to pick the right image for your device :)

**Comment by nemchik** [comment]
A rpi4 can run a 64 bit OS (recommended) and when doing so DS will have your system use the `aarch64` (aka `arm64) files such as https://github.com/GhostWriters/DockSTARTer/blob/master/compose/.apps/homeassistant/homeassistant.aarch64.yml as opposed to the `armv7l` files (aka `armhf` or `arm32`).

DS uses the `uname -m` command to determine which CPU architecture you have.

**Comment by Tosko4** [comment]
@nemchik i understand what you write here. I was expecting this already. 

It is not up to DS to decide what architecture one should run, i could also have a rpi4 with only 1 or 2 GB ram. A 64 bit OS is in that case not recommended. but this feature request is to check what home assistant image fits best for your device (drivers etc)

Step 1: what architecture is used as OS (this part is already live)
Step 2: determen the actual hardware equipment one has. RPi3 or 4. And use the proper image for that. 

Now, when one runs a 32 bit OS, home assistant raspberry pi 3 image is installed, while the image for 4 on a 4 works better than an image for 3 on a 4. That’s why I suggested this improvement.

**Comment by nemchik** [comment]
At the moment ds doesn't do any hardware detection beyond cpu architecture. The intention of the templates in ds isn't too cater to specific hardware, rather just to be available and usable on many performs.

What it sounds like is maybe we want to use a better choice for an armv7l image for home assistant. One that caters more generally to different arm32 as a whole and less specifically to rpi 3 or 4.

Aside from that, DS also let's you override templates https://dockstarter.com/overrides/introduction/ so you can absolutely use the image you want.

Lastly, the hardware would still need to be exposed to the container (using overrides) regardless of which image we include in the DS templates.
