### ISSUE TITLE
Addition to existing app list: Yacht

### ISSUE THREAD

**Issue by Tosko4** [GhostWriters/DockSTARTer#1212]
Yacht has proven itself to be a very strong alternative to Portainer. Where Portainer is aimed for the more advanced users, Yacht is doing a very good job for junior people in this world to easier maintain and control their docker environment. 

Therefor this app I believe should have a place in wonderful DockSTARTer!

https://hub.docker.com/r/selfhostedpro/yacht

this is the official image

**Comment by angrycuban13** [comment]
Not a bad project. I will look into a PR soon. I like the optional ability to remove auth which Portainer went away with in their latest major release.

**Comment by SelfhostedPro** [comment]
Thanks! Really appreciate the support! I was just looking into submitting a PR for this. @angrycuban13 I am a huge fan of DockSTARTer! if you have any recommendations for yacht feel free to reach out.
