### ISSUE TITLE
Node-red

### ISSUE THREAD

**Issue by emiller233** [GhostWriters/DockSTARTer#1216]
# Feature request

could node-red be on the app list ? can you add it?

**Comment by angrycuban13** [comment]
Can you please provide some more details such as GitHub repo and Docker Hub?

**Comment by myozone** [comment]
Node-red can be added to Docker mentioned here https://nodered.org/docs/getting-started/docker at it's Github is here https://github.com/node-red/node-red.

**Comment by emiller233** [comment]
sorry it took me so long to write back! but yes those are the correct links
