### ISSUE TITLE
Added apps please 

### ISSUE THREAD

**Issue by myozone** [GhostWriters/DockSTARTer#1217]
Node-red and Comskip would be welcome additions to Docksarter.

**Comment by angrycuban13** [comment]
#1216 is already asking for Node-Red and I'm waiting to hear back from them.

Can you please share the GitHub page for `Comskip` as well as any official Docker Hub pages or community supported Docker Hub pages?

**Comment by myozone** [comment]
Thanks for the quick reply, Comskip Github is here https://github.com/erikkaashoek/Comskip I'll look at the other link !

**Comment by angrycuban13** [comment]
I'm not seeing an official Docker image on their repo. Is there an unofficial one that's being actively developed on?

**Comment by myozone** [comment]
I don't think Comskip has a Docker image .

**Comment by CLHatch** [comment]
A quick search on Docker Hub shows that there is an official Docker image, but it hasn't been updated in a year, and has a note that it's not usable yet, and not to use it.  But there are also other images that have been updated within a couple weeks.

https://hub.docker.com/search?q=comskip&type=image&sort=updated_at&order=desc

**Comment by angrycuban13** [comment]
I can't find where the repository source for the most recently updated image is. All other images are pretty old. If you find an image that is actively being maintained with a source code readily available we will happily add `ComSkip`.

**Comment by angrycuban13** [comment]
#1220 will add Node-RED though. Just needs to be merged to master.
