### ISSUE TITLE
Please add Unpackrr

### ISSUE THREAD

**Issue by RinnosukeETQW** [GhostWriters/DockSTARTer#1218]
Please add Unpackrr to the list, getting kind of tired of unpacking .rars manually

**Comment by angrycuban13** [comment]
Please provide the GitHub page and the Docker Hub page for this project

**Comment by RinnosukeETQW** [comment]
Github: https://github.com/davidnewhall/unpackerr

Docker Hub: https://hub.docker.com/r/golift/unpackerr

**Comment by CLHatch** [comment]
There's also a hotio image: https://hub.docker.com/r/hotio/unpackerr
