### ISSUE TITLE
Plexanisync

### ISSUE THREAD

**Issue by RinnosukeETQW** [GhostWriters/DockSTARTer#1224]
Might be a little harder then my previous request due to it needing auth from anilist (they use an API token) and a plex token. Syncs any anime played in plex to anilist (anilist.co)

Github: https://github.com/RickDB/PlexAniSync

Dockerhub: https://hub.docker.com/r/rickdb/plexanisync

**Comment by angrycuban13** [comment]
I got it running, not too difficult. I will PR it at some point
