### ISSUE TITLE
[BUG] - YouTube-DL Environmental Variables

### ISSUE THREAD

**Issue by apperrault** [GhostWriters/DockSTARTer#1236]
# Bug report

**Describe the bug**
When using Youtube-DL it doesn't honor the download paths set in the .env file.

**To Reproduce**
Install Youtube-dl and set the download path to /storage/$PATH and it doesn't download to that path:

**Expected behavior**
You would expect that the app would use the specified download path.

**System**
(please complete the following information):

- OS: Ubuntu 
- Version 20.04

**Comment by angrycuban13** [comment]
Addressed by repo owner [here](https://github.com/nbr23/youtube-dl-server/issues/24#issuecomment-754995709)
