### ISSUE TITLE
[Feature Request] Nextcloud Configuration Instructions

### ISSUE THREAD

**Issue by highaltidude** [GhostWriters/DockSTARTer#1244]
**Is your feature request related to a problem? Please describe.**
Additional instructions regarding setting up NextCloud, could deter new users from using the container.

**Describe the solution you'd like**
Instructions to setup Nextcloud with MariaDB. 

**Additional context**
Reference to #571 . Responses to issue led me in the right direction. After I installed MariaDB & PHPadmin I was able to create a DB & DB user for Nextcloud setup. In addition, I was unable to use localhost as the server and I was forced to use the IP address of the server.

Thanks! Enjoying the project!

**Comment by angrycuban13** [comment]
Addressed in d61a94c

**Comment by angrycuban13** [comment]
Fixed in #1291
