### ISSUE TITLE
[BUG] PlexAniSync does not compose

### ISSUE THREAD

**Issue by LadySmith** [GhostWriters/DockSTARTer#1274]
# Bug report

**Describe the bug**
PlexAniSync does not compose. Removing all other containers except watchtower, result is still same. Also tried default app installation. Seems like `/runsync.sh` is failing?

**To Reproduce**
1. use command `ds`
2. enter `configuration`
3. navigate to `full setup`
4. select `PlexAnisync` (other one is watchtower)
5. get `[WARN ]   Failed to include /home/ladysmith/.docker/compose/.apps/plexanisync/plexanisync.ports.yml file.`
6. Profit.

**Expected behavior**
Should've composed. Like all other apps. Checked DockSTARTer documents for info (e.g. insufficent folder permissions etc.) Also checked docker hub.

**Screenshots**
Check additional context for log.

**System**
- Ubuntu 20.04.2 LTS
- Docker version 20.10.3, build 48d30b5
- docker-compose version 1.27.4, build 40524192
- DockSTARTer is up-to-date

**Additional context**

```
ladysmith@xbooru-ubuntu:[~]: ds
2021-02-08 05:00:43 [NOTICE]   Preparing app menu. Please be patient, this can take a while.
2021-02-08 05:00:49 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
2021-02-08 05:00:55 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
2021-02-08 05:00:55 [NOTICE]   Adding compose configurations for enabled apps. Please be patient, this can take a while.
2021-02-08 05:00:55 [WARN  ]   Failed to include /home/ladysmith/.docker/compose/.apps/plexanisync/plexanisync.ports.yml file.
Starting plexanisync ...
Starting plexanisync ... error

ERROR: for plexanisync  Cannot start service plexanisync: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/runsync.sh": stat /runsync.sh: no such file or directory: unknown

ERROR: for plexanisync  Cannot start service plexanisync: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/runsync.sh": stat /runsync.sh: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
2021-02-08 05:01:00 [FATAL ]   Docker Compose failed.
Failing command: eval docker-compose "up -d --remove-orphans"
DockSTARTer did not finish running successfully.
```

**Comment by angrycuban13** [comment]
> # Bug report
> **Describe the bug**
> PlexAniSync does not compose. Removing all other containers except watchtower, result is still same. Also tried default app installation. Seems like `/runsync.sh` is failing?

Yep looks like they decided to remove that?? Lol. Will PR a fix.
