### ISSUE TITLE
Guacamole image has been archived

### ISSUE THREAD

**Issue by fbartels** [GhostWriters/DockSTARTer#1279]
The Github Repo https://github.com/oznu/docker-guacamole has been archived and should be replaced/removed.

**Comment by angrycuban13** [comment]
We have maintained archived repos such as Ouroboros. If it isn't broken I don't see the point on marking it as deprecated. 

If you have a fork that's being maintained that you'd like to see implemented please feel free to share it.

**Comment by nemchik** [comment]
I'm open to finding a replacement. The main reason we went with oznu over the official image is oznu's image was an all-in-one solution that was easier to get running for a beginner compared to the official image.

If anyone is aware of an alternative oznu seems to be looking to link to it, and we would consider switching.

Worst case, we may deprecate and remove it from DS.
