### ISSUE TITLE
GUI apps not being de-selected correctly

### ISSUE THREAD

**Issue by oranblackwell** [GhostWriters/DockSTARTer#128]
I'm using the GUI version on RPi3B+. When I go to Configure Apps I want to deselect an app I've already configured ie. uninstall it, but it doesnt seem to have any effect. At the end when it says do I want to launch the selected containers now, I was hopping that it would end any previous containers and only keep the selected ones. I've tried manually stopping and them removing all containers but rerunning the GUI keeps re-installing them.

**Comment by nemchik** [comment]
This is confirmed, and planned to be fixed after https://github.com/GhostWriters/DockSTARTer/pull/123 merges
