### ISSUE TITLE
TDARR v2 Environmental Variable Missing for GPU

### ISSUE THREAD

**Issue by rasorjb** [GhostWriters/DockSTARTer#1287]
# Bug report

**Describe the bug**
GPU Processing does not function as containers are configured directly from DockStarter compose.

**To Reproduce**
Install tdarr and tdarrnode from DockStarter via compose. Make no other changes and attempt to utilize NVIDIA gpu in TDARR. All Health Checks and Encodes will fail stating:

[AVHWDeviceContext @ 0x560f7feb44c0] Cannot load libcuda.so.1
[AVHWDeviceContext @ 0x560f7feb44c0] Could not dynamically load CUDA
Device creation failed: -1313558101.
[hevc @ 0x560f7feb26c0] No device available for decoder: device type cuda needed for codec hevc.
Device setup failed for decoder on input stream #0:0 : Unknown error occurred

**Expected behavior**
Health Checks and Encoding should function without further container modifications.

**System**
Mint 20

Docker 
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:32 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Additional context**
This error occurs due to the GPU not being made available to docker. An additional environmental variable should be added to both tdarr and tdarr node: "NVIDIA_VISIBLE_DEVICES=all"

Additionally, the runtime for both containers should be changed from "runc" to "nvidia" (I use the term runtime as that is what it is called in Portainer, I'm not sure what the docker terminology is).

For a bonus if you could have DockStarter install nvidia-docker2 (https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/overview.html) you would not have to set up anything to have NVIDIA GPU support in DS.

**Comment by angrycuban13** [comment]
I don't know if I will get to this anytime soon so please feel free to make a PR :)

**Comment by rasorjb** [comment]
> I don't know if I will get to this anytime soon so please feel free to make a PR :)

While I would love to provide more support, I am not that skilled. It took me forever to figure it out in Portainer and I have no clue how to properly implement it in a .yaml. Also, I think it would need some type of "app configuration" in the setup to identify CPU or GPU encoding, and if GPU what kind. Way out of my ballpark!

I do appreciate DockStarter to simplify it all for me!
