### ISSUE TITLE
What is "Full Setup?"

### ISSUE THREAD

**Issue by spencerthayer** [GhostWriters/DockSTARTer#1290]
I cannot find in the documentation what "full setup" actually is. This should exist somewhere right?

**Comment by angrycuban13** [comment]
Full setup goes through all the menu options in order

**Comment by nemchik** [comment]
This is correct. I could add descriptions to each of the menu options on this screen so it will be more clear, but Full Setup just goes in order through the other options. It is recommended to do this on your first run. On subsequent runs you may just want to add a new app, or change a global variable.

**Comment by angrycuban13** [comment]
#1292 addresses this
