### ISSUE TITLE
E: Sub-process / usr / bin / dpkg returned an error code (1)

### ISSUE THREAD

**Issue by kobruc** [GhostWriters/DockSTARTer#1293]
# Bug report
[FATAL ]   Failed to upgrade packages from apt. Failing command: eval apt-get -y dist-upgrade ""
**Describe the bug**
When installing Dockerstarter I always get this error:
E: Sub-process / usr / bin / dpkg returned an error code (1) [FATAL ]   Failed to upgrade packages from apt.

**To Reproduce**

- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
I trying to install DockStarter!
DockSTARTer did not finish running successfully.

**Screenshots**

**System**
(please complete the following information):

- OS: [e.g. Debian]

**Additional context**

**Comment by angrycuban13** [comment]
Make sure your apt sources are correct.

**Comment by nemchik** [comment]
This isn't a bug with DS.

Run
```shell
sudo apt update
sudo apt dist-upgrade
```
and you will see whatever relevant error message and you'll need to resolve that. We may be able to assist on our discord.

Closing the issue since it's not an actual bug in the code of DS and more of a support issue.
