### ISSUE TITLE
[Feature Request] app variable restart behavoir

### ISSUE THREAD

**Issue by Soppiej** [GhostWriters/DockSTARTer#1305]
# Feature request
It would be nice to be able to adjust the restart behavoir of a container, for each container.

**Is your feature request related to a problem? Please describe.**
Im currently using docker_compose_override.yml to solve the issue, i am however lazy by nature :)

**Describe the solution you'd like**
Add to app variables

**Describe alternatives you've considered**

**Comment by nemchik** [comment]
That's fair, and doable. I can try to do this maybe this weekend.

**Comment by nemchik** [comment]
Maybe sooner...

**Comment by nemchik** [comment]
Ok. This should now be doable for every app in DS with new vars. You can update DS with `ds -u` (i would recommend running that command twice) and then edit your `.env` to set the restart policy on any app.
