### ISSUE TITLE
[BUG] PHPMyAdmin not in App list for ARMv7 CPU

### ISSUE THREAD

**Issue by codeclinic** [GhostWriters/DockSTARTer#1307]
# Bug report

**Describe the bug**
If I run DockStarter on my old Seagate NAS system running pure Debian 10, I am not given the option to install PHPMyAdmin. The NAS uses a Marvell Armada 370 SoC which is ARMv7. According to the official PHPMyAdmin docker hub ARMv7 is supported: 

https://hub.docker.com/r/phpmyadmin/phpmyadmin/

**Expected behavior**
PHPMyAdmin should appear in the App menu of installable apps within Dockstarter.

**System**
(please complete the following information):

- OS: Debian - Fresh install bypassing the original system OS on the devices flash memory.
- Version: 10 Buster

**Comment by nemchik** [comment]
I don't see anywhere on that docker hub link indicating armv7 support with their docker image. They do have badges that indicate they do builds of phpmyadmin for armv7 (and others) but not that they support it with their docker image. You would want to look at the tags tab here https://hub.docker.com/r/phpmyadmin/phpmyadmin/tags and notice that only amd64 is listed on all of the tags for the image. https://hub.docker.com/r/linuxserver/mariadb/tags is an example where you can see tags that list support for multiple architectures.

This wouldn't be considered a bug with DS itself, but rather something that phpmyadmin would need to do (build arm tags for their image) before we could add it to DS.
