### ISSUE TITLE
[BUG] Failed to run yml merge script

### ISSUE THREAD

**Issue by codeclinic** [GhostWriters/DockSTARTer#1317]
# Bug report

**Describe the bug**
DockSTARTer fails to setup apps selected from menu

**To Reproduce**
Run "ds" and complete the full configuration. After setting the app configs ds fails with the following output:

2021-05-25 17:30:26 [NOTICE]   Preparing app menu. Please be patient, this can take a while.
2021-05-25 17:32:40 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
2021-05-25 17:32:55 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
2021-05-25 17:32:56 [NOTICE]   Adding compose configurations for enabled apps. Please be patient, this can take a while.
2021-05-25 17:33:00 [FATAL ]   Failed to run yml merge script.
Failing command: bash "/tmp/tmp.xxxxxxxxxx"
DockSTARTer did not finish running successfully.

**Expected behavior**
DockSTARTer completes installation and configuration of the selected apps

**System**
(please complete the following information):

- OS: Debian
- Version: 9 Stretch

**Additional context**
I was previously able to use DS on this same system prior to wiping the HDD and creating a fresh install of Debian.

**Comment by codeclinic** [comment]
> Can you locate the `/tmp/tmp.xxxxxxxxxx` file and post the contents here?
`#!/usr/bin/env bash
export YQ_OPTIONS=" -v /home/phill/.docker:/home/phill/.docker"
yq -y -s 'reduce .[] as $item ({}; . * $item) | del(.version)' \
"/home/phill/.docker/compose/.reqs/r1.yml" \
"/home/phill/.docker/compose/.reqs/r2.yml" \
"/home/phill/.docker/compose/.apps/watchtower/watchtower.armv7l.yml" \
"/home/phill/.docker/compose/.apps/watchtower/watchtower.hostname.yml" \
"/home/phill/.docker/compose/.apps/watchtower/watchtower.yml" \
> "/home/phill/.docker/compose/docker-compose.yml"
`

**Comment by codeclinic** [comment]
> ~/.docker/compose/.env
    
    # Global Settings
    COMPOSE_HTTP_TIMEOUT=60
    DOCKERCONFDIR=/home/phill/.config/appdata
    DOCKERGID=999
    DOCKERHOSTNAME=ccAdGuardHome
    DOCKERLOGGING_MAXFILE=10
    DOCKERLOGGING_MAXSIZE=200k
    DOCKERSTORAGEDIR=/home/phill/storage
    PGID=1000
    PUID=1000
    TZ=Europe/Berlin
    
    # VPN Settings
    LAN_NETWORK=192.168.2.0/24
    NS1=1.1.1.1
    NS2=8.8.8.8
    VPN_CLIENT=openvpn
    VPN_ENABLE=yes
    VPN_OPTIONS=
    VPN_OVPNDIR=/home/phill/.config/appdata/.openvpn
    VPN_PASS=
    VPN_PROV=custom
    VPN_USER=
    VPN_WGDIR=/home/phill/.config/appdata/.wireguard
    
    # END OF DEFAULT SETTINGS
    WATCHTOWER_CLEANUP=true
    WATCHTOWER_ENABLED=true
    WATCHTOWER_INCLUDE_STOPPED=false
    WATCHTOWER_MONITOR_ONLY=false
    WATCHTOWER_NETWORK_MODE=
    WATCHTOWER_NOTIFICATIONS_LEVEL=info
    WATCHTOWER_NOTIFICATIONS=shoutrrr
    WATCHTOWER_NOTIFICATION_TEMPLATE={{range .}}{{.Message}}{{println}}{{end}}
    WATCHTOWER_NOTIFICATION_URL=
    WATCHTOWER_REPO_PASS=
    WATCHTOWER_REPO_USER=
    WATCHTOWER_RESTART=unless-stopped
    WATCHTOWER_SCHEDULE=0 0 4 * * *
    WATCHTOWER_TIMEOUT=10s

**Comment by nemchik** [comment]
Can you run `yq --version`

**Comment by codeclinic** [comment]
> Can you run `yq --version`

yq 2.12.0

**Comment by codeclinic** [comment]
I've reinstalled DS and now I get the following output:

    2021-05-27 23:06:40 [WARN  ]   Wrong version of yq detected. https://github.com/kislyuk/yq will be installed.
    Untagged: ghcr.io/linuxserver/yq:latest
    Untagged: ghcr.io/linuxserver/yq@sha256:144d40fb2959d0635d32cbd4eea2ff1155c4fe2fa21d230b9400011ec0f8b778
    Deleted: sha256:d25c86f257525a270cd19cecdaed152b731666a86db0db0f44d182cb404a1731
    Deleted: sha256:dda21a05d26f9ecd5d3e58608c9d07073b387647e4268ee5f6b23e184adf531a
    Deleted: sha256:3f9e5b201763570633c3028f56c7bcf5205d17a8c4a112f3074fdc5097421a85
    Deleted: sha256:e2dcb12293e807efdfa278463b052ba5d015e085e6afb9074d46d576db6cffda
    Deleted: sha256:822ffae515113bdfe7c8321e644237c18bd93d0a64ec0b3a29eeed136b7b4c63
    Deleted: sha256:bf37e20caaf6c948c41a525349d1388b09818fc9d42217c694aa8f33711a06b5
    Deleted: sha256:9f91e6c7aca0f844f996b18752f87c73efcbc8e83e7513bdd3f7c8b3e4d250a5
    Deleted: sha256:5983181db79de2393a5238b8b271b536fe2e014a596d8bf61eca3293f16aefeb
    2021-05-27 23:07:59 [ERROR ]   Failed to install the latest yq.
    2021-05-27 23:07:59 [FATAL ]   Failed to install the minimum required yq.
    
    
If I install yq manually with `pip3 install yq` it say all the requirements are already satisfied. So I'm not sure why DS thinks it's not installed, tries to install it and then fails.

**Comment by codeclinic** [comment]
Even removing all traces of yq and then re-running the DockSTARTer installation script fails to install yq. 

I now even updated the system to Debian 10 stretch to see if that makes any difference. It doesn't.

Any ideas?

**Comment by nemchik** [comment]
This should be resolved in https://github.com/GhostWriters/DockSTARTer/pull/1318
