### ISSUE TITLE
[Feature Request] Native Docker-Compose file creation

### ISSUE THREAD

**Issue by BanditTech** [GhostWriters/DockSTARTer#1343]
# Feature request
It would be an amazing feature to include a flag such as --native which would compile a workable compose file with all components included, which can be run with the native docker-compose cli.

**Is your feature request related to a problem? Please describe.**
the output compose file is not openable within the cli of the console, and does not include the directives of the override file. It would be very helpful to essentially have the compile process occur, but then instead of running the merged compose, save it to `docker-compose.native.yml`

It would also help with pulling down the stack, since I typically make an alias for my compose 
```alias dcp="sudo docker-compose -f /path/to/.docker/compose/docker-compose.yml --project-directory /path/to/.docker/compose"```

**Describe the solution you'd like**
A single file I can run outside of DS with identical parameters

**Describe alternatives you've considered**
I fully understand I could figure the pieces together and make the file work if I wanted to manually do it each time. :)

**Comment by BanditTech** [comment]
I was informed my docker-compose is probably out of version, and indeed it is! 👍

**Comment by nemchik** [comment]
Aside from the version of compose, you shouldn't need to specify the file name of you're specifying the project directory. The override functionally is part of the compose application, not part of DockSTARTer. DS doesn't at any point merge the override file into the compose file (even at runtime), this is handled by compose itself reading both files. If you don't specify the file name, the override should be properly accounted for.

You can test this by doing:
```
cd /path/to/.docker/compose
# see the full merged file
docker-compose config
# bring up your stack, including the override file
docker-compose up -d
```

**Comment by BanditTech** [comment]
The issue I ran into, was that APT-GET is telling me I had the current version of docker-compose. But the latest version on APT is 4 subversions behind. So, I needed to run the install string they provide on docker-compose install instructions to reinstall it with the latest version. Hope this clears up any remaining confusion for anyone finding this.

[From the install page](https://docs.docker.com/compose/install/)
```
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

**Comment by CLHatch** [comment]
Yes, I helped him with this in Discord.  It wasn't really an issue with it's not reading the override file, it was that the version of Docker Compose was old enough that it required the "version:" line, so it never even got to reading the override file.
