### ISSUE TITLE
[Application Request] Time Machine

### ISSUE THREAD

**Issue by gvillo** [GhostWriters/DockSTARTer#1344]
# Name of the application
Time Machine

## GitHub
https://github.com/mbentley/docker-timemachine

## Docker Hub/GitHub Registry
https://hub.docker.com/r/mbentley/timemachine

### Additional context
It would be awesome to add time machine to the app list, to be able to backup Mac computers using Time Machine

**Comment by samAheenan** [comment]
Just adding another vote for time machine. It looks like there are a few candidate images that could be considered:

1. https://hub.docker.com/r/mbentley/timemachine
2. https://hub.docker.com/r/odarriba/timemachine (the most downloaded from Docker but it is three years old and its last commit in GitHub appears to have been over a year ago)
3. https://hub.docker.com/r/msjpq/time-machine/ (updated 30 minutes ago as of time of commenting)

I have no preference but would just like to see a Time Machine solution included. Hopefully other people would find it valuable too.

**Comment by angrycuban13** [comment]
We accept Pull Requests for any new apps, if you read over the contributing guide it should help you get started and we can always nitpick any mistakes in the PR.

**Comment by samAheenan** [comment]
Thanks for your response, @angrycuban13. 

I submitted a request to the maintainer of the first container in the list, @mbentley, ([here](https://github.com/mbentley/docker-timemachine/issues/118)) as my dev skills are minimal! Unfortunately, he does not think he will have time to maintain it.

**Comment by mbentley** [comment]
I changed my mind after looking at another PR; looked about as much work as maintaining an existing compose file, just exploded out so we'll see :)
