### ISSUE TITLE
[Application Request] Readarr

### ISSUE THREAD

**Issue by soile1991** [GhostWriters/DockSTARTer#1345]
# Name of the application
Readarr

## GitHub
https://github.com/Readarr/Readarr

## Docker Hub/GitHub Registry
https://hub.docker.com/r/hotio/readarr

**Comment by angrycuban13** [comment]
Readarr is not officially released and has too many bugs.

**Comment by bcsteeve** [comment]
I wonder if you would reconsider in 2023?  I realize it is still pre-release, but I find it works really very well.  No "bugs" that I've noticed, although there are some quirks to get used to, I think that's a result of how authors do what they do.

Just a thought.
