### ISSUE TITLE
[Application Request] Prowlarr

### ISSUE THREAD

**Issue by robgates** [GhostWriters/DockSTARTer#1346]
# Name of the application
Prowlarr
## GitHub
https://github.com/Prowlarr/Prowlarr/
### Additional context

Its early days for the Application but might be worth implementing on ds as its an automated indexer

**Comment by BanditTech** [comment]
Second this! From what I have heard its jackett and hydra combined with automatic integration with all the *arr services.

**Comment by Mchar7** [comment]
Should be safe to close now as my #1366 has been merged into master. I have Prowlarr running via DockSTARTer and it is working well.
