### ISSUE TITLE
BusyBox installation options, instructions where git cannot be installed

### ISSUE THREAD

**Issue by inspector71** [GhostWriters/DockSTARTer#1353]
On BusyBox systems, `git` may not be installable.

Understand using a git repo effectively provides a form of user self-updating (just `git pull`) and that may be ideal for the devs.

However, a `wget` 'release' URL would be helpful for those who cannot install git.

**Comment by inspector71** [comment]
OTOH, appears `main.sh` does not run on the current stable version of LibreELEC's BusyBox v1.31.0 :

```
./DockSTARTer-master/main.sh
./DockSTARTer-master/main.sh: set: line 2: illegal option -E
```

**Comment by nemchik** [comment]
This would require a much bigger overhaul than just `git`,. For example, we use options from GNU `grep` not found in the BusyBox version of `grep` currently.

It should be possible to find ways around this, but I can definitely say it's not high on the priority list at the moment.

**Comment by inspector71** [comment]
> 
> 
> This would require a much bigger overhaul than just `git`. For example, we use options from GNU `grep` not found in the BusyBox version of `grep` currently.
> 
> It should be possible to find ways around this, but I can definitely say it's not high on the priority list at the moment.

Fair enough, thanks for the feedback.
