### ISSUE TITLE
DockSTARTer not installing when system language is not english

### ISSUE THREAD

**Issue by milleraa** [GhostWriters/DockSTARTer#1357]
# Bug report

**Describe the bug**
DockSTARTer not installing on RPI4 Raspberry os lite

**To Reproduce**
```
pi@my-pi:~ $ sudo bash /home/"${USER}"/.docker/main.sh -vi
2021-07-25 18:07:52 [INFO  ]   Setting permissions for /home/pi/.docker/main.sh
2021-07-25 18:07:52 [INFO  ]   Taking ownership of /home/pi/.docker/main.sh for user 1000 and group 1000
2021-07-25 18:07:52 [INFO  ]   Setting file and folder permissions in /home/pi/.docker/main.sh
2021-07-25 18:07:52 [INFO  ]   Setting executable permission on /home/pi/.docker/main.sh
cat: /tmp/tmp.9mI9VURT4A: Нет такого файла или каталога
DockSTARTer did not finish running successfully.
cat: /tmp/tmp.9mI9VURT4A: Нет такого файла или каталога
DockSTARTer did not finish running successfully.
```
cat: /tmp/tmp.9mI9VURT4A: no such file or directory

**System**
- OS: raspberry os lite 
- fresh install 25.07.2021

**Additional context**
```
pi@my-pi:~ $ locale
LANG=ru_RU.UTF-8
LANGUAGE=
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```

```
cat /etc/debian_version
10.10
```

**Comment by milleraa** [comment]
may here is the issue https://github.com/GhostWriters/DockSTARTer/commit/9e095bfe0cd7d3250b67091edf6314607e305fb6

**Comment by milleraa** [comment]
i have found the issue. If system locale is not LANG=en_GB.UTF-8 the script can't parse version of libseccomp2 
https://github.com/GhostWriters/DockSTARTer/blob/75bbfa5c6cad0b365dd3be56f34d4716f63790b8/.scripts/pm_apt_repos.sh
` INSTALLED_LIBSECCOMP2=$(apt-cache policy libseccomp2 | grep -Po 'Installed: \K.*')`

**Comment by nemchik** [comment]
> i have found the issue. If system locale is not LANG=en_GB.UTF-8 the script can't parse version of libseccomp2
> https://github.com/GhostWriters/DockSTARTer/blob/75bbfa5c6cad0b365dd3be56f34d4716f63790b8/.scripts/pm_apt_repos.sh
> ` INSTALLED_LIBSECCOMP2=$(apt-cache policy libseccomp2 | grep -Po 'Installed: \K.*')`

Good find! I hadn't considered other locales! There may be other places in DS that could cause similar issues. I'll have a look around and see what I can do.

Thanks for reporting this!

**Comment by inject3d** [comment]
@nemchik: Did you already have the time to look into this?

**Comment by nemchik** [comment]
> @nemchik: Did you already have the time to look into this?

I can definitely see there are a few places in DS that will be affected. One solution may be too force the script to temporarily set the environment variable. This could force the menus to display only in English, but none of the user facing strings are setup for translation anyway, so it could work out fine. I'll try to put something together later today and reply here with testing information.

Thanks.

**Comment by nemchik** [comment]
To anyone having issues who has their system language set to anything other than English, can you please see if https://github.com/GhostWriters/DockSTARTer/pull/1361 fixes the issue?

Test `ds -u origin/lang`

**Comment by inject3d** [comment]
```~/.docker$ ./main.sh 
2021-08-08 16:00:36 [NOTICE]   DockSTARTer will not be updated to origin/master.
2021-08-08 16:00:58 [NOTICE]   Preparing app menu. Please be patient, this can take a while.
2021-08-08 16:01:46 [NOTICE]   /home/dietpi/.docker/compose/.env does not contain any disabled apps.
2021-08-08 16:01:48 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
2021-08-08 16:02:02 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
2021-08-08 16:02:03 [NOTICE]   Adding compose configurations for enabled apps. Please be patient, this can take a while.
latest: Pulling from linuxserver/yq
Digest: sha256:9b122a36d2ddf0c071ed6b38a9ac0ecc90767f077546d71361849b9e95124aaa
Status: Image is up to date for ghcr.io/linuxserver/yq:latest
ghcr.io/linuxserver/yq:latest
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6f11390 (most recent call first):
<no Python frame>
2021-08-08 16:02:06 [FATAL ]   Failed to run yq script.
DockSTARTer did not finish running successfully.```

**Comment by nemchik** [comment]
> ```
> 2021-08-08 16:00:36 [NOTICE]   DockSTARTer will not be updated to origin/master.
> 2021-08-08 16:00:58 [NOTICE]   Preparing app menu. Please be patient, this can take a while.
> 2021-08-08 16:01:46 [NOTICE]   /home/dietpi/.docker/compose/.env does not contain any disabled apps.
> 2021-08-08 16:01:48 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
> 2021-08-08 16:02:02 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
> 2021-08-08 16:02:03 [NOTICE]   Adding compose configurations for enabled apps. Please be patient, this can take a while.
> latest: Pulling from linuxserver/yq
> Digest: sha256:9b122a36d2ddf0c071ed6b38a9ac0ecc90767f077546d71361849b9e95124aaa
> Status: Image is up to date for ghcr.io/linuxserver/yq:latest
> ghcr.io/linuxserver/yq:latest
> Fatal Python error: pyinit_main: can't initialize time
> Python runtime state: core initialized
> PermissionError: [Errno 1] Operation not permitted
> 
> Current thread 0xb6f11390 (most recent call first):
> <no Python frame>
> 2021-08-08 16:02:06 [FATAL ]   Failed to run yq script.
> DockSTARTer did not finish running successfully.```
> ```

This looks like a different issue entirely. Can you reboot and then run
```
ds -p
```
And then try again?

**Comment by inject3d** [comment]
Unfortunately this does not help. Pulled latest changes of lang. Then rebooted.

~$ ds -p
Total reclaimed space: 0B
~$ ds -vif
2021-08-16 07:56:42 [INFO  ]   Setting permissions for /home/dietpi/.docker/main.sh
2021-08-16 07:56:42 [INFO  ]   Taking ownership of /home/dietpi/.docker/main.sh for user 1000 and group 1000
2021-08-16 07:56:42 [INFO  ]   Setting file and folder permissions in /home/dietpi/.docker/main.sh
2021-08-16 07:56:42 [INFO  ]   Setting executable permission on /home/dietpi/.docker/main.sh
cat: /tmp/tmp.gkRf9FYihW: Datei oder Verzeichnis nicht gefunden
DockSTARTer did not finish running successfully.
cat: /tmp/tmp.gkRf9FYihW: Datei oder Verzeichnis nicht gefunden
DockSTARTer did not finish running successfully.

**Comment by inject3d** [comment]
Seems to be the same problem, what do you think?

**Comment by nemchik** [comment]
Sorry for not getting back to you sooner on this. I've made another attempt in the lang branch. Please try:

```shell
ds -u origin/lang
ds -fiv
```

**Comment by inject3d** [comment]
Fix works for me, so the PR could be merged. Thanks for your help.
