### ISSUE TITLE
Glances container fails to start

### ISSUE THREAD

**Issue by MorganTiley** [GhostWriters/DockSTARTer#1364]
# Bug report

**Describe the bug**
Glances container no longer works

**To Reproduce**
- Install glances container. 
- Attempt to browse Glances webpage in container - no response.
- See error in logs "/usr/local/bin/python3: No module named glances.__main__; 'glances' is a package and cannot be directly executed"

**Expected behavior**
Glances web page responds and displays properly

**System**
(please complete the following information):

- OS: Ubuntu 
- Version 20.04

**Additional context**
- I completely removed glances container, updated dockstarter and ran prune command, then reinstalled Glances and still got same error

**Comment by HalianElf** [comment]
Dockstarter just builds the compose, they will need to fix their container. For now you can use an override and roll back to the previous version. They already have an issue relating to this: nicolargo/glances#1905 Feel free to keep an eye on that issue for when their container is fixed.

**Comment by MorganTiley** [comment]
thanks!
