### ISSUE TITLE
[BUG] docker: invalid reference format: repository name must be lowercase.

### ISSUE THREAD

**Issue by karl0ss** [GhostWriters/DockSTARTer#1412]
# Bug report

**Describe the bug**
Not made any changes to any of my images/containers, but periodcly run a sudo ds -c, having run that this morning, it wont work.. and am now getting -

```
2022-01-04 10:35:39 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
2022-01-04 10:35:40 [NOTICE]   Adding compose configurations for enabled apps. Please be patient, this can take a while.
latest: Pulling from linuxserver/yq
Digest: sha256:e6eb08fb08ac40716ebf25b299ad08f9fe15ec6c704bada0ac95138931d55ed7
Status: Image is up to date for lscr.io/linuxserver/yq:latest
lscr.io/linuxserver/yq:latest
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
2022-01-04 10:35:42 [FATAL ]   Failed to run yq script.
Failing command: sh "/tmp/tmp.21utUuHzJa" " -y -s 'reduce .[] as $item ({}; . * $item) | del(.version)' /tmp/tmp.SHHPeVLgj3/*.yml > /home/ubuntu/.docker/compose/docker-compose.yml"
DockSTARTer did not finish running successfully.
```

I then have a blank docker-compose file and a corrupted docker-compose file called `docker-compose.yml(B[m` both are 0kb

**To Reproduce**

run `sudo ds - c`

**Expected behavior**
Images should update and rebuild

**System**
(please complete the following information):

- Distributor ID: Ubuntu
- Description:    Ubuntu 20.04.3 LTS
- Release:        20.04
- Codename:       focal

**Additional context**

**Comment by nemchik** [comment]
Thanks for reporting this. I've been seeing a lot of issues with yq lately and i'm (slowly) working on a way to skip using yq entirely. Until then, could you try:
```shell
ds -p
ds -u
ds -fiv
ds -c
```
That's kind of throwing everything at it all at once, but hopefully get's you working.

**Comment by karl0ss** [comment]
Thanks for your response, doing these steps has "fixed" my issue...

Still loving this tool after all these years...

**Comment by nemchik** [comment]
This should be resolved now that we've merged the compose v2 changes. We no longer use yq.
