### ISSUE TITLE
[BUG] Bitwarden Container does not start

### ISSUE THREAD

**Issue by inject3d** [GhostWriters/DockSTARTer#1440]
I started up the bitwarden container, but it fails and repeats in a boot loop with the following message:
```today at 1:30:48 PM/--------------------------------------------------------------------\
today at 1:30:48 PM|                        Starting Vaultwarden                        |
today at 1:30:48 PM|                           Version 1.24.0                           |
today at 1:30:48 PM|--------------------------------------------------------------------|
today at 1:30:48 PM| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
today at 1:30:48 PM| official channels to report bugs/features, regardless of client.   |
today at 1:30:48 PM| Send usage/configuration questions or feature requests to:         |
today at 1:30:48 PM|   https://vaultwarden.discourse.group/                             |
today at 1:30:48 PM| Report suspected bugs/issues in the software itself at:            |
today at 1:30:48 PM|   https://github.com/dani-garcia/vaultwarden/issues/new            |
today at 1:30:48 PM\--------------------------------------------------------------------/
today at 1:30:48 PM
today at 1:30:48 PM[INFO] No .env file found.
today at 1:30:48 PM
today at 1:30:48 PMError validating domain: relative URL without a base
today at 1:30:48 PMError loading config:
today at 1:30:48 PM	DOMAIN variable needs to contain the protocol (http, https). Use 'http[s]://bw.example.com' instead of 'bw.example.com'
today at 1:30:48 PM
today at 1:30:47 PMContainer stopped
```
Did I miss anything except the ssl handling? I would expect that a base setup would run. Also I could not find anything in the documentation: https://dockstarter.com/apps/bitwarden/

**Comment by nemchik** [comment]
In your `~/.docker/compose/.env` file you need to set `BITWARDEN_DOMAIN=https://bw.example.com` (but set it to your domain)

You probably need to have a reverse proxy setup for it ahead of time (ex: swag, which has a premade proxy sample that should work).

**Comment by nemchik** [comment]
In SWAG configs when you rename the bitwarden proxy sample you should NOT need to change anything inside the file. nginx in SWAG uses the internal docker network to communicate between containers, so the following is designed to work out of the box:
```nginx
        set $upstream_app bitwarden;
        set $upstream_port 80;
```
DS names the bitwarden container `bitwarden` and the docker network allows nginx in SWAG to communicate to the hostname `bitwarden`
Inside the container bitwarden runs on port 80 . You can map that port to something else using DS .env variables, and this might expose port 8081 or whatever you pick to your local network, but bitwarden is still running on 80 inside the container, so nginx in SWAG needs to use port 80 (not your custom port).

So really you just rename the file and don't modify it and restart SWAG and it should work out of the box.
