### ISSUE TITLE
[Application Request] Deprecate Airsonic in favour of Airsonic-advanced

### ISSUE THREAD

**Issue by SevereOverfl0w** [GhostWriters/DockSTARTer#1448]
# Name of the application

airsonic-advanced

## GitHub

https://github.com/airsonic-advanced/airsonic-advanced

## Docker Hub/GitHub Registry

https://github.com/linuxserver/docker-airsonic-advanced

### Additional context

From [linuxserver/airsonic](https://hub.docker.com/r/linuxserver/airsonic):

> This image is deprecated. We will not offer support for this image and it will not be updated. We recommend our airsonic-advanced image instead: https://github.com/linuxserver/docker-airsonic-advanced

**Comment by nemchik** [comment]
This does need to happen. I haven't had time. Could be as simple as switching the image in the compose, but we need to make sure it's compatible with the existing vars/ports/volumes (etc) or if we need new compose.
