### ISSUE TITLE
[BUG] DockSTARTer fails to perfrom first run install successfully.

### ISSUE THREAD

**Issue by agom08** [GhostWriters/DockSTARTer#1454]
# Bug report

**Describe the bug**
DockSTARTer fails to finish running successfully.

**To Reproduce**
bash -c "$(curl -fsSL https://get.dockstarter.com)"

**Expected behavior**
To perform first run install with a successful completion.

**System**
(please complete the following information):

- OS: Linux Mint Cinnamon
- Version: 21.04

**Additional context**
Output is as follows:
2022-04-03 19:01:38 [WARN  ]   Attempting to clone DockSTARTer repo to /home/agom08/.docker location.
Cloning into '/home/agom08/.docker'...
remote: Enumerating objects: 20824, done.
remote: Counting objects: 100% (1953/1953), done.
remote: Compressing objects: 100% (274/274), done.
remote: Total 20824 (delta 1631), reused 1733 (delta 1512), pack-reused 18871
Receiving objects: 100% (20824/20824), 4.32 MiB | 23.15 MiB/s, done.
Resolving deltas: 100% (13947/13947), done.
2022-04-03 19:01:39 [NOTICE]   Performing first run install.
[sudo] password for agom08:        
2022-04-03 19:01:53 [INFO  ]   Setting permissions for /home/agom08/.docker/main.sh
2022-04-03 19:01:53 [INFO  ]   Taking ownership of /home/agom08/.docker/main.sh for user 1000 and group 1000
2022-04-03 19:01:53 [INFO  ]   Setting file and folder permissions in /home/agom08/.docker/main.sh
2022-04-03 19:01:53 [INFO  ]   Setting executable permission on /home/agom08/.docker/main.sh
2022-04-03 19:01:53 [INFO  ]   Creating /usr/bin/ds symbolic link for DockSTARTer.
2022-04-03 19:01:53 [INFO  ]   Creating /usr/local/bin/ds symbolic link for DockSTARTer.
2022-04-03 19:01:53 [INFO  ]   Updating repositories.
2022-04-03 19:01:55 [NOTICE]   Upgrading packages. Please be patient, this can take a while.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2022-04-03 19:01:55 [NOTICE]   Installing dependencies. Please be patient, this can take a while.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
grep is already the newest version (3.4-1).
sed is already the newest version (4.7-1).
whiptail is already the newest version (0.52.21-4ubuntu2).
curl is already the newest version (7.68.0-1ubuntu2.7).
git is already the newest version (1:2.25.1-1ubuntu3.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2022-04-03 19:01:56 [INFO  ]   Removing unused packages.
2022-04-03 19:01:56 [INFO  ]   Cleaning up package cache.
cat: /tmp/tmp.UHdmB49Dp3: No such file or directory
DockSTARTer did not finish running successfully.
cat: /tmp/tmp.UHdmB49Dp3: No such file or directory
DockSTARTer did not finish running successfully.

I am unable to locate the tmp file to post its contents.

**Comment by agom08** [comment]
I completed a reboot and ran DockSTARTer with the following issue:

$ ds
[sudo] password for agom08:        
2022-04-03 19:27:12 [NOTICE]   Preparing app menu. Please be patient, this can take a while.
2022-04-03 19:27:34 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
2022-04-03 19:28:45 [WARN  ]   Setting permissions for /mnt/Plex outside of /home/agom08 may be unsafe.
2022-04-03 19:28:59 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
2022-04-03 19:29:00 [NOTICE]   Adding compose configurations for enabled apps. Please be patient, this can take a while.
/home/agom08/.docker/.scripts/yml_merge.sh: line 63: docker: command not found
2022-04-03 19:29:00 [FATAL ]   Failed to output compose config.
Failing command: docker compose --project-directory /home/agom08/.docker/compose/ config > "/home/agom08/.docker/compose/docker-compose.yml"
DockSTARTer did not finish running successfully.

**Comment by agom08** [comment]
I accidentally closed this issue.

**Comment by nemchik** [comment]
Try running

```shell
ds -u
ds -fiv
ds -c
```

**Comment by agom08** [comment]
I was able to complete the setup and have DockSTARTer up and running. Thank you!

**Comment by nemchik** [comment]
That's great! I'll close this issue for now, but if you have any other problems feel free to open a new issue.

**Comment by PavanVasishta** [comment]
Hi can you reopen this? I'm facing the same issue and running 

```
ds -u
ds -fiv
ds -c
```
does not seem to solve the issue. I end up getting the same error as here. Thanks.

**Comment by JackDeSomeTrades** [comment]
Hi can you reopen this? I'm facing the same issue and running

```
ds -u
ds -fiv
ds -c

```
does not seem to solve the issue. I end up getting the same error as https://github.com/GhostWriters/DockSTARTer/issues/1454#issuecomment-1086973933 . Thanks.

**Comment by nemchik** [comment]
> Hi can you reopen this? I'm facing the same issue and running
> 
> ```
> ds -u
> ds -fiv
> ds -c
> ```
> 
> does not seem to solve the issue. I end up getting the same error as [#1454 (comment)](https://github.com/GhostWriters/DockSTARTer/issues/1454#issuecomment-1086973933) . Thanks.

Can you post the log of the output here?

**Comment by JackDeSomeTrades** [comment]
Hi, I managed to find out what the issue was. I was installing this with OpenMediaVault(OMV) after having installed Docker via their GUI. 
DockSTARTer does not check if there's an existing installation of Docker and tries to reinstall it. 

My solution is to wait until the installation script fails for the first time, comment out the OMV sources in `/etc/apt/sources.list.d/` and run the three above commands. 

I guess this is more of an interplay issue between OMV and DockSTARTer than a bug. If there is a bug, it's that the install script does not check for existing docker installs. 

Thanks.

**Comment by nemchik** [comment]
> If there is a bug, it's that the install script does not check for existing docker installs.

Actually if you run the install script with `ds -i` (or `ds -iv` for verbose output) it does in fact check for an existing installation of any dependency. When you run `ds -fi` (or `ds -fiv` for verbose output) it forces the installation of dependencies and opts in to prompts like whether certain command output should be shown. Often times forcing the installation of dependencies fixes the issues, but in the case of OMV it might be the opposite.

The first time install script does not run with the force flag, but I believe there is another issue with the first install parts of the script that I have yet to look into.

**Comment by chulojay** [comment]
This fails for me in Debian 12 lxc with sudor jay added 

jay@dockstarter-vm:~$ bash -c "$(curl -fsSL https://get.dockstarter.com)"
2024-02-22 18:05:26 [WARN  ]   Attempting to clone DockSTARTer repo to /home/jay/.docker location.
fatal: destination path '/home/jay/.docker' already exists and is not an empty directory.
2024-02-22 18:05:26 [FATAL ]   Failed to clone DockSTARTer repo.
Failing command: git clone https://github.com/GhostWriters/DockSTARTer "/home/jay/.docker"
DockSTARTer did not finish running successfully.

**Comment by nemchik** [comment]
> This fails for me in Debian 12 lxc with sudor jay added
> 
> jay@dockstarter-vm:~$ bash -c "$(curl -fsSL https://get.dockstarter.com)" 2024-02-22 18:05:26 [WARN ] Attempting to clone DockSTARTer repo to /home/jay/.docker location. fatal: destination path '/home/jay/.docker' already exists and is not an empty directory. 2024-02-22 18:05:26 [FATAL ] Failed to clone DockSTARTer repo. Failing command: git clone https://github.com/GhostWriters/DockSTARTer "/home/jay/.docker" DockSTARTer did not finish running successfully.

Try

```shell
git clone https://github.com/GhostWriters/DockSTARTer "/home/${USER}/.ds"
bash /home/"${USER}"/.ds/main.sh -vi
sudo reboot
```

I am actually considering making a similar change as a long term/permanent change to DS.
