### ISSUE TITLE
Docker-compose commands missing hyphen

### ISSUE THREAD

**Issue by samjaninf** [GhostWriters/DockSTARTer#1455]
Just recently updated the script and suddenly recieveing this error:

```
2022-04-06 01:42:14 [INFO  ]   Running compose config to create docker-compose.yml file from enabled templates.
unknown flag: --project-directory
See 'docker --help'.
```

When I grep for "project-directory" in the .docker folder I get these responses:
```
.docker/.scripts/yml_merge.sh:63:    eval "docker compose --project-directory ${SCRIPTPATH}/compose/ config > ${SCRIPTPATH}/compose/docker-compose.yml" || fatal "Failed to output compose config.\nFailing command: ${F[C]}docker compose --project-directory ${SCRIPTPATH}/compose/ config > \"${SCRIPTPATH}/compose/docker-compose.yml\""
.docker/.scripts/yml_merge.sh:71:    eval "docker compose --project-directory ${SCRIPTPATH}/compose/ config" || fatal "Failed to display compose config.\nFailing command: ${F[C]}docker compose --project-directory ${SCRIPTPATH}/compose/ config"
.docker/.scripts/docker_compose.sh:43:    eval "docker compose --project-directory ${SCRIPTPATH}/compose/ ${COMPOSECOMMAND}" || fatal "Failed to run compose.\nFailing command: ${F[C]}docker compose --project-directory ${SCRIPTPATH}/compose/ ${COMPOSECOMMAND}"
.docker/.scripts/docker_compose.sh:50:    eval "docker compose --project-directory ${SCRIPTPATH}/compose/ config" || fatal "Failed to display compose config.\nFailing command: ${F[C]}docker compose --project-directory ${SCRIPTPATH}/compose/ config"
```

Should the docker compose command not have a hyphen? docker-compose? e.g. `eval "docker-compose --project-directory ${SCRIPTPATH}/compose/ config" `

**Comment by samjaninf** [comment]
Hmmm, Changing it to docker-compose gives a different error about docker-compose being unable to cd.
```
/usr/local/bin/docker-compose: 41: cd: can't cd to /home/<username>/.docker/compose/.reqs/r1.yml:/home/<username>/.docker/compose/.reqs/r2.yml:
```

Lists all of the other yml files as well.

**Comment by CLHatch** [comment]
> Just recently updated the script and suddenly recieveing this error:
> 
> ```
> 2022-04-06 01:42:14 [INFO  ]   Running compose config to create docker-compose.yml file from enabled templates.
> unknown flag: --project-directory
> See 'docker --help'.
> ```
> 
> When I grep for "project-directory" in the .docker folder I get these responses:
> 
> ```
> .docker/.scripts/yml_merge.sh:63:    eval "docker compose --project-directory ${SCRIPTPATH}/compose/ config > ${SCRIPTPATH}/compose/docker-compose.yml" || fatal "Failed to output compose config.\nFailing command: ${F[C]}docker compose --project-directory ${SCRIPTPATH}/compose/ config > \"${SCRIPTPATH}/compose/docker-compose.yml\""
> .docker/.scripts/yml_merge.sh:71:    eval "docker compose --project-directory ${SCRIPTPATH}/compose/ config" || fatal "Failed to display compose config.\nFailing command: ${F[C]}docker compose --project-directory ${SCRIPTPATH}/compose/ config"
> .docker/.scripts/docker_compose.sh:43:    eval "docker compose --project-directory ${SCRIPTPATH}/compose/ ${COMPOSECOMMAND}" || fatal "Failed to run compose.\nFailing command: ${F[C]}docker compose --project-directory ${SCRIPTPATH}/compose/ ${COMPOSECOMMAND}"
> .docker/.scripts/docker_compose.sh:50:    eval "docker compose --project-directory ${SCRIPTPATH}/compose/ config" || fatal "Failed to display compose config.\nFailing command: ${F[C]}docker compose --project-directory ${SCRIPTPATH}/compose/ config"
> ```
> 
> Should the docker compose command not have a hyphen? docker-compose? e.g. `eval "docker-compose --project-directory ${SCRIPTPATH}/compose/ config" `


Define "updated the script".  I'm guessing you just did a 

`ds -u`

There was a recently a major update (announced in the DockSTARTer Discord server "Announcements" section), to where we are now using Docker Compose v2.  It now also does not use `yq`.  This uses the `docker compose` command instead of `docker-compose`.  But this update also requires a full update (a reinstall after updating), which is done with

```
ds -u
ds -fiv
```

This is the update that was recently merged: https://github.com/GhostWriters/DockSTARTer/pull/1444

**Comment by nsyvr** [comment]
`ds -u
ds -fiv`
fixed it. thanks..
