### ISSUE TITLE
command to composer throws error, nothing builds

### ISSUE THREAD

**Issue by meisam91** [GhostWriters/DockSTARTer#1456]
```
unknown flag: --project-directory
...
...
...
[FATAL ]   Failed to output compose config.
Failing command: docker compose --project-directory /home/**redacted**/.docker/compose/ config > "/home/**redacted**/.docker/compose/docker-compose.yml"```

**Comment by calinorg** [comment]
Just came here to write the same about this issue, and you beat me to it. 

Did the update dockstarter thingy before trying, and it just messes up docker-compose.yml
Luckily had timeshift backup, but something is messed up.

**Comment by nemchik** [comment]
Run
```
ds -u
ds -fiv
```

Then try what you were doing before.

**Comment by meisam91** [comment]
That did the trick! had no idea, we had those flags available :)

**Comment by fethomm** [comment]
Still happens here. 
Failing command: docker compose --project-directory /home/ft./docker/compose/ config > "/home/ft/.docker/compose/docker-compose.yml"
If In cd to /home/ft/.docker/compose/, there is a docker-compose.yml, but it is empty. Any help appreciated.

**Comment by nemchik** [comment]
> Still happens here. Failing command: docker compose --project-directory /home/ft./docker/compose/ config > "/home/ft/.docker/compose/docker-compose.yml" If In cd to /home/ft/.docker/compose/, there is a docker-compose.yml, but it is empty. Any help appreciated.

Can you run `docker compose version` and open a new issue (link to this one) and post your command output?

**Comment by fethomm** [comment]
I moved on. Issue can be closed.
