### ISSUE TITLE
Booksonic http error

### ISSUE THREAD

**Issue by PrzemekSkw** [GhostWriters/DockSTARTer#1462]
- OS: Dietpi [Debian 11], miniPC x64

Fresh install on last DS.
![IMG_20220416_151347](https://user-images.githubusercontent.com/25219988/163690400-aa1663c8-33c6-4610-9d5c-2e0f2dc1915c.jpg)

Container is running OK.
Log: 
https://www.toptal.com/developers/hastebin/ibuxexeyaz.typescript

Regards.

**Comment by nemchik** [comment]
Try
http://192.168.0.19:4040/booksonic

**Comment by PrzemekSkw** [comment]
I install Audioserve.
Regards.
