### ISSUE TITLE
[BUG]curl: (22) The requested URL returned error 503

### ISSUE THREAD

**Issue by varunpan** [GhostWriters/DockSTARTer#1485]
Trying to install dockStarter and receiving an error when running:
bash -c "$(curl -fsSL https://get.dockstarter.com)"

curl: (22) The requested URL returned error: 503

- OS: ubuntu 
- Version 22.04

**Comment by HalianElf** [comment]
You're being blocked by Cloudflare. Try using the url that redirects to (https://raw.githubusercontent.com/GhostWriters/DockSTARTer/master/main.sh) or download that manually and run it.

**Comment by varunpan** [comment]
That worked, Thank you :)
