### ISSUE TITLE
[Application Request] Synapse (Matrix Server)

### ISSUE THREAD

**Issue by kdaniel2410** [GhostWriters/DockSTARTer#1507]
# Name of the application
Matrix Synapse

## GitHub
https://github.com/matrix-org/synapse

## Docker Hub/GitHub Registry
https://hub.docker.com/r/matrixdotorg/synapse/

### Additional context
Synapse: Matrix homeserver written in Python 3/Twisted. Matrix is an open network for secure, decentralized communication

**Comment by angrycuban13** [comment]
Closing as per #1508
