### ISSUE TITLE
[BUG] Failing to run Compose

### ISSUE THREAD

**Issue by rasorjb** [GhostWriters/DockSTARTer#1513]
# Bug report

**Describe the bug**
I am attempting to add a new application to my DockStarter configuration. Once I select the app and press enter the below happens:

`2022-08-11 15:58:00 [NOTICE]   Preparing app menu. Please be patient, this can take a while.
2022-08-11 15:58:04 [NOTICE]   /home/josh/.docker/compose/.env does not contain any disabled apps.
2022-08-11 15:58:09 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
2022-08-11 15:58:10 [NOTICE]   Adding compose configurations for enabled apps. Please be patient, this can take a while.
unknown flag: --project-directory
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default
                           "/root/.docker")
  -c, --context string     Name of the context to use to connect to the
                           daemon (overrides DOCKER_HOST env var and
                           default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level
                           ("debug"|"info"|"warn"|"error"|"fatal")
                           (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default
                           "/root/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default
                           "/root/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default
                           "/root/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  app*        Docker App (Docker Inc., v0.9.1-beta3)
  builder     Manage builds
  buildx*     Docker Buildx (Docker Inc., v0.8.2-docker)
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  scan*       Docker Scan (Docker Inc., v0.17.0)
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go/guides/

2022-08-11 15:58:10 [FATAL ]   Failed to output compose config.
Failing command: docker compose --project-directory /home/josh/.docker/compose/ config > "/home/josh/.docker/compose/docker-compose.yml"
DockSTARTer did not finish running successfully.
`

**To Reproduce**

1. sudo ds
2. Configuration
3. Select Apps4. 
4. Select 1 or more new apps.
5. OK
6. See above error. 

3. **Expected behavior**
Compose to complete successfully and container be added to docker.

**Screenshots**
n/a

**System**
(please complete the following information):

- OS: Linux Mint
- Version 21

**Additional context**
I did just update to Mint 21, however, I cannot guarantee this problem did or did not exist prior to the upgrade. I haven't added an app to my configuration in quite some time.

**Comment by nemchik** [comment]
try
```
ds -u
ds -fiv
# during the -fiv there will be some text on screen about pressing Ctrl+C to cancel, DON'T DO IT, let it finish
ds -c
```

**Comment by rasorjb** [comment]
> try
> 
> ```
> ds -u
> ds -fiv
> # during the -fiv there will be some text on screen about pressing Ctrl+C to cancel, DON'T DO IT, let it finish
> ds -c
> ```

:~$ sudo ds -u
[sudo] password for josh:               
2022-08-11 20:11:35 [NOTICE]   Updating DockSTARTer to origin/master.
2022-08-11 20:11:39 [NOTICE]   Creating environment variables for enabled apps. Please be patient, this can take a while.
:~$ ds -fiv
2022-08-11 20:11:57 [INFO  ]   Setting permissions for /home/josh/.docker/main.sh
2022-08-11 20:11:57 [INFO  ]   Taking ownership of /home/josh/.docker/main.sh for user 1000 and group 1000
2022-08-11 20:11:57 [INFO  ]   Setting file and folder permissions in /home/josh/.docker/main.sh
2022-08-11 20:11:57 [INFO  ]   Setting executable permission on /home/josh/.docker/main.sh
2022-08-11 20:11:57 [NOTICE]   Updating repositories. Please be patient, this can take a while.
2022-08-11 20:11:57 [INFO  ]   Updating repositories.
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Ign:2 http://packages.linuxmint.com vanessa InRelease                          
Hit:3 https://download.docker.com/linux/ubuntu jammy InRelease                 
Hit:4 http://packages.linuxmint.com vanessa Release                            
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease                         
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]        
Get:7 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]      
Hit:8 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu jammy InRelease     
Get:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]    
Hit:11 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease 
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 DEP-11 Metadata [91.4 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 DEP-11 Metadata [127 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 DEP-11 Metadata [940 B]
Get:15 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 DEP-11 Metadata [12.5 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/main amd64 DEP-11 Metadata [11.4 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 DEP-11 Metadata [10.1 kB]
Fetched 578 kB in 1s (511 kB/s)             
Reading package lists... Done
W: http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
2022-08-11 20:12:01 [NOTICE]   Upgrading packages. Please be patient, this can take a while.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  python3-imdbpy
Use 'sudo apt autoremove' to remove it.
The following packages have been kept back:
  apt apt-utils cryptsetup cryptsetup-bin cryptsetup-initramfs libapt-pkg6.0
  libcryptsetup12
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
2022-08-11 20:12:02 [NOTICE]   Installing dependencies. Please be patient, this can take a while.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
grep is already the newest version (3.7-1build1).
sed is already the newest version (4.8-1ubuntu2).
whiptail is already the newest version (0.52.21-5ubuntu2).
curl is already the newest version (7.81.0-1ubuntu1.3).
git is already the newest version (1:2.34.1-1ubuntu1.4).
The following package was automatically installed and is no longer required:
  python3-imdbpy
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
2022-08-11 20:12:02 [INFO  ]   Removing unused packages.
2022-08-11 20:12:03 [INFO  ]   Cleaning up package cache.
2022-08-11 20:12:04 [INFO  ]   Removing conflicting Docker packages.
2022-08-11 20:12:05 [NOTICE]   Installing docker. Please be patient, this can take a while.
2022-08-11 20:12:05 [INFO  ]   Downloading docker install script.
2022-08-11 20:12:05 [INFO  ]   Running docker install script.
# Executing docker install script, commit: b2e29ef7a9a89840d2333637f7d1900a83e7153f
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20
+ sh -c apt-get update -qq >/dev/null
W: http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c mkdir -p /etc/apt/keyrings && chmod -R 0755 /etc/apt/keyrings
+ sh -c curl -fsSL "https://download.docker.com/linux/debian/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
+ sh -c chmod a+r /etc/apt/keyrings/docker.gpg
+ sh -c echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
E: The repository 'https://download.docker.com/linux/debian bookworm Release' does not have a Release file.
W: http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
2022-08-11 20:12:29 [FATAL ]   Failed to install docker.
Failing command: sh /tmp/tmp.XEOdBb521Y
DockSTARTer did not finish running successfully.

**Comment by nemchik** [comment]
```
E: The repository 'https://download.docker.com/linux/debian bookworm Release' does not have a Release file.
```
This line (near the very end of your output) is probably the issue. This isn't something DS causes. You would need to resolve this and run
```
sudo apt update
sudo apt upgrade
```
without receiving any errors before DS can succeed.

**Comment by rasorjb** [comment]
Ok, so I disabled both of the repos with Key errors (even though I don't think they are relevant). I changed the software source for docker from "https://download.docker.com/linux/debian bookworm Release" to "https://download.docker.com/linux/ubuntu jammy Release". When I run "ds -fiv" the script changes it back to Debian bookworm which doesn't have a release file.

**Comment by nemchik** [comment]
> Ok, so I disabled both of the repos with Key errors (even though I don't think they are relevant). I changed the software source for docker from "https://download.docker.com/linux/debian bookworm Release" to "https://download.docker.com/linux/ubuntu jammy Release". When I run "ds -fiv" the script changes it back to Debian bookworm which doesn't have a release file.
> 
> Edit: I've also run
> 
> `apt-get install docker` with the jammy repo and it is installed. DS still fails.
> 
> Edit 2: I just noticed in the initial error `unknown flag: --project-directory` is present near the top.

Try removing it again, then run
```
sudo apt update
sudo apt upgrade
```
and if those are successful run
```
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
```

I am wondering if the issue is coming from the docker install script.

The only other place it might be coming from is https://github.com/GhostWriters/DockSTARTer/blob/master/.scripts/pm_apt_repos.sh but DS only does the repo related stuff if your `libseccomp2` is outdated (you can check by running `apt-cache policy libseccomp2 | grep --color=never -Po 'Installed: \K.*'` and looking for version `2.4.4` or greater)

**Comment by rasorjb** [comment]
Ran:

<code> sudo apt remove docker</code> Successful
<code>sudo apt update</code> Successful
<code>sudo apt upgrade</code> Successful
<code>curl -fsSL https://get.docker.com -o get-docker.sh</code> Successful
<code>sudo sh get-docker.sh</code> It notifies me that docker command is present. When it runs, it still flags the bookworm error above.

<code>libseccomp2</code> is 2.5.3-2ubuntu2

**Comment by rasorjb** [comment]
Ok I think I can confirm the issue is isolated to Mint 21. Due to some unrelated networking issues, I reverted back to a TimeShift 20.3 backup. 

While initially, DS exhibited the same symptoms, upon running

<code>ds -u</code>
<code>ds -fiv</code>

The system reinstalled docker and I was able to run DS (to include adding and removing containers) without issue.

**Comment by gjm19761** [comment]
i have this exact same issue after upgrading linux mint

**Comment by nemchik** [comment]
> i have this exact same issue after upgrading linux mint

Try the following:
```shell
sudo -H chown -R "$(id -u)":"$(id -g)" ~/.docker
cd ~/.docker
git fetch -p
git reset --hard origin/master
cd
ds -u
# twice to make sure it works
ds -u

# also recommended
ds -fiv
```
