### ISSUE TITLE
[Feature Request] Wireguard VPN support with PIA or other provider

### ISSUE THREAD

**Issue by dylanmtaylor** [GhostWriters/DockSTARTer#1520]
# Feature request

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Being able to choose to connect to PIA or another VPN provider using wireguard instead of OpenVPN

**Describe alternatives you've considered**
N/A

**Additional context**
Wireguard should have less overhead and offer additional performance over OpenVPN

**Comment by angrycuban13** [comment]
This is already possible - it all depends on the container maintainer to add support for WG

**Comment by dylanmtaylor** [comment]
> This is already possible - it all depends on the container maintainer to add support for WG

Would you be so kind as to provide me with an example of how to set it up? I am using whatever default VPN container dockstarter ships and I am currently using private internet access VPN.

**Comment by dylanmtaylor** [comment]
To clarify, I have it working with OpenVPN but want to use wireguard

**Comment by angrycuban13** [comment]
The container you use is what will determine if OVPN or WG is supported. For instance, Hotio's qbittorrentvpn only supports WG. There are a few VPN containers that are included with DS so I don't know which one you're specifically using

**Comment by prabbit237** [comment]
Just set it in the VPN variables and try it out. If you find one of your ******vpn apps doesn't work, you can always do an over-ride in docker.compose.override.yml to set that one back to openvpn.

From ~/.docker/compose/.env:
````
# VPN Settings
LAN_NETWORK='192.168.0.0/16'
NS1='1.1.1.1'
NS2='8.8.8.8'
VPN_CLIENT='wireguard'
VPN_ENABLE='yes'
VPN_OPTIONS=''
VPN_OVPNDIR='~/.config/appdata/.openvpn'
VPN_PASS='*****redacted*****'
VPN_PROV='pia'
VPN_USER='*****redacted*****'
VPN_WGDIR='~/.config/appdata/.wireguard'
````
However see https://github.com/GhostWriters/DockSTARTer/issues/1533 about a small  bug (that's easily resolved.)
