### ISSUE TITLE
[Application Request] OpenSpeedTest

### ISSUE THREAD

**Issue by dylanmtaylor** [GhostWriters/DockSTARTer#1523]
# Name of the application
OpenSpeedTest

## GitHub
https://github.com/openspeedtest/Speed-Test

## Docker Hub/GitHub Registry
https://hub.docker.com/r/openspeedtest/latest

### Additional context
I would like to run a speed test server within my home network to test 10Gbit speeds from one machine to another.

![image](https://user-images.githubusercontent.com/277927/187499324-3741aeda-3cf1-4080-a2da-eebd2ffc9877.png)

**Comment by angrycuban13** [comment]
PR merged
