### ISSUE TITLE
[BUG] Glances image used by DockSTARTer doesn't include all modules needed for Docker plugin to work

### ISSUE THREAD

**Issue by trolley** [GhostWriters/DockSTARTer#1527]
# Bug report

**Describe the bug**
The Glances image that is used by DockSTARTer is the minimal image (`nicolargo/glances`) which doesn't include all the [dependencies](https://github.com/nicolargo/glances) (see "Available versions on the Docker Hub repository" section). In particular, the `dateutil` Python module is missing, so the Docker plugin does not work. From the Glances log:

```
2022-08-31 19:48:09,285 -- WARNING -- Error loading Docker deps Lib. Docker plugin is disabled (No module named 'dateutil')
```

**To Reproduce**
N/A

**Expected behavior**
Install the "full" image: `nicolargo/glances:latest-full`

**Screenshots**

**System**
(please complete the following information):

- OS: Ubuntu
- Version: 20.04.5 LTS

**Additional context**

**Comment by trolley** [comment]
If the expectation is to use the compose override file to choose a different image please close this.

**Comment by angrycuban13** [comment]
I do not use Glances to really tell you yes or no, as a Glances user what do you think?

**Comment by trolley** [comment]
Since all of the plugins are optional, and now that I know it's easy to work around with the override file, some people may not want the full installation by default. I'll just close this.
