### ISSUE TITLE
[BUG] Goaccess is super out of date

### ISSUE THREAD

**Issue by Bockiii** [GhostWriters/DockSTARTer#1528]
Hi,

The goaccess custom image that you use is horribly out of date, hasn't been updated since 2020 and is hardcoded to Goaccess v1.4 (current is 1.6)

Either get the custom-image to build with the recent versions or switch to the official image ( a lot has happened in the documentation since 2019)

**Comment by angrycuban13** [comment]
We don't build any images, you can reach out to the maintainer of the repo or provide an alternative repo.

https://github.com/GregYankovoy/docker-goaccess

**Comment by Bockiii** [comment]
The alternative would be the official image, it just needs some additional work.

I just want to note that it's not great to use an image that was last updated 2 years ago

**Comment by nemchik** [comment]
I'm fine with using the official image, but you mentioned it needs work, like what?

**Comment by Bockiii** [comment]
The custom one was used because it has an integrated nginx server. The official one doesnt. So you will need a dependency to also have an nginx container that mounts the output of goaccess.

Its all a little annoying :( I actually came to check how you do it because i'm currently trying to solve it myself :D

**Comment by nemchik** [comment]
I see. It sounds like the tool is one that (out of the box) is meant to be a command line utility, and not a web service. I would almost suggest making this an override that places the required files into the config of another nginx container to be served.

**Comment by mattgphoto** [comment]
@Bockiii This will be handy I believe if you end up getting just goaccess to well... go :-) https://github.com/mattgphoto/tools/blob/master/goaccess-proxy.conf
