### ISSUE TITLE
Calibre has a new variable

### ISSUE THREAD

**Issue by rubadub-github** [GhostWriters/DockSTARTer#1540]
this needs added to the docker commands for calibre:
    security_opt:
      - seccomp:unconfined #optional

Otherwise the latest version was failing to run.  I have it in my override, not sure if you want it in the build.

https://hub.docker.com/r/linuxserver/calibre

**Comment by nemchik** [comment]
Resolved in https://github.com/GhostWriters/DockSTARTer/pull/1564
