### ISSUE TITLE
Global or App option to set runtime

### ISSUE THREAD

**Issue by rasorjb** [GhostWriters/DockSTARTer#1554]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Not necessarily. Currently to enable GPU processing inside of a container I have to manually add the "runtime: nvidia" flag in my override file. While not necessarily painful, it is annoying to enable every time I add an app.

**Describe the solution you'd like**
Global or by App variable to set the desired runtime mode that you would prefer.

**Describe alternatives you've considered**
Override.yaml

**Additional context**
None.

**Comment by nemchik** [comment]
Not every container needs access to your GPU. Really it's probably only a select few containers having to do with media playback or conversion. This should be done with the override file. Sorry, I will not be adding a global feature to enable GPU in all containers.
