### ISSUE TITLE
[BUG] quasselweb container name doesn't match LSIO reverse proxy conf

### ISSUE THREAD

**Issue by trolley** [GhostWriters/DockSTARTer#1562]
# Bug report

**Describe the bug**
https://github.com/GhostWriters/DockSTARTer/blob/master/compose/.apps/quasselweb/quasselweb.yml sets the name of the quassel-web container to `quasselweb`, but the LSIO reverse proxy config expects `quassel-web`: https://github.com/linuxserver/reverse-proxy-confs/blob/master/quassel-web.subdomain.conf.sample

It would be preferable to have the DockSTARTer app config use the same name as LSIO so the reverse proxy config works without modification.

**To Reproduce**

N/A

**Expected behavior**
The reverse proxy config for quassel-web to work without modification.

**Screenshots**

**System**
(please complete the following information):

- OS: Ubuntu
- Version: 20.04

**Additional context**
N/A

**Comment by nemchik** [comment]
Unfortunately there are things in DS that require the ability to use the app name as a variable in bash, and bash variables cannot have dashes in them. As an example, DS uses `~/.docker/compose/.env` to store variables that define what containers to run, and there are variables prefixed with `QUASSELWEB_` (as opposed to `QUASSEL-WEB_` which is not a valid variable name).

**Comment by trolley** [comment]
Ah, makes sense. Thanks for explaining.
