### ISSUE TITLE
[BUG] omadacontroller is missing the port.yml file

### ISSUE THREAD

**Issue by SailTheWorldBy50** [GhostWriters/DockSTARTer#1582]
# Bug report

**Describe the bug**
Missing file `omadacontroller.ports.yml` from https://github.com/GhostWriters/DockSTARTer/tree/master/compose/.apps/omadacontroller

No ports are published when `ds -c` is run. The container starts, but there are no ports to access. 

No ports listed in the `.env` file:
```OMADACONTROLLER_ENABLED='true'
OMADACONTROLLER_MANAGE_HTTPS_PORT_8043='8043'
OMADACONTROLLER_MANAGE_HTTP_PORT_8088='8188' #(I changed to 8188)
OMADACONTROLLER_NETWORK_MODE=''
OMADACONTROLLER_PORTAL_HTTPS_PORT_8843='8443'
OMADACONTROLLER_PORTAL_HTTP_PORT_8088='8188'
OMADACONTROLLER_RESTART='unless-stopped'
OMADACONTROLLER_SHOW_MONGODB_LOGS='false'
OMADACONTROLLER_SHOW_SERVER_LOGS='true'
OMADACONTROLLER_SMALL_FILES='false' ```

**To Reproduce**
Steps to reproduce the behavior:

-Add `omadacontroller` to App list in DS
-Run `ds -c`

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/123767524/215169317-a9026409-c59e-4f8d-85fc-33421e73ad03.png)

**System**
(please complete the following information):

- OS: Ubuntu 
- Version: 20.04 LTS Server

**Additional context**
Add any other context about the problem here.

**Comment by SailTheWorldBy50** [comment]
I added ```  omadacontroller:
    container_name: omadacontroller
    ports:
      - "8188:8088"
      - "8043:8043"
      - "8843:8843"
      - "27001:27001/udp"
      - "29810:29810/udp"
      - "29811:29811"
      - "29812:29812"
      - "29813:29813"
      - "29814:29814"```
to my Override and I can now access the container in a browser.

**Comment by mcaron1234** [comment]
This is was address in https://github.com/GhostWriters/DockSTARTer/pull/1620 and can be closed.
