### ISSUE TITLE
[Application Request] Readarr

### ISSUE THREAD

**Issue by HalcyonSeas73** [GhostWriters/DockSTARTer#1614]
# Name of the application
Readarr
## GitHub
https://github.com/Readarr/Readarr
## Docker Hub/GitHub Registry
https://hub.docker.com/r/linuxserver/readarr
### Additional context
Readarr is like Sonarr, but for eBooks!

From the original app [GitHub](https://github.com/Readarr/Readarr):
> Readarr is an ebook and audiobook collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new books from your favorite authors and will grab, sort, and rename them. Note that only one type of a given book is supported. If you want both an audiobook and ebook of a given book you will need multiple instances.

**Comment by mcaron1234** [comment]
Readarr was  added to Dockstarter yesterday.
