### ISSUE TITLE
[Feature Request] Add support for Docker Swarm

### ISSUE THREAD

**Issue by TenTypekMatus** [GhostWriters/DockSTARTer#1621]
# Feature request

**Is your feature request related to a problem? Please describe.**
Yes, it is, and if I want to use a Docker Compose file in the Swarm cluster, then I would need to heavily edit it. 

**Describe the solution you'd like**
Adding another dialog box that'll ask you if you want to use the Compose file with Swarm. 

**Describe alternatives you've considered**
Switching to K3s

**Additional context**
https://dockerswarm.rocks

**Comment by nemchik** [comment]
I don't know a lot about swarm. Could you provide some examples of what needs to be changed in the current output of the `docker-compose.yml` file generated by DS in order to be usable with swarm?

**Comment by TenTypekMatus** [comment]
- You have to specify constraints
- You also have to create networks **manually**
- It doesn't have persistent storage, but there are plenty of Ansible playbooks here on this site
- You have to use services like Traefik to actually get to your services
Here are some another resources that I found:
- https://stackoverflow.com/questions/42545431/when-to-use-docker-compose-and-when-to-use-docker-swarm
- https://geek-cookbook.funkypenguin.co.nz/docker-swarm/
