### ISSUE TITLE
[Application Request] Maloja

### ISSUE THREAD

**Issue by HalcyonSeas73** [GhostWriters/DockSTARTer#1631]
# Maloja

## GitHub
https://github.com/krateng/maloja

## Docker Hub/GitHub Registry
https://hub.docker.com/r/krateng/maloja#docker--podman

### Additional context
> Simple self-hosted music scrobble database to create personal listening statistics. No recommendations, no social network, no nonsense.

Similar to lastFM, but self-hosted. Runs on any x86 or ARM machine that runs Python.

![image](https://user-images.githubusercontent.com/84727791/233517080-9a9e20df-3505-415e-9fa3-932d76efd285.png)

**Comment by HalcyonSeas73** [comment]
Should I "bump" this issue so that it's no longer stale? Or is that discouraged here?

**Comment by nemchik** [comment]
not discouraged. i just haven't been keeping up with DS for a bit. It shouldn't be hard to add. if you want to take a swing at it you can check out recently added apps in the closed PRs of this repo and mimic how they were done.

**Comment by HalcyonSeas73** [comment]
Bumping this issue as it remains an active suggestion.
