### ISSUE TITLE
[Feature Request] Ability to change container name

### ISSUE THREAD

**Issue by mtrolley** [GhostWriters/DockSTARTer#1652]
# Feature request

**Is your feature request related to a problem? Please describe.**
The app configs have the docker container name hard coded, so there's no way to modify them if needed. For example, I use `sabnzbdvpn` but to use SWAG auto proxy mod it expects the container name to be `sabnzbd`.

**Describe the solution you'd like**
Having a variable per app in the `.env` file for container name that gets populated with the default name but can be modified would allow renaming the container (e.g. `SABNZBDVPN_CONTAINER_NAME=sabnzbd`).

**Describe alternatives you've considered**
I tried to override the container name in `docker-compose.override.yml` but it is not overridable.

**Additional context**
N/A

**Comment by nemchik** [comment]
An easier solution is to modify the swag config. Just set the upstream app variable to sabnzbdvpn. I think they use the same port.

I think the main difference with service name and container name (as far as how if affects users) is where you can use them. Ex: `docker restart CONTAINER` and `docker compose restart SERVICE`, although I imagine the compose cli is far less used in this way. DS does have a use case for the compose cli, but I'm not sure if we use the docker cli in a way that would conflict.

I'll look into it, but I'm thinking we probably won't make this change even with no conflicts, just to avoid confusion for users.

**Comment by mtrolley** [comment]
Hi @nemchik, I appreciate the quick feedback.

That's what I'm doing now, but that means I'm manually managing the proxy config files. The [SWAG auto-proxy mod](https://github.com/linuxserver/docker-mods/tree/swag-auto-proxy) uses a label on the container to automatically apply the proxy config. I had dozens of proxy config files, and whenever LSIO updates them all you get is a warning in the SWAG log telling you it needs to be updated, so I just went through the process of switching all of them to use the auto-proxy mod so I never need to worry about manually updating again, except for two holdouts that won't work because the container names don't match what the mod supports: `sabnzbdvpn` needs to have container name `sabnzbd` and `transmissionvpn` needs to have container name `transmission`.

I'm not sure how many people make manual changes in `.env`, so unless someone went in and specifically changed the `<CONTAINER>_CONTAINER_NAME` variable everything would continue to work like it does now I'd think. For example a lot of containers have variables in `.env` for modifying the ports they run on, I see this as similar to that: not likely changed by many users, but useful when you need to.

**Comment by nemchik** [comment]
i have started looking at a potential alternate option; having a vpn container in DS that users would assign other containers to operate through. with that approach you would use the sab or transmission container with the names expected by swag, but you would be able to route traffic through your vpn. it's a work in progress, and i don't use a vpn, so testing will be limited.

**Comment by nemchik** [comment]
FYI the vpn container that you can route other containers through was added in https://github.com/GhostWriters/DockSTARTer/pull/473 and you can now use the default container that matches the name swag expects. You'll need an override to setup the container vpn, which I have not tested or experimented with in a few years, but the basic idea is setting the container's network mode to the other container. This can sort of be done without an override, but I believe it does not keep the container visible for swag since it would no longer be on the same docker network as swag, but I believe an override can make it work for both uses.
