### ISSUE TITLE
[Application Request] Kapowarr

### ISSUE THREAD

**Issue by methanoid** [GhostWriters/DockSTARTer#1663]
Kapowarr

GitHub  https://casvt.github.io/Kapowarr/

Docker Hub/GitHub Registry   https://hub.docker.com/r/mrcas/kapowarr

This is a Comic manager (similar to Mylar3 but with strong styling/look of other Arrs like Sonarr/Radarr). Always good to have an alternative app in the toolbox

**Comment by rutskiuk** [comment]
+1 for this, long term Mylar3 user keen to try the 'arrquivalent

**Comment by patredtheknight** [comment]
+1 as well
