### ISSUE TITLE
[BUG] Containers installed via override don't inherit system time/timezone

### ISSUE THREAD

**Issue by eZtaR1** [GhostWriters/DockSTARTer#1695]
# Bug report

**Describe the bug**
Applications installed via the ~/.docker/compose/docker-compose.override.yml won't inherit the system time or time zone.
F.ex.
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - Europe/Paris

**To Reproduce**

- Add an application to your docker override, for example this addition of crowdsec:
-   crowdsec:
    image: 'docker.io/crowdsecurity/crowdsec:latest'
    container_name: crowdsec
    environment:
      - GID=1000
      - >-
        COLLECTIONS=crowdsecurity/nginx crowdsecurity/http-cve
        crowdsecurity/whitelist-good-actors
      - CUSTOM_HOSTNAME=hostcomputer
    volumes:
      - '${DOCKERCONFDIR}/crowdsec/config:/etc/crowdsec:rw'
      - '${DOCKERCONFDIR}/crowdsec/data:/var/lib/crowdsec/data:rw'
      - '${DOCKERCONFDIR}/swag/log/nginx:/var/log/swag:ro'
      - '/var/log:/var/log/host:ro'
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true

**Expected behavior**
That the container inherits the system time as set in the global variables. But it's an hour before

**System**

- OS: Ubuntu
- Version 22.04.3

**Comment by nemchik** [comment]
If you include

```yaml
  volumes:
    - /etc/localtime:/etc/localtime:ro
```

the container should respect your host system's time unless the application has some kind of environment variable it uses to set timezone like `TZ` or `TIMEZONE` (usually noted in the documentation from the image)

**Comment by eZtaR1** [comment]
> If you include
> 
> ```yaml
>   volumes:
>     - /etc/localtime:/etc/localtime:ro
> ```
> 
> the container should respect your host system's time unless the application has some kind of environment variable it uses to set timezone like `TZ` or `TIMEZONE` (usually noted in the documentation from the image)

Yeah I figured that was the solution, I was just wondering i could do something a bit more systemic :)

**Comment by angrycuban13** [comment]
This is not a DockSTARTer issue, closing.
