### ISSUE TITLE
[BUG] calibre-web installs as calibreweb in dockstarter, this breaks swag.

### ISSUE THREAD

**Issue by eZtaR1** [GhostWriters/DockSTARTer#1709]
# Bug report

**Describe the bug**
When installing calibre-web with dockstarter, the installed container is called calibreweb.
When you install swag and try to use the included nginx/proxy-confs/calibre-web.subdomain.conf.sample, it references the wrong container and leaves you with a broken config, leading to error 502.

**To Reproduce**
cp .config/appdata/swag/nginx/proxy-conf/calibre-web.subdomain.conf.sample calibre-web.subdomain.conf
docker restart swag
error 502

**Additional context**
Changing either the container name to calibre-web or editing calibre-web.subdomain.conf.sample or calibre-web.subfolder.conf.sample to "set $upstream_app calibreweb;" fixes the problem

**Comment by angrycuban13** [comment]
This is not a bug. We don't use `-` in DockSTARTer. You just need to change the container name in the SWAG proxy config.
