### ISSUE TITLE
Komga container port - 25600

### ISSUE THREAD

**Issue by Sridou** [GhostWriters/DockSTARTer#1744]
# Bug report

After reading the [official Komga Docker installation](https://komga.org/docs/installation/docker), it seems that container port in  DockSTARTer template (komga.ports.yml) should be 25600 instead of 8080. I have tested the same by changing the port to 25600 and Komga Web UI interface is accessible now. By the looks of it, it has been like that since [Version 1.0 ](https://komga.org/blog/prepare-v1/). 

I don't know how it went unnoticed till date, maybe nobody uses this anymore ( I'm just starting my journey), but if somebody  could change the port, so that I don't have to override it in docker-compose.override.yml, it would be beneficial.

**Comment by Audiard-Jerome** [comment]
I saw the same problem a few weeks ago.

**Comment by cyberweasel** [comment]
I had this working fine but it seems to have stopped.  Maybe during a Komga update but now same problem.  It is mapped as 25600:8080 in docker.  I am not a docker pro but I think it needs to be 25600:25600.  Not sure how to change except maybe via an override for now but I am afraid I would lose my Komga config.
