### ISSUE TITLE
[Feature Request] Support Setting DOCKER_MODS in Linuxserver Containers

### ISSUE THREAD

**Issue by viveksupe** [GhostWriters/DockSTARTer#1792]
# Feature request

**Is your feature request related to a problem? Please describe.**

Trying to override containers to include DOCKER_MODS= but the override isn't being merged. There are multiple containers that support mods that do on persist after compose recreate.

Eg features: 
- https://mods.linuxserver.io/
- https://github.com/linuxserver/docker-mods

Can future versions allow users to add these mods as Env variables or similar?

**Comment by CLHatch** [comment]
> # Feature request
> **Is your feature request related to a problem? Please describe.**
> 
> Trying to override containers to include DOCKER_MODS= but the override isn't being merged. There are multiple containers that support mods that do on persist after compose recreate.
> 
> Eg features:
> 
> * https://mods.linuxserver.io/
> * https://github.com/linuxserver/docker-mods
> 
> Can future versions allow users to add these mods as Env variables or similar?

I can confirm that `DOCKER_MODS` does work in the override file, I do it myself.  So unless there is something odd about the docker mod you are attempting to use, you must be doing something wrong there.  Here's an example of one I used to be using:

```yaml
  swag:
    environment:
      - DOCKER_MODS=linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-dashboard
```

That said, I actually suggested adding the `DOCKER_MODS` variable to the `.env` in Discord last month, before seeing this FR. :)
