### ISSUE TITLE
NPM Compose Override Volumes inconsistent with .env defaults

### ISSUE THREAD

**Issue by grebz-dev** [GhostWriters/DockSTARTer#1795]
https://github.com/GhostWriters/DockSTARTer/blob/b6c16361d7c7749ffe8aeecafa18d36fc2ceda25/docs/overrides/nginxproxymanager.md?plain=1#L42-L45

These lines need to be updated to:
```
      - ${DOCKERCONFDIR}/proxymanager/config.json:/app/config/config.json
      - ${DOCKERCONFDIR}/proxymanager/data:/data
      - ${DOCKERCONFDIR}/proxymanager/letsencrypt:/etc/letsencrypt
      - ${DOCKERSTORAGEDIR}:/storage
```

**Comment by CLHatch** [comment]
> https://github.com/GhostWriters/DockSTARTer/blob/b6c16361d7c7749ffe8aeecafa18d36fc2ceda25/docs/overrides/nginxproxymanager.md?plain=1#L42-L45
> 
> These lines need to be updated to:
> 
> ```
>       - ${DOCKERCONFDIR}/proxymanager/config.json:/app/config/config.json
>       - ${DOCKERCONFDIR}/proxymanager/data:/data
>       - ${DOCKERCONFDIR}/proxymanager/letsencrypt:/etc/letsencrypt
>       - ${DOCKERSTORAGEDIR}:/storage
> ```

Actually, those variables have been renamed to the `DOCKER_VOLUME_*` ones in a major update that came out recently.  You'll see this next time you do a `ds -u`.

**Comment by grebz-dev** [comment]
My mistake!
