### ISSUE TITLE
Universal settings don't seem to be applied.

### ISSUE THREAD

**Issue by MikeEdinger** [GhostWriters/DockSTARTer#191]
Not sure how to add the Help Wanted tag.  

**Describe the bug**
I changed the .env file Universal settings as suggested in the Setup your environment section of the Advanced Usage section of the wiki.  Used dockstarter to create my desired containers (radarr, sonarr, sabnzbd, etc)  When trying to update default folders (such as temporary download folder in sabnzbd) or bulk add movies in Radarr using my Movies library, the respective service says these folders do not exist.  I'm assuming it's because these folders exist outside of the containers.

**To Reproduce**
1. cd ~/.docker/compose
2. cp .env.example .env
3. sudo nano .env
4. Change the universal settings to the following (this is a direct copy/paste from .env):
`# Universal Settings

DOCKERCONFDIR=~/.docker/config

DOCKERSHAREDDIR=~/.docker/shared

DOWNLOADSDIR=/media/myMedia/completeTorrent

MEDIADIR_BOOKS=/media/myMedia/random

MEDIADIR_COMICS=/media/myMedia/random

MEDIADIR_MOVIES=/media/myMedia/Movies

MEDIADIR_MUSIC=/media/myMedia/random

MEDIADIR_TV=/media/myMedia/TV_Shows

PGID=1000

PUID=1000

TZ=America/New_York
`
5. sudo bash ~/.docker/main.sh
6. Configure apps, Select desired apps.
7. When asking What would you like to set for DOCKERCONFDIR, I select keep current ~/.docker/config, it then asks to create the directory.  Same of SHAREDDIR.
8. It asks to set DOWNLOADSDIR, I keep current.  Does this for all other directories listed in Universal Settings.
![setdownloadsdir](https://user-images.githubusercontent.com/7926037/44966966-43659800-af0c-11e8-89db-7602edacf2ff.PNG)
![setpermissions](https://user-images.githubusercontent.com/7926037/44966969-46f91f00-af0c-11e8-8f52-eea3f05702c7.PNG)

9.  Everything installs without errors.
10. I go to service web gui, attempt to add folders.  Get the following errors:
![sabnzbd](https://user-images.githubusercontent.com/7926037/44967098-e4ece980-af0c-11e8-8488-2bf1b3e246bf.PNG)
![radarr](https://user-images.githubusercontent.com/7926037/44967100-e6b6ad00-af0c-11e8-8db1-4a6f1104aad5.PNG)

**Expected behavior**
Should be able to access /media/myMedia from within these services.

**Screenshots**

**System (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
Also changed folder permissions to 775, so folder permissions are not the issue.  I am a linux novice and my only experience with docker is with dockstarter.

**Comment by nemchik** [comment]
The way docker works is the volumes have an inside and an outside setting. DS prompts you to see the outside settings (where the folders exist on your OS). The apps inside the containers see those folders mounted as `/downloads` or `/movies` or `/tv`. The main benefit of this is you could move your media or config files or download folder and you would just need to update your `.env` file to point to the correct locations and you would not need to reconfigure the apps or change every folder in every app to point to your new disk locations, etc.

Please let me know if you can see your stuff in the folders I mentioned.

**Comment by MikeEdinger** [comment]
> The way docker works is the volumes have an inside and an outside setting. DS prompts you to see the outside settings (where the folders exist on your OS). The apps inside the containers see those folders mounted as /downloads or /movies or /tv. The main benefit of this is you could move your media or config files or download folder and you would just need to update your .env file to point to the correct locations and you would not need to reconfigure the apps or change every folder in every app to point to your new disk locations, etc.

Oh, I see.  Okay, yeah, I just went into Radarr and used the /movies directory instead and everything showed up.  I think I get how that works now.

This is a someone unrelated question, but it's quick and I don't want to clutter your git.  But when I start making radarr/sonarr try to work with sabnzbd/jackett/hydra, should I use my local IP (192.168.....), or should I be using the IP address displayed in portainer?

**Comment by nemchik** [comment]
Use the name of the container and the original port as needed. For example, no matter what port you set for sonarr, you should always connect from others docker containers on the same host using `http://sonarr:8989/` and apply that same method to all other apps running in docker on the same host.

If you host multiple machines, then to refer to an app on another machine (whether it's in docker or not) you'll use the other machine's IP address and the port you've set for the app.

**Comment by nemchik** [comment]
I've marked this invalid as it's just a misunderstanding and nothing actually wrong or broken. I don't mind answering more questions if you've got them. We also have a discord chat linked in the readme if you'd like to join and ask things there.
