### ISSUE TITLE
torrent client with vpn

### ISSUE THREAD

**Issue by eskimos2000** [GhostWriters/DockSTARTer#222]
Hi 

Could you add transmission with openvpn, please?
Plex could be useful as well.

Cheers

**Comment by nemchik** [comment]
We already have this included in DS. If you started using DS before we added it you can update DS to get the new apps.

**Comment by eskimos2000** [comment]
I have installed DS (I reckon the latest version) and there is no Plex or transmission with vpn,  however, I can see them in env file. But on the main screen with app selection no. How to check if I have the latest version?

**Comment by nemchik** [comment]
I see now (connected the dots). You're using arm64. The containers that include torrent clients with VPN only support x86_64. Likewise the official Plex image only supports x86_64. There is an LSIO image for Plex on arm64, but you should be aware that you will not have a great experience if you require transcoding or subtitles. You can add this to DS using overrides (see the wiki and join discord our for assistance).

For VPN I would recommend installing a VPN client directly on your OS and then see our FAQ wiki page for some info on making sure docker only runs when the VPN is up. You could also reach out to the dev of the transmission VPN docker image (haugene) or the dev of the deluge/rtorrent VPN clients (binhex) and request support for armhf/arm64. We can add them to DS if they are able to make an image.

**Comment by eskimos2000** [comment]
Yeah I read more on yr wiki and there is a table which explain this, I should read first sorry.
On haugene repo there are armhf dockerfiles which run on raspberry pi, however, I do not know if there are 32 or 64. I will contact him to determine that. I will be back to you for help when I will sort it out.
I need plex only as database and manager. I will play everything on Kodi with kodiplexconnect best combo ever.
Cheers

**Comment by nemchik** [comment]
You could try running Plex directly on the host OS, they have a debian package that I recommend using for the installation. There's also a script by MrWolf that will handle updates to plex a LOT better than the native updater.

For haugene's armhf docker file it's 32 (armhf = 32, aarch64 = 64) but armhf works just fine on aarch64. The downside is it's just the dockerfile meaning you have to pull his repo and compile the image yourself for use in docker. I've seen this done before but I believe it took a very long time to build the docker image. This also needs to be done any time haugene updates his image. You might have better luck than the last person. If haugene has the capability to build the arm image himself or automate the process in some way that would be ideal. Otherwise I recommend installing the vpn software directly on your host OS. This would put all traffic through the VPN, not just torrents, but it would likely be the better option long term until (if) an arm image becomes available.

**Comment by nemchik** [comment]
Here's that script for plex updates https://github.com/mrworf/plexupdate

**Comment by eskimos2000** [comment]
Man, thank you for all that info. That sounds good and I started to moving towards that direction as well.
My idea is to run on odroid c2 (plex, homeassistant, pihole), and on rasppi3 download box (torrent, nzbget, sonarr, radarr, jacket, opnevpn) but all media will be on my NAS. So I need to have easy access to it and from docker sometimes it is tricky so I need to abandon docker for a while).

Cheers

**Comment by w111a** [comment]
The recent release of Transmission VPN by Haugene is titled  "Provider updates and bug fixes, automated armhf builds". As you said before that we would need automated builds to have Transmission VPN added for armhf, is this now a possibility?

**Comment by eskimos2000** [comment]
Yeah there is armhf version available now. I have changed my settings in the meantime and have now odroid HC2 NAS, with OMV on in with Docker installed, just tried Haugene container ale went well until some error with VPN happened, I am in touch with him to solve the issue. So yeah I will be using docker but not your DockSTARTER. Thank you very much for remembering my case. Cheers mate.

**Comment by w111a** [comment]
Looks like eskimos2000 got it working( https://github.com/haugene/docker-transmission-openvpn/issues/633). Would be a nice addition to this project. Thanks for all the hard work, awesome resource.

**Comment by nemchik** [comment]
Are you able to point me to something that shows haugene's recommendation to use the dev tag and that he supports this as the primary use for arm users? I'm a little cautious about putting dev builds in unless I have some confirmation from the developer.

**Comment by eskimos2000** [comment]
I was based on the answer here:

https://github.com/haugene/docker-transmission-openvpn/issues/571

**Comment by w111a** [comment]
I can say that i pulled  the haugene/transmission-openvpn:latest-armhf version and have it working on my Rpi3B using NordvppPN with no problems. All leak tests complete.
