### ISSUE TITLE
grafana

### ISSUE THREAD

**Issue by nemchik** [GhostWriters/DockSTARTer#227]
https://hub.docker.com/r/grafana/grafana/

**Comment by JuezFenix** [comment]
Take a look to this https://github.com/stefanprodan/dockprom

**Comment by nemchik** [comment]
That looks like it'll That looks interesting. I'll see if any of it would make sense to put into out YML templates for grafana and possibly include the other apps from there as well. dockerprom itself seems to just be a premade compose file so really we'd almost be replicating what it does.

**Comment by JuezFenix** [comment]
Even, as you can see, have a "traefik like" proxy, caddy. That it's much more easily to configure.
Using the base of this, i added a bot to notify from alerts to telegram bot. That could be another amazing add to this.
