### ISSUE TITLE
Headphones and sonarr ports

### ISSUE THREAD

**Issue by JuezFenix** [GhostWriters/DockSTARTer#232]
Headphones and sonarr use port 8081, same as medusa, so they cant use as the same time. I suggest to change port of headphones and sonnar

**Comment by nemchik** [comment]
From what I can tell, headphones uses 8181, Medusa uses 8081, and sonarr uses 8989.

If an app uses the same port as another app you can change the ports in `~/.docker/compose/.env` to be whatever ports you like.

**Comment by nemchik** [comment]
P.s. you would do it by putting the custom pretty after the `=` so the original port remains before the `=` like this: `SONARR_PORT_8989=1234`

**Comment by JuezFenix** [comment]
Ok, thanks, but i think that it's a good idea change it from default

**Comment by nemchik** [comment]
Which apps are you trying to say have a conflict? The ones you've mentioned so far user unique ports.

Ex: letsencrypt and nextcloud both want 443

**Comment by JuezFenix** [comment]
Headphones, medusa and sickrage use 8081 rigth now. I change manualy headphones to 8082 and medusa to 8084 an conflict solved.

**Comment by nemchik** [comment]
As of the latest commit in the repo from 3 days ago

Headphones uses 8181
https://github.com/GhostWriters/DockSTARTer/blob/f48954dc3037646c701d18086097f103f87933b2/compose/.env.example#L78

Medusa uses 8081
https://github.com/GhostWriters/DockSTARTer/blob/f48954dc3037646c701d18086097f103f87933b2/compose/.env.example#L143

Sickrage uses 8081
https://github.com/GhostWriters/DockSTARTer/blob/f48954dc3037646c701d18086097f103f87933b2/compose/.env.example#L260

Sonarr uses 8989
https://github.com/GhostWriters/DockSTARTer/blob/f48954dc3037646c701d18086097f103f87933b2/compose/.env.example#L265

---

So you are correct that Medusa and Sickrage both use the same port, but Sickrage was not mentioned until your most recent comment this morning. Also Medusa and Sickrage are both TV PVR applications, which to my knowledge do the same thing. If you need them both at the same time you can change the port in your `~/.docker/compose/.env` file to something like `SICKRAGE_PORT_8081=8084`. Once you set something in your env file it will be remembered and carried over through future updates of DS, so you won't have to set it again. This is not much different than if you were to have installed the applications natively without docker (they cannot run on the same port and you would have to adjust it manually).

I am going to close this issue for now, but feel free to continue the discussion here, or join us on discord (link in the readme) to chat more about it.
