### ISSUE TITLE
A few more apps

### ISSUE THREAD

**Issue by JuezFenix** [GhostWriters/DockSTARTer#233]
I thinks should be easy and good to add those dockers:

Airdc++ (maybe the best are romancin/airdcpp-webclient): its a DC++ client, a new way to get new content for the media server.

h5ai (maybe the best are clue/h5ai), web index for the downloader content tougth a web browser.

traefik (official docker), awesome proxy that can be used to transform the nightmare of ports on a very well organized structure of subdomains or "folders"

vsftpd (maybe the best are fikipollo/vsftpd-docker), an ftp to access files anywhere.

**Comment by nemchik** [comment]
Would you mind to make a separate issue for each of these requests? I appreciate the suggestions on which docker image to use, that is helpful!

I'm going to close this but I look forward to the separate issues and we can address them each individually.
