### ISSUE TITLE
Airdc++

### ISSUE THREAD

**Issue by JuezFenix** [GhostWriters/DockSTARTer#234]
Airdc++: 

Info about it: 

https://www.airdcpp.net/

https://en.wikipedia.org/wiki/DC%2B%2B

Docker and integration:

The best existing docker could be https://hub.docker.com/r/romancin/airdcpp-webclient/

As we can see they only need one port, two bind for persistent data (one for download and another for sharing content). To work, need 2 files before starting the docker, those two files are accesible from docker github.

Reason 

its a DC++ client, a new way to get new content for the media server.

**Comment by nemchik** [comment]
Fyi #268 adds the prompt for individual app settings.
