### ISSUE TITLE
Plex - DLNA

### ISSUE THREAD

**Issue by UnR34L** [GhostWriters/DockSTARTer#241]
I can't get DLNA to work,

Looking at the plex site all the correct ports are mapped in docker and I turned on GDM. linuxserver.io's [README.md](https://github.com/linuxserver/docker-plex/blob/master/README.md) recommends that we just use host networking.

So by default DockSTARTer maps the ports and doesn't use host networking, I'm wondering if there's a reason for that and if it'll cause problems if I just switch to host networking.

ESXI - Ubuntu 18.04.1 LTS - Docker version 18.06.1-ce, build e68fc7a

**Comment by UnR34L** [comment]
Damn, never noticed PLEX_NETWORK_MODE. Open ports don't seem to be enough, something to do with multicast.

I feel like it should really be the default if it breaks functionality.

Thanks.

**Comment by nemchik** [comment]
For some reason the official image documentation lists bridge mode as the default mode. It might be possible that there's a setting somewhere in Plex that needs to be set for dlna to work in bridge mode, or another port that needs to be open. DS includes all the ports mentioned in the documentation.

**Comment by ismay** [comment]
> For some reason the official image documentation lists bridge mode as the default mode.

For me clients trying to access my plex server when on the same network, could only find the server if it was running in `host` mode. This has also been the case for me when running plex docker containers before I used DS. I'm not sure if this does work for other people when in bridge mode, and why it's not working without host though. All other containers work fine when bridged.

**Comment by nemchik** [comment]
According to this https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/ we have all the ports Plex has documented that they would be using. Two specific ports are listed for DLNA use, so I am not sure why it would not work. We also include 33400 for the Plex Web Tools plugin.

**Comment by ismay** [comment]
Yeah I know, it doesn't make sense to me either. It's just what I've found, both with the plex container DS installs, and the linuxserver.io plex container.

The only variable I changed to make access to plex work for my phone and htpc on the local network is to set `PLEX_NETWORK_MODE=host` in `~/.docker/compose/.env` and to run `sudo ds -c up`. That's it, didn't change anything else.
