### ISSUE TITLE
transmissionvpn w/ proxy option

### ISSUE THREAD

**Issue by robertbaker** [GhostWriters/DockSTARTer#263]
**Is your feature request related to a problem? Please describe.**
The transmissionvpn isn't quite turnkey. If you want to setup a proxy to access it locally and have radarr/sonarr talk to it, then you have some setup to do.

**Describe the solution you'd like**
make it work locally out of the box.

This is for the built in proxy. However, I think it's possible with letsencrypt with a subdomain.conf by doing the same link,.

Here's the command for reference:
```
docker run -d  --network compose_default  --link transmissionvpn:transmission -p 8080:8080 haugene/transmission-openvpn-proxy
```
**Additional context**
Out of the box, sonarr and radarr can't communicate with transmissionvpn. that docker image includes a reverse proxy, but it's not ideal if you use letsencrypt.

**Comment by nemchik** [comment]
I'll do some testing on this and see what I can figure out. Others reported they were able to get this container working but I personally did not have much luck with it.

**Comment by robertbaker** [comment]
I got as far as getting it to work locally but not over the internet. I switched to rtorrent + flood.
