### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by jamin215** [GhostWriters/DockSTARTer#270]
**Describe the bug**
I have started using Duplicati for backing up my system and it can only see files under the dockershared directory. At first I had it set to my home folder /home/user but then I wanted to backup other folders so I changed the dockershared directory to / just to included everything. Then I realized the permissions would not allow me to backup what I wanted to. Without thinking very much about it I re-ran configure apps and said yes to set permissions to the dockershared folder (/)  This most obviously ruined my entire ubuntu installation as now essentially all permissions were set to my user.  Maybe a warning or actually not allowing someone to set permissions for certain folders.

**To Reproduce**
1. Set dockershared folder to /
2. Answer Yes to set permissions in dockershared folder
3. All permissions are now borked.

**Expected behavior**
To not so easily ruin the entire OS with a few clicks and no warnings.

**System (please complete the following information):**
 - OS: Ubuntu 18

**Additional context**
- I have files I would like to back up outside of my user folder and might not be owned by my user.

**Comment by nemchik** [comment]
I'm very sorry that happened and I realized how this might be an issue and actually have a fix in testing as of yesterday
https://github.com/GhostWriters/DockSTARTer/pull/268/files#diff-f33cec0badc3bf06d2c9e4101fc3c295R10

In the future, what you want is to edit your `~/.docker/compose/.env` file and set the `DUPLICATI_SOURCEDIR` to `/` and then duplicati will see `/` inside `/source`

**Comment by nemchik** [comment]
P.S. that check is the start of possibly some more robust checks such as double prompting if you are sure you want to set the permissions on a folder if it is outside of your home directory (default will be no, but you could select yes), and there's a few more system paths I'd like protected against permission resets as well. I also plan to change the folder prompt to disallow the use of `~` and by default will have an option that automatically replaces `~` with `/home/<user>`

**Comment by jamin215** [comment]
Awesome, thanks for the tip to change the .env file I was not aware of that setting. Also thanks for the quick reply I look forward to this project growing and improving.
