### ISSUE TITLE
Add FileBrowser

### ISSUE THREAD

**Issue by wolf39us** [GhostWriters/DockSTARTer#296]
**Is your feature request related to a problem? Please describe.**
**NO**

**Describe the solution you'd like**
**Add FileBrowser to available options in DS**

**Describe alternatives you've considered**
**Suggested container here:
https://github.com/filebrowser/filebrowser**

**Additional context**

**Comment by islanddog** [comment]
Would absolutely love this as it would provide a clean way to clean up archives remotely.

**Comment by nemchik** [comment]
It looks like this project is currently in a bit of a holding pattern.
https://github.com/filebrowser/filebrowser/issues/532
I will keep this issue open until we see some update to that issue, or out repo's stalebot closes it (if that happens we can always reopen it if needed).
