### ISSUE TITLE
OpenVPN-AS

### ISSUE THREAD

**Issue by DArkes1312** [GhostWriters/DockSTARTer#312]
https://hub.docker.com/r/linuxserver/openvpn-as/

This one could be a great add, webgui openvpn server.

**Comment by nemchik** [comment]
Sounds promising. I'll get it added.

**Comment by mkono87** [comment]
Used it on unraid, worked great

**Comment by nemchik** [comment]
Need some volunteers for testing #370 
Testing information is on our discord chat (link is the chat badge in the readme) see the announcements channel to join testing.
