### ISSUE TITLE
Regarding Organizr v2

### ISSUE THREAD

**Issue by islanddog** [GhostWriters/DockSTARTer#313]
Just curious to when we might be getting Organizr v2 Installer available as I wanted to switch from Atomik over to this.

https://github.com/GhostWriters/DockSTARTer/projects/8#card-13803427

**Comment by nemchik** [comment]
DockSTARTer has actually had Organizr V2 for quite some time. The card you linked shows a recent change (already completed) to change to using a new repo for Organizr V2. In DockSTARTer it is just labeled Organizr as there is no need for us to have both versions.

**Comment by islanddog** [comment]
Just saw this after looking through the Available Application list notes. Apologies.
