### ISSUE TITLE
Pi-hole incorrect IP in config

### ISSUE THREAD

**Issue by foamz** [GhostWriters/DockSTARTer#318]
**Describe the bug**
Installing Pi-hole via the installer with default settings leave the IP set as "192.168.x.x", instead of using the container's IP.

**To Reproduce**
Install Pi-hole using the installer, without setting App variables after installation. Log into Portainer, view containers and see pi-hole attempting to start, only to fail.

**Expected behavior**
Retrieve container's IP and inject into configuration.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.1 & Latest Raspbian

BTW, awesome work! I really love how convenient DockSTARTer is.

**Comment by nemchik** [comment]
I'll look into this, but I actually don't believe it's supposed to have a 192.168.x.x address. The container is put on your compose network (which has 172.x.x.x addresses), and is bridged to your host.

I'll see what I can figure out anyway, but pihole is a bit of an advanced container and thus already has some notes in our wiki about initial setup.

**Comment by nemchik** [comment]
Ok, sorry for not reviewing this sooner.

My Docker Host (server) IP address is `192.168.1.21`, so that's what I use for `PIHOLE_SERVERIP`

You should change the IP address to match your system IP. After saving that change, run `sudo ds -g` to make the changes affect the container.

**Comment by foamz** [comment]
No worries, that is what I did to fix the IP address.
I just thought I'd log it as it wasn't clear in the beginning why pi-hole wasn't starting. Only after some debugging I came across it.
I wasn't sure if it was overlooked, thus logged it here.
