### ISSUE TITLE
airdccpp fails

### ISSUE THREAD

**Issue by malabrito** [GhostWriters/DockSTARTer#322]
AirDC++ container fails to run.

I have installed only this container with all default options in a new instance (along with portainer and watchtower as per DockSTARTer's default options).

Portainer's log for this container shows:

> .No valid configuration found. Run the application with --configure parameter to set up initial configuration.

**Comment by nemchik** [comment]
In your `~/.docker/compose/.env` what do you have for the following:
```
AIRDCPP_SHAREDIR
DOCKERCONFDIR
DOCKERSHAREDDIR
DOWNLOADSDIR
PUID
PGID
```

They won't be in that order.

**Comment by malabrito** [comment]
> In your `~/.docker/compose/.env` what do you have for the following:
> 
> ```
> AIRDCPP_SHAREDIR
> DOCKERCONFDIR
> DOCKERSHAREDDIR
> DOWNLOADSDIR
> PUID
> PGID
> ```
> They won't be in that order.

Pasted all ~/.docker/compose/.env and bolded what you asked for:


# Universal Settings
**DOCKERCONFDIR=/home/mlab/.docker/config**
DOCKERGID=999
**DOCKERSHAREDDIR=/home/mlab/.docker/config/shared**
**DOWNLOADSDIR=/mnt/downloads**
MEDIADIR_BOOKS=/mnt/medialibrary/books
MEDIADIR_COMICS=/mnt/medialibrary/comics
MEDIADIR_MOVIES=/mnt/medialibrary/movies
MEDIADIR_MUSIC=/mnt/medialibrary/music
MEDIADIR_TV=/mnt/medialibrary/tv
**PGID=1000
PUID=1000**
TZ=America/sao paulo

# VPN Settings
LAN_NETWORK=192.168.0.0/16
NS1=1.1.1.1
NS2=8.8.8.8
VPN_ENABLE=yes
VPN_OPTIONS=
VPN_PASS=
VPN_PROV=pia
VPN_USER=

# App Settings

### AIRDCPP
AIRDCPP_ENABLED=true
AIRDCPP_NETWORK_MODE=
AIRDCPP_PORT_21248=21248
AIRDCPP_PORT_21249=21249
AIRDCPP_PORT_5600=5600
AIRDCPP_PORT_5601=5601
**AIRDCPP_SHAREDIR=/mnt/NAS**

### AIRSONIC
AIRSONIC_ENABLED=false
AIRSONIC_NETWORK_MODE=
AIRSONIC_PORT_4040=4040
AIRSONIC_CONTEXT_PATH=/airsonic
AIRSONIC_JAVA_OPTS=

### BAZARR
BAZARR_ENABLED=false
BAZARR_NETWORK_MODE=
BAZARR_PORT_6767=6767

### CALIBREWEB
CALIBREWEB_ENABLED=false
CALIBREWEB_NETWORK_MODE=
CALIBREWEB_PORT_8083=8083

### COUCHPOTATO
COUCHPOTATO_ENABLED=false
COUCHPOTATO_NETWORK_MODE=
COUCHPOTATO_PORT_5050=5050

### DDCLIENT
DDCLIENT_ENABLED=false
DDCLIENT_NETWORK_MODE=

### DELUGE
DELUGE_ENABLED=false
DELUGE_NETWORK_MODE=
DELUGE_PORT_58846=58846
DELUGE_PORT_58946=58946
DELUGE_PORT_8112=8112

### DELUGEVPN
DELUGEVPN_ENABLED=false
DELUGEVPN_NETWORK_MODE=
DELUGEVPN_PORT_58846=58846
DELUGEVPN_PORT_58946=58946
DELUGEVPN_PORT_8112=8112

### DUCKDNS
DUCKDNS_ENABLED=false
DUCKDNS_NETWORK_MODE=
DUCKDNS_LOG_FILE=true
DUCKDNS_SUBDOMAINS=
DUCKDNS_TOKEN=

### DUPLICATI
DUPLICATI_ENABLED=false
DUPLICATI_NETWORK_MODE=
DUPLICATI_PORT_8200=8200
DUPLICATI_BACKUPSDIR=~/.docker/config/backups
DUPLICATI_SOURCEDIR=~/.docker/config

### EMBY
EMBY_ENABLED=false
EMBY_NETWORK_MODE=
EMBY_PORT_8096=8096
EMBY_PORT_8920=8920

### GLANCES
GLANCES_ENABLED=false
GLANCES_NETWORK_MODE=
GLANCES_PORT_61208=61208
GLANCES_PORT_61209=61209

### GUACAMOLE
GUACAMOLE_ENABLED=false
GUACAMOLE_NETWORK_MODE=
GUACAMOLE_PORT_8080=8080
GUACAMOLE_EXTENSIONS=

### HEADPHONES
HEADPHONES_ENABLED=false
HEADPHONES_NETWORK_MODE=
HEADPHONES_PORT_8181=8181

### HEIMDALL
HEIMDALL_ENABLED=false
HEIMDALL_NETWORK_MODE=
HEIMDALL_PORT_443=445
HEIMDALL_PORT_80=1801

### HOMEASSISTANT
HOMEASSISTANT_ENABLED=false
HOMEASSISTANT_NETWORK_MODE=
HOMEASSISTANT_PORT_8123=8123

### HTPCMANAGER
HTPCMANAGER_ENABLED=false
HTPCMANAGER_NETWORK_MODE=
HTPCMANAGER_PORT_8085=8085

### HYDRA2
HYDRA2_ENABLED=false
HYDRA2_NETWORK_MODE=
HYDRA2_PORT_5076=5076

### JACKETT
JACKETT_ENABLED=false
JACKETT_NETWORK_MODE=
JACKETT_PORT_9117=9117

### LAZYLIBRARIAN
LAZYLIBRARIAN_ENABLED=false
LAZYLIBRARIAN_NETWORK_MODE=
LAZYLIBRARIAN_PORT_5299=5299

### LETSENCRYPT
LETSENCRYPT_ENABLED=false
LETSENCRYPT_NETWORK_MODE=
LETSENCRYPT_PORT_443=443
LETSENCRYPT_PORT_80=80
LETSENCRYPT_DNSPLUGIN=
LETSENCRYPT_EMAIL=
LETSENCRYPT_EXTRA_DOMAINS=
LETSENCRYPT_ONLY_SUBDOMAINS=false
LETSENCRYPT_SUBDOMAINS=plex,portainer,www
LETSENCRYPT_URL=
LETSENCRYPT_VALIDATION=http

### LIDARR
LIDARR_ENABLED=false
LIDARR_NETWORK_MODE=
LIDARR_PORT_8686=8686

### LOGARR
LOGARR_ENABLED=false
LOGARR_NETWORK_MODE=
LOGARR_PORT_80=2802

### MARIADB
MARIADB_ENABLED=false
MARIADB_NETWORK_MODE=
MARIADB_MYSQL_ROOT_PASSWORD=
MARIADB_PORT_3306=3306

### MCMYADMIN2
MCMYADMIN2_ENABLED=false
MCMYADMIN2_NETWORK_MODE=
MCMYADMIN2_PORT_25565=25565
MCMYADMIN2_PORT_8080=8080

### MEDUSA
MEDUSA_ENABLED=false
MEDUSA_NETWORK_MODE=
MEDUSA_PORT_8081=8081

### MONITORR
MONITORR_ENABLED=false
MONITORR_NETWORK_MODE=
MONITORR_PORT_80=3803

### MUXIMUX
MUXIMUX_ENABLED=false
MUXIMUX_NETWORK_MODE=
MUXIMUX_PORT_80=4804

### MYLAR
MYLAR_ENABLED=false
MYLAR_NETWORK_MODE=
MYLAR_PORT_8090=8090

### NETDATA
NETDATA_ENABLED=false
NETDATA_NETWORK_MODE=
NETDATA_PORT_19999=19999

### NEXTCLOUD
NEXTCLOUD_ENABLED=false
NEXTCLOUD_NETWORK_MODE=
NEXTCLOUD_PORT_443=444
NEXTCLOUD_DATADIR=/mnt/nextcloud

### NZBGET
NZBGET_ENABLED=true
NZBGET_NETWORK_MODE=
NZBGET_PORT_6789=6789

### OMBI
OMBI_ENABLED=false
OMBI_NETWORK_MODE=
OMBI_PORT_3579=3579

### ORGANIZR
ORGANIZR_ENABLED=false
ORGANIZR_NETWORK_MODE=
ORGANIZR_PORT_80=5805

### PHPMYADMIN
PHPMYADMIN_ENABLED=false
PHPMYADMIN_NETWORK_MODE=
PHPMYADMIN_PORT_80=9809

### PIHOLE
PIHOLE_ENABLED=false
PIHOLE_NETWORK_MODE=
PIHOLE_PORT_443=446
PIHOLE_PORT_53=53
PIHOLE_PORT_67=67
PIHOLE_PORT_80=7807
PIHOLE_SERVERIP=192.168.x.x
PIHOLE_SERVERIPV6=
PIHOLE_WEBPASSWORD=

### PLEX
PLEX_ENABLED=false
PLEX_NETWORK_MODE=
PLEX_PORT_1900=1900
PLEX_PORT_3005=3005
PLEX_PORT_32400=32400
PLEX_PORT_32410=32410
PLEX_PORT_32412=32412
PLEX_PORT_32413=32413
PLEX_PORT_32414=32414
PLEX_PORT_32469=32469
PLEX_PORT_33400=33400
PLEX_PORT_5353=5353
PLEX_PORT_8324=8324
PLEX_ADVERTISE_IP=http://192.168.x.x:32400/
PLEX_CLAIM=claim-YYYYYYYYY
PLEX_TAG=latest
PLEX_TRANSCODEDIR=/tmp

### PLEXREQUESTS
PLEXREQUESTS_ENABLED=false
PLEXREQUESTS_NETWORK_MODE=
PLEXREQUESTS_PORT_3000=3000

### PORTAINER
PORTAINER_ENABLED=true
PORTAINER_NETWORK_MODE=
PORTAINER_PORT_9000=9000

### PORTAINERAGENT
PORTAINERAGENT_ENABLED=false
PORTAINERAGENT_NETWORK_MODE=
PORTAINERAGENT_PORT_9001=9001

### QBITTORRENT
QBITTORRENT_ENABLED=false
QBITTORRENT_NETWORK_MODE=
QBITTORRENT_PORT_6881=6881
QBITTORRENT_PORT_8080=8080

### RADARR
RADARR_ENABLED=false
RADARR_NETWORK_MODE=
RADARR_PORT_7878=7878

### RTORRENTVPN
RTORRENTVPN_ENABLED=false
RTORRENTVPN_NETWORK_MODE=
RTORRENTVPN_PORT_3000=3000
RTORRENTVPN_PORT_9080=9080
RTORRENTVPN_PORT_9443=9443
RTORRENTVPN_ENABLE_AUTODL_IRSSI=no
RTORRENTVPN_ENABLE_FLOOD=both

### RUTORRENT
RUTORRENT_ENABLED=false
RUTORRENT_NETWORK_MODE=
RUTORRENT_PORT_5000=5000
RUTORRENT_PORT_51413=51413
RUTORRENT_PORT_6881=6881
RUTORRENT_PORT_80=6806

### SABNZBD
SABNZBD_ENABLED=false
SABNZBD_NETWORK_MODE=
SABNZBD_PORT_8080=8080

### SABNZBDVPN
SABNZBDVPN_ENABLED=false
SABNZBDVPN_NETWORK_MODE=
SABNZBDVPN_PORT_8080=8080
SABNZBDVPN_PORT_8090=8090

### SICKRAGE
SICKRAGE_ENABLED=false
SICKRAGE_NETWORK_MODE=
SICKRAGE_PORT_8081=8081

### SONARR
SONARR_ENABLED=true
SONARR_NETWORK_MODE=
SONARR_PORT_8989=8989

### SYNCTHING
SYNCTHING_ENABLED=false
SYNCTHING_NETWORK_MODE=
SYNCTHING_PORT_21027=21027
SYNCTHING_PORT_22000=22000
SYNCTHING_PORT_8384=8384
SYNCTHING_SOURCEDIR=/mnt/syncthing

### TAUTULLI
TAUTULLI_ENABLED=false
TAUTULLI_NETWORK_MODE=
TAUTULLI_PORT_8181=8181

### THELOUNGE
THELOUNGE_ENABLED=false
THELOUNGE_NETWORK_MODE=
THELOUNGE_PORT_9000=9100

### TRANSMISSION
TRANSMISSION_ENABLED=false
TRANSMISSION_NETWORK_MODE=
TRANSMISSION_PORT_51413=51413
TRANSMISSION_PORT_9091=9091

### TRANSMISSIONVPN
TRANSMISSIONVPN_ENABLED=false
TRANSMISSIONVPN_NETWORK_MODE=
TRANSMISSIONVPN_PORT_9091=9091

### UBOOQUITY
UBOOQUITY_ENABLED=false
UBOOQUITY_NETWORK_MODE=
UBOOQUITY_PORT_2202=2202
UBOOQUITY_PORT_2203=2203
UBOOQUITY_FILESDIR=/mnt/ubooquity/files
UBOOQUITY_MAXMEM=512

### UNIFI
UNIFI_ENABLED=false
UNIFI_NETWORK_MODE=
UNIFI_PORT_10001=10001
UNIFI_PORT_3478=3478
UNIFI_PORT_6789=6789
UNIFI_PORT_7878=7878
UNIFI_PORT_8080=8080
UNIFI_PORT_8081=8081
UNIFI_PORT_8443=8443
UNIFI_PORT_8843=8843
UNIFI_PORT_8880=8880

### WATCHTOWER
WATCHTOWER_ENABLED=true

# END OF DEFAULT SETTINGS

**Comment by nemchik** [comment]
What do you see when you run `id -u` and `id -g`?

Your env looks fine. As long as those commands both return 1000 this might fix it
```
docker stop airdcpp
docker rm airdcpp
sudo ds -g
```

**Comment by malabrito** [comment]
both `id -u` and `id -g` return 1000.

`docker stop airdcpp
docker rm airdcpp
sudo ds -g`

running these commands haven't solved. The same error message is presented in the log. Can I send any other information for troubleshooting?

**Comment by nemchik** [comment]
This might be the fix (took a little googling):
```
docker stop airdcpp
docker run --rm -it --volumes-from airdcpp gangefors/airdcpp-webclient --add-user
```
You will be prompted to create a user and password, then run
```
docker start airdcpp
```

**Comment by malabrito** [comment]
that made it! Thanks !  :)

**Comment by nemchik** [comment]
I'll get that added to the wiki in a bit

**Comment by nemchik** [comment]
https://github.com/GhostWriters/DockSTARTer/wiki/AirDCpp
