### ISSUE TITLE
No server option with Plex

### ISSUE THREAD

**Issue by theetallest** [GhostWriters/DockSTARTer#323]
I just installed DS on my ubuntu system.  I like the ease of your product.  I have NO  server option when I install plex and it does not detect that I am even running one.     

Ubutnu 17.x 
it is VM

**Comment by nemchik** [comment]
Have a look at out Plex page in the wiki
https://github.com/GhostWriters/DockSTARTer/wiki/Plex
Make sure you do the claim process.

**Comment by nemchik** [comment]
Have a look at the Plex page on our wiki https://github.com/GhostWriters/DockSTARTer/wiki/Plex
This seems like you might just need to do the claim process.

**Comment by theetallest** [comment]
You are correct.   I did not realize there was that part I am up and running now.  I am not used to run docker so stuff I get to learn.    Thank you for responding back to me.

**Comment by nemchik** [comment]
No problem! Feel free to ask if you need anything else. We're also very active on discord (link in the readme)

**Comment by theetallest** [comment]
where is the readme with the Discord server?
