### ISSUE TITLE
Missing Apps

### ISSUE THREAD

**Issue by Roostlick** [GhostWriters/DockSTARTer#324]
Hi All

Hoping you can help, I've managed to get dockstarter installed on my raspberry pi 3+ model b. I've installed dependencies and rebooted, the issue is when I go to select the apps to install, Plex is missing and also all the VPN variants of the apps aren't there to select. Plus maybe more but they are the ones relevant to me. Anything obvious I've missed or done wrong?

Thanks!

**Comment by nemchik** [comment]
You'll notice in the folders that contain the yml files such as https://github.com/GhostWriters/DockSTARTer/tree/master/compose/.apps/bazarr there is an armhf file. That file indicates support for armhf CPU types, such as the Raspberry Pi. Unfortunately the Plex image we use (PMS Official) and the VPN download client images we use (Binhex) do not offer ARM CPU support at this time.

You can use https://github.com/GhostWriters/DockSTARTer/wiki/Overrides to add Plex using the `linuxserver/plex` image but we do not recommend running Plex on ARM CPUs.

You may be able to reach out to Binhex regarding his images and ask if he would be interested in maintaining ARM versions, but it would be up to him. We'd be happy to add those images to DockSTARTer if he were to release and support them.
