### ISSUE TITLE
Cockpit "Server Webui"

### ISSUE THREAD

**Issue by MrLordy** [GhostWriters/DockSTARTer#334]
Cockpit:

Information about it:
https://cockpit-project.org/

GitHub link:
https://github.com/cockpit-project/cockpit

Reason: 
Might be a great addition and alternative to webmin for managing a server

**Comment by nemchik** [comment]
I can't seem to find a docker package for this app. Is there a specific one you're using?

**Comment by nemchik** [comment]
After some research and discussion it seems this program is not currently available inside a Docker container. DockSTARTer's aim is to run apps in Docker with the cleanest and most minimal changes to the host system as possible. We may reopen this in the future if it becomes available in container form.
