### ISSUE TITLE
TTRSS "Tiny tiny rss - Rss reader"

### ISSUE THREAD

**Issue by MrLordy** [GhostWriters/DockSTARTer#335]
Tiny tiny rss:

Information about it:
https://tt-rss.org/

Git link:
https://git.tt-rss.org/git/tt-rss

Reason: 
Great self hosted rss reader / news reader to keep up with all rss/news . Rather then using and paying for others.

**Comment by nemchik** [comment]
Shouldn't be an issue. I'll add it to the list.

**Comment by nemchik** [comment]
Adding Notes
https://hub.docker.com/r/linuxserver/tt-rss
