### ISSUE TITLE
Unsupported architecture

### ISSUE THREAD

**Issue by arrudagates** [GhostWriters/DockSTARTer#336]
running the setup script gives me this

```
bash: line 10: BASH_SOURCE[0]: unbound variable
2018-10-28 17:17:50 [FATAL]      Unsupported architecture.
```

i am running a ubuntu server 16.04 i386

**Comment by arrudagates** [comment]
i don't really want to use DS, but atomic toolkit is not being supported anymore and nginx just refuse to work, i am lost, i really dont know what to do now, installing everything mannualy is a nightmare.

**Comment by nemchik** [comment]
Is it possible for you to run the x86_64 version of Ubuntu on your hardware?

**Comment by arrudagates** [comment]
Nope, it's a 775 socket with an Intel Pentium D

**Comment by nemchik** [comment]
Gotcha. Unfortunately the docker crowd focus mostly on x86_64 and some have ARM support, but i386 falls in the middle and are less common these days. You would have to get some new (or used) hardware to use the apps in docker.

**Comment by arrudagates** [comment]
atomic toolkit supported i386 but now they ask people to use DS, :(

**Comment by nemchik** [comment]
And I would love to support i386 in DS, actually DS could add i386 support very easily, but if the apps don't support i386 in docker then DS wouldn't be of much use.

A raspberry pi is only about $35, and there's plenty of used PCs or servers under $100.

**Comment by arrudagates** [comment]
thanks, will keep looking for some parts for a 64 bit system, my objective here is to build a server with all parts from recycling centers.

**Comment by nemchik** [comment]
Hope to see you back soon! Good luck with your build

**Comment by arrudagates** [comment]
thanks!
