### ISSUE TITLE
Missing proxy-conf files

### ISSUE THREAD

**Issue by rickster2** [GhostWriters/DockSTARTer#338]
There is no proxy-conf folder in the listed location from the Wiki document, and therefore none of the sample proxy-conf files to be used to set up the reverse proxy.

**To Reproduce**
1. Install container using dockstarter install script
2. Navigate to the .docker/config/letsencrypt/nginx/ folder and note that there is no /proxy-conf folder.

**Expected behavior**
Expect to see example proxy-conf files in the specified folder.

**System (please complete the following information):**
 - OS: Ubuntu x64
 - Version 18.04.1

**Additional context**
Confirmed that container is indeed pulled from linuxserver/letsencrypt:latest image.

**Comment by nemchik** [comment]
The documentation for the image is pretty good https://github.com/linuxserver/docker-letsencrypt you may also find guides about how to configure it around the web. We've discussed putting something together for our wiki, but have not yet had the time to complete it.
