### ISSUE TITLE
MakeMKV/Handbrake

### ISSUE THREAD

**Issue by mkono87** [GhostWriters/DockSTARTer#340]
Would be a great for DS with those using it on their media servers.

**Comment by mkono87** [comment]
Yes there is are docker images for each. They are encoding apps. Makemkv
takes bluray rips encode them to mkv. Handbrake is an all around media
encoder. That's why I thought it would good to have it available.

**Comment by JuezFenix** [comment]
> Is this a docker image you're asking for? I don't know much about these apps.

Take a look of those images: https://hub.docker.com/u/jlesage/

**Comment by nemchik** [comment]
I'm making my way through the list of requests and hope to have most of them added by the end of the month. I'll review this and see if there's an option that makes sense to include in the context of the project.

**Comment by nemchik** [comment]
I'm going to bump this to stay open. I haven't had a chance to look further into it yet.

**Comment by nemchik** [comment]
Sorry for the wait on these. I've got them added today.
