### ISSUE TITLE
NZBgetVPN

### ISSUE THREAD

**Issue by jarlave** [GhostWriters/DockSTARTer#347]
https://hub.docker.com/r/jshridha/docker-nzbgetvpn/ 
Would be nice to see nzbgetvpn added so usenet have an vpn option too

**Comment by nemchik** [comment]
FYI we do have binhex's sabnzbd+vpn already, so if you need Usenet+VPN right now you can use that.

I'll review the image you linked and likely get it added soon.

**Comment by jarlave** [comment]
Well haven't saw sabnzbd+vpn (maybe because I don't like sabnzbd, who knows) :D 
atm I'm fine with adding nzbgetvpn manually with an docker run command but for "one-click" it would be nice to see it inside DockSTARTer :)

**Comment by nemchik** [comment]
Quick question what CPU type are you running? Binhex currently doesn't support ARM.

**Comment by jarlave** [comment]
I'm running on amd64

**Comment by nemchik** [comment]
Ok good, the Sab+VPN is available now, and like I said I'll review the nzbget+VPN you linked and likely be adding it soon
