### ISSUE TITLE
Add to .env file or override?

### ISSUE THREAD

**Issue by sixshooterz** [GhostWriters/DockSTARTer#348]
I need to add some paths to the Universal Settings section.  How do I go about that?  Is there a .env override or do I add them to the docker-compose?

**Comment by nemchik** [comment]
I'm sorry for apparently not replying to this earlier! I had a nice big reply typed up and I guess didn't hit the green button.

You can add variables to the very bottom of `.env` but you don't have to use them at all if you don't want to. You can put the values directly into the yml.

**Comment by sixshooterz** [comment]
Awesome! I’m still playing with it. Opening the ticket was a little
premature because I hadn’t done enough on my end to figure it out and I’m
new to Docker so it’s a little overwhelming.

Thanks for the reply!
