### ISSUE TITLE
Node-red

### ISSUE THREAD

**Issue by kanutten** [GhostWriters/DockSTARTer#358]
Any chance of adding node-red to the list of applications?

https://hub.docker.com/r/cpswan/node-red/

**Comment by nemchik** [comment]
I'll review this and see if there's a Docker image that would be a good fit to add to DS

**Comment by kanutten** [comment]
great, i noticed i pasted the wrong url.
link to the official node-red docker:
https://hub.docker.com/r/nodered/node-red-docker/
Node-red is a great companion to Home-assistant,grafana, influxdb and a mqtt broker

**Comment by nemchik** [comment]
Keep this open

**Comment by nemchik** [comment]
Ok I've been reviewing this today (sorry it's taken me a while to get to) and I've noticed that it seems like they do not have documentation of a basic setup but rather they seem to imply that there are multiple ways that node-red could be run and it is very much up to the end user to decide how they want that done. I may be reading the docs wrong on first point. Secondly it looks like they are encouraging installing packages to the OS inside the docker container. I strongly hope I'm reading that wrong for many reasons.

In any case if you have a decent example of how this is meant to be setup that is at least mostly universal and would be usable by anyone who turned it on and decided to run with it I'd love to see an override example. If not I don't know that I'll be able to get this included in the main project although you are free to add it yourself using overrides or run it via other means.

**Comment by kanutten** [comment]
Hi, 
Thanks for the feedback.
Ive been running this override for some time now.
I dont now if the usable but its working for me 👍 
 
nodered:
    image: nodered/node-red-docker:v8
    container_name: nodered
    restart: unless-stopped
    user: ${PUID}:${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/nodered:/data
      - ${DOCKERSHAREDDIR}:/shared
    ports:
      - "1880:1880"

**Comment by nemchik** [comment]
Can anyone here try out `ds -u origin/nodered` ? You may need to remove any override you have in place. I'm basically using the template @kanutten posted above but not using the `v8` tag. Instead I've gone with `latest` but you CAN use an override to specify the version if you prefer.

Once I have some confirmation that this works I'll get it merged into master. PR incoming shortly as well to track.
