### ISSUE TITLE
Keep comments at end of .env file after running ds

### ISSUE THREAD

**Issue by sixshooterz** [GhostWriters/DockSTARTer#368]
**Describe the bug**
Any comments added with volumes at the end of the .env file (after # END OF DEFAULT SETTINGS) are removed upon running ds

**Expected behavior**
Keep any comments and formatting in the .env file that are added

**System (please complete the following information):**

- OS: Ubuntu
- Version: 18.04

**Comment by nemchik** [comment]
I've found a solution: comments must have an `=` in them to be kept.

```
# END OF DEFAULT SETTINGS
#comment with =
#= comment
# multiple ===
YOUTUBEDL_PORT_8080=8080
d2=q # random thing unused
```
Really I'd think the `#=` idea works well enough for you to setup whatever comments you need.
