### ISSUE TITLE
Port Conflicts

### ISSUE THREAD

**Issue by nemchik** [GhostWriters/DockSTARTer#380]
Warn when two apps use the same port and offer to change one or both

**Comment by nemchik** [comment]
Just to put this out in the open my current view on this is that when two apps use conflicting ports docker-compose will display an error and users will need to learn what that error means and how to resolve it. I'm not ruling out that DS could detect this ahead of time and try to gracefully handle the situation, but I'm leaning towards this type of situation being a learning experience for the end user. DS does a lot, but there's still some basic responsibility on the end user's part to understand certain things.

Much of that view comes from me not currently knowing the best way to handle port conflicts while still being informative to the end user and not just doing everything for them. Keeping people clueless isn't helpful.

**Comment by khostri** [comment]
I am not sure how Nginx works. But in the solution I was testing (media-docker) with Traefik, its handled.

Compose file doesn't contain ports: section, but only expose section to expose port internally
Traefik handles that even in case several same numbers are present I think, because it routes trafic from inside container to another one, not on external network.
Port conflict would be also there but only in case you need to publish port externally by ports: directive, outside of web gui acces.
fore example Minecraft port, MariaDB ports, Plex ports etc.

**Comment by nemchik** [comment]
Nginx itself doesn't really have much to do with the port conflicts. Nginx can proxy http and https communication (web interfaces) from the various apps but cannot (to my knowledge) proxy certain proprietary communication such as what might happen on the ports a torrent client uses to download. I don't believe Traefik can either.

As for `expose` vs `ports`:
Containers should be exposing their own ports in their `Dockerfile`. This is done to allow apps on the same docker bridge to communicate with each other (and other reasons). DockSTARTer does not make any efforts to `expose` any additional ports on the internal docker network (again this should be handled by the app container). We do however expose any ports used by the app to the default compose bridge network, which is a "user defined" network (in quotes because docker compose actually defines the network, not the user). This allows the user to access all relevant ports. The only real reason NOT to do this would be to reduce port conflicts and increase security. From a port conflict perspective, a the intention of this ticket would be to actually detect which ports are being mapped and compare them to ports mapped by all other apps and resolve conflicts, rather than just not map ports at all and rely on expose and proxying all ports. From a security perspective mapping all the ports shouldn't be an issue for any machine with a firewall, or any machine who's only network connection is to a network with a firewall. This fits the description of most home users and home servers. Cloud users may run the risk of mapped ports being openly accessible to the internet, but this is something they should account for when setting up anything on a cloud server. As an alternative users can use the letsencrypt container as their network mode by setting `<app>_NETWORK_MODE=container:letsencrypt` or `<app>_NETWORK_MODE=service:letsencrypt` which would then only expose ports to the letsencrypt container and any other containers also using letsencrypt as their network mode. This is a more advanced approach, but it would allow for the security benefit of not mapping all the ports an app would normally use. I personally do not recommend doing this because my opinion is that it is unnecessary.

In the case that I continue to pursue the idea of port conflict resolution it will be from the standpoint of detecting which ports are used by all apps and comparing those that use the same port and prompting to change one or the other. I am still on the fence about this idea and leaning away from it as I believe users do have at least some responsibility to learn how port mapping works and what to do to resolve the issue. I am not fully decided and will keep this open for discussion until a decision is made.

**Comment by mytvpro** [comment]
can a warning about port conflicts be displayed before user commits to changes?
