### ISSUE TITLE
Smokeping

### ISSUE THREAD

**Issue by nemchik** [GhostWriters/DockSTARTer#394]
https://hub.docker.com/r/linuxserver/smokeping/

**Comment by DblD** [comment]
https://github.com/20c/vaping

**Comment by nemchik** [comment]
Keep this

**Comment by nemchik** [comment]
@DblD I've looked into vaping and it does not appear to have an image available on docker hub. It looks like they have a dockerfile you can build yourself but they do not maintain their own premade image.
