### ISSUE TITLE
PIA - CA Montreal isn't in port forwarding list 

### ISSUE THREAD

**Issue by raoz0r** [GhostWriters/DockSTARTer#407]
I'm trying to use PIA Montreal servers but when i add the CA Montreal.ovpn file to openvpn i'm getting this message.

> [warn] PIA endpoint 'ca-montreal.privateinternetaccess.com' doesn't support port forwarding, DL/UL speeds will be slow
> [info] Please consider switching to an endpoint that does support port forwarding, shown below:-
> 
> 2018-12-02 02:26:52,250 DEBG 'start-script' stdout output:
> [info] ca-vancouver.privateinternetaccess.com (CA Vancouver)
> [info] ca-toronto.privateinternetaccess.com (CA Toronto)
> [info] ca.privateinternetaccess.com (CA Montreal)

What should i do to fix this? Changing the ovpn file address ca.privateinternetaccess is enough?

**Comment by nemchik** [comment]
I'm not an expert on pia, but I would think they have an ovpn file premade for each location and you should use the correct file for the location you're trying to use.

This issue isn't directly an issue with DockSTARTer, so I'm going to close it, but feel free to continue to add replies and I'll try to help as much as I can. You can also join our discord chat (badge in the readme), there are people on an hours of the day when I might not be around and some may have more experience with pia than me.
