### ISSUE TITLE
curl: (22) The requested URL returned error: 403 Forbidden

### ISSUE THREAD

**Issue by Shailendraxyz** [GhostWriters/DockSTARTer#409]
**Describe the bug**
Hi,

I do get this error when installing:
[root@vm ~]# bash -c "$(curl -fsSL https://get.dockstarter.com)"
curl: (22) The requested URL returned error: 403 Forbidden

What to do ?

**Comment by nemchik** [comment]
Can you visit https://get.dockstarter.com/ in a web browser?

**Comment by Shailendraxyz** [comment]
Yes,

it redirects to : https://raw.githubusercontent.com/GhostWriters/DockSTARTer/master/main.sh

**Comment by nemchik** [comment]
Would it be possible for you to login as a standard user?

**Comment by nemchik** [comment]
Try
```bash
git clone https://github.com/GhostWriters/DockSTARTer "~/.docker" #no sudo
sudo bash ~/.docker/main.sh
```

That might get things working but it sounds like you might have a more serious issue unrelated to DockSTARTer. What OS are you using and what version of the OS?

**Comment by Shailendraxyz** [comment]
I am using centos 7

**Comment by nemchik** [comment]
I'm working on testing a possible fix for the issue with CentOS. I've heard it before but I don't have a CentOS VM around to confirm if the fix will work. I'll let you know once I put the fix in place and you can try again.

**Comment by Shailendraxyz** [comment]
Ok thanks

**Comment by Shailendraxyz** [comment]
i tried to reinstall the vps with debian 9, and now it is installing :)

can you also add these apps to in your list 
- azuracast : https://github.com/AzuraCast/AzuraCast
-invoiceninja : https://github.com/invoiceninja/invoiceninja

**Comment by nemchik** [comment]
Please open individual requests for each app and they will be considered. I will still investigate the issue with CentOS but I may not have a working solution today.

**Comment by nemchik** [comment]
Can you run `sudo ds -i` and reboot at the end when prompted?

**Comment by Shailendraxyz** [comment]
amit@vm:~$ sudo ds -i
[sudo] password for amit:
2018-12-04 15:37:54 [INFO]       apt package manager detected.
2018-12-04 15:37:54 [INFO]       Removing old Docker packages.
2018-12-04 15:37:54 [INFO]       Updating repositories.
2018-12-04 15:37:56 [INFO]       Upgrading packages.
2018-12-04 15:37:57 [INFO]       Installing dependencies.
2018-12-04 15:37:57 [INFO]       Removing unused packages.
2018-12-04 15:37:57 [INFO]       Cleaning up package cache.
2018-12-04 15:37:58 [INFO]       Installing latest docker. Please be patient, this will take a while.
2018-12-04 15:38:23 [INFO]       Installing docker machine completion.
2018-12-04 15:38:23 [INFO]       Creating docker group.
2018-12-04 15:38:23 [INFO]       Adding amit to docker group.
2018-12-04 15:38:23 [INFO]       Systemd detected. Enabling docker service.
2018-12-04 15:38:23 [FATAL]      Failed to start docker service.

**Comment by nemchik** [comment]
try
```bash
sudo systemctl stop docker
sudo systemctl start docker
```

**Comment by Shailendraxyz** [comment]
amit@vm:~$ sudo systemctl stop docker
amit@vm:~$ sudo systemctl start docker
A dependency job for docker.service failed. See 'journalctl -xe' for details.


amit@vm:~$ sudo journalctl -xe
-- Unit containerd.service has failed.
--
-- The result is failed.
Dec 04 15:43:42 vm systemd[1]: Dependency failed for Docker Application Containe
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit docker.service has failed.
--
-- The result is dependency.
Dec 04 15:43:42 vm systemd[1]: docker.service: Job docker.service/start failed w
Dec 04 15:43:42 vm systemd[1]: containerd.service: Unit entered failed state.
Dec 04 15:43:42 vm systemd[1]: containerd.service: Failed with result 'exit-code
Dec 04 15:43:42 vm sudo[227]: pam_unix(sudo:session): session closed for user ro
Dec 04 15:43:42 vm systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit docker.service has finished shutting down.
Dec 04 15:44:10 vm sudo[241]:     amit : TTY=pts/0 ; PWD=/home/amit ; USER=root
Dec 04 15:44:10 vm sudo[241]: pam_unix(sudo:session): session opened for user ro
lines 628-650/650 (END)
-- Unit containerd.service has failed.
--
-- The result is failed.
Dec 04 15:43:42 vm systemd[1]: Dependency failed for Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit docker.service has failed.
--
-- The result is dependency.
Dec 04 15:43:42 vm systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Dec 04 15:43:42 vm systemd[1]: containerd.service: Unit entered failed state.
Dec 04 15:43:42 vm systemd[1]: containerd.service: Failed with result 'exit-code'.
Dec 04 15:43:42 vm sudo[227]: pam_unix(sudo:session): session closed for user root
Dec 04 15:43:42 vm systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit docker.service has finished shutting down.
Dec 04 15:44:10 vm sudo[241]:     amit : TTY=pts/0 ; PWD=/home/amit ; USER=root ; COMMAND=/bin/journalctl -xe
Dec 04 15:44:10 vm sudo[241]: pam_unix(sudo:session): session opened for user root by amit(uid=0)

**Comment by nemchik** [comment]
Try rebooting and then run `sudo ds -i` again.

If that doesn't work you'll need to figure out why the docker service won't start. We're using the official https://get.docker.com/ script which has instructions right up top
```bash
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
```
Those should be run as root or with sudo. They do not cover the service, which is done with these commands (the first one was already run by DS successfully and DS logs did not show an error for it failing)
```bash
systemctl enable docker
systemctl stop docker
systemctl start docker
```

You may get quicker responses on our discord chat https://discord.gg/YFyJpmH
