### ISSUE TITLE
Add PyLoad 

### ISSUE THREAD

**Issue by Veronit** [GhostWriters/DockSTARTer#415]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add PyLoad to DockStarter

**Describe alternatives you've considered**
An alternative to Jdownloader2 also suggested here. 

**Additional context**
Works great on low powered machines like RPIs.
From their github page (https://github.com/pyload/pyload): "Free and Open Source download manager written in Pure Python and designed to be extremely lightweight, fully customizable and remotely manageable"

Lot of images available: https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=pyload&starCount=0
Haven't used any of these, but this one is the most popular with 1M pulls: https://hub.docker.com/r/writl/pyload/

**Comment by karl0ss** [comment]
https://github.com/GhostWriters/DockSTARTer/pull/450
