### ISSUE TITLE
Pihole logs shows deprecation notice

### ISSUE THREAD

**Issue by Veronit** [GhostWriters/DockSTARTer#417]
**Describe the bug**
Pihole logs shows deprecation notice

**To Reproduce**
1. Start pihole
2. Open pihole logs
3. Logs show error :

:: ::: ::: ::: ::: ::: ::: ::: ::: :::

:: Image moved / deprecation notice
::    OLD IMAGE : diginc/pi-hole
::    NEW IMAGE : pihole/pihole
:: In order to get the latest updates 
:: please update your image references

Full log: https://pastebin.com/aXVmSV8m

I also cannot access the admin page of Pihole, so I think it's not starting correctly.

**Expected behavior**
No error

**System (please complete the following information):**

- OS: Rasbian
- Version 9

**Comment by Veronit** [comment]
Was able to get access to admin page by fixing this error:
[?] DNS resolution is currently unavailable

Found this: https://github.com/pi-hole/docker-pi-hole/issues/208
And after using suggested workaround: https://github.com/pi-hole/docker-pi-hole/issues/208#issuecomment-360769032

Pihole started and I can now access the admin page.

This is the log after editing the resolv.conf: https://pastebin.com/hbCwcLS1

**Comment by nemchik** [comment]
Pi-hole tags their images a bit weird, can you try something for me?
Create/edit `~/.docker/compose/docker-compose.override.yml`
```yaml
services:
  pihole:
    image: pihole/pihole
```
Then `sudo ds -c up`

**Comment by Veronit** [comment]
Ofcourse.
Received this error at the end of running sudo ds -c up:
ERROR: Version mismatch: file ./docker-compose.yml specifies version 3.4 but extension file ./docker-compose.override.yml uses version 1
2018-12-05 19:54:31 [FATAL]      Docker Compose failed.

**Comment by nemchik** [comment]
wow, i forgot this
```yaml
version: "3.4"
services:
  pihole:
    image: pihole/pihole:v4.0_armhf
```

**Comment by nemchik** [comment]
Also FYI i was able to run pihole without editing the resolv.conf
