### ISSUE TITLE
Add Blackhole tool for Premiumize.me

### ISSUE THREAD

**Issue by d3adlizard** [GhostWriters/DockSTARTer#425]
I'd like to be able for Premiumize.me to be used with your setup. Premiumize is a torrent cloud provider and is similar to common debrid services. Often torrents are cached making downloads much faster for users.

I would love it if the GitHub project like this black hole project for premiumize was implemented in your auto configuration wizard. https://github.com/piejanssens/premiumizer

I had attempted to use a few 3rd party docker solutions which also use this project, but having the wizard help with the setup would be amazing and make it much simpler for new comers.

**Comment by d3adlizard** [comment]
So, i saw this was added on the todo list, but today its showing as being marked stale? Is just the issue being marked stale? or does this mean this feature will not be implemented?

**Comment by nemchik** [comment]
Replying to stale bot (which you did) keeps it from closing the issue for being inactive.

**Comment by nemchik** [comment]
#637 needs testing if you wouldn't mind confirming it works for you.

**Comment by nemchik** [comment]
FYI I think pyload supports Premiumize.me but I don't know if it's in the same capacity.
