### ISSUE TITLE
Configure Letsencrypte

### ISSUE THREAD

**Issue by bentux** [GhostWriters/DockSTARTer#428]
Hi,
It's more a question than a bug.
Wath is the right configuration to use Nexcloud with ssl (Letsencrypt)

Thanks for advises

**Comment by nemchik** [comment]
Please review the documentation here:

https://github.com/linuxserver/docker-letsencrypt/blob/master/README.md
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_readme
https://github.com/linuxserver/reverse-proxy-confs/blob/master/nextcloud.subdomain.conf.sample
https://github.com/linuxserver/reverse-proxy-confs/blob/master/nextcloud.subfolder.conf.sample

Feel free to join our discord server for help https://discord.gg/YFyJpmH
LSIO also has a discord server where people might be able to assist https://discord.gg/YWrKVTn

**Comment by bentux** [comment]
Hi nemchik and thanks for answer.
It doesn't work yet so may be in discord...
