### ISSUE TITLE
Add Wallabag

### ISSUE THREAD

**Issue by XabiAlonso86** [GhostWriters/DockSTARTer#438]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add Wallabag to DockStarter

**Describe alternatives you've considered**

**Additional context**
wallabag is a self hostable application for saving web pages. Unlike other services, wallabag is free (as in freedom) and open source.
With this application you will not miss content anymore. Click, save, read it when you want. It saves the content you select so that you can read it when you have time.
I think it would be a great addition to DockStarter.

Docker Official repo [here](https://github.com/wallabag/docker)

**Comment by nemchik** [comment]
We can keep this open. Sorry I haven't been able to get around to it yet.

**Comment by nemchik** [comment]
So I've finaly got around to actually reading into how to add this and the documentation about what volumes are needed seems a little all over the place. Do you have any personal experience running this container and could maybe point me in the right direction?
