### ISSUE TITLE
Docker compose timeout

### ISSUE THREAD

**Issue by khostri** [GhostWriters/DockSTARTer#443]
**Describe the bug**
With many container Docker Compse timeout happens

**To Reproduce**
Use many containers with not so fast connection

**Expected behavior**
Dockstarter should run even on standard connetions, so timeout value should be set properly

Only global Environment value set is needed:
COMPOSE_HTTP_TIMEOUT=180

**System (please complete the following information):**

Ubuntu Minimal 18.04 on Synology host (as VM)

**Comment by nemchik** [comment]
I'll look into this. I haven't seen an exact example of how to implement it yet, but this is a common issue so I think it's worth investigating.

**Comment by khostri** [comment]
Its easy - you just add one line to .env file:

COMPOSE_HTTP_TIMEOUT=180
