### ISSUE TITLE
Nzbgetvpn OpenVPN config

### ISSUE THREAD

**Issue by khostri** [GhostWriters/DockSTARTer#444]
**Is your feature request related to a problem? Please describe.**
As "one click solution" it would be great if Nzbgetvpn had *.ovpn configs present as with Transmission. 

**Describe the solution you'd like**
Its probably request for container maintainer, but it would be great to have it done by Dockstarter. I think it would be possible in case of Nzbgetvpn selected (I am not sure, but probably same thing applies for Delugevpn) that *.ovpn configs are copied into config folder.
For example:
1) starting docker-compose up -d nzbgetvpn
2) copy *.ovpn files into created folder
3) docker stop nzbgetvpn
4) use docker-compose in current way

**Describe alternatives you've considered**
Current situation with manual config files copy. It just doesnt work after starting containers but you need to know what to do based on logs.

**Comment by nemchik** [comment]
I agree this is more of a request for the image maintainer. There are an infinite amount of potential ovpn files and VPN containers can be created by the user using overrides that may use different folder structures for volume mapping, so I think the best we can do is better documentation in our wiki. We've got a page (publicly editable) but it may lack the information about specifically setting up these ovpn files.

**Comment by nemchik** [comment]
I'm going to close this, but discussion will remain open in case there is some relevant point or idea that I may have overlooked and should consider.
