### ISSUE TITLE
Add Jellyfin

### ISSUE THREAD

**Issue by Eric-sson** [GhostWriters/DockSTARTer#456]
Would it be possible to add Jellyfin?

After the news that Emby server is now proprietary, with only some plugins being open source, a free software fork of Emby was created, called Jellyfin.

https://hub.docker.com/r/jellyfin/jellyfin/

**Comment by nemchik** [comment]
I'll have a look at this.

**Comment by nemchik** [comment]
We'll get to this. Keep it open.

**Comment by nemchik** [comment]
#638 needs testing if you wouldn't mind confirming it works for you.
