### ISSUE TITLE
[Feature request] Add UNMS controller to Dockstarter

### ISSUE THREAD

**Issue by 1985kasper** [GhostWriters/DockSTARTer#458]
I have several ubiquiti appliances of the Edge type. Ubiquiti has launched their UNMS controller to monitor and control these devices:
https://unms.com
They provide a docker container and it would be really nice and cool to add this to dockstarter. 
Since it comes with nginx and letsencrypt and needs port 80 and 443 a default installation might conflict with a existing dockstarter based setup.

**Comment by nemchik** [comment]
Reference
https://hub.docker.com/r/oznu/unms
https://hub.docker.com/r/ubnt/unms

**Comment by nemchik** [comment]
Bump to keep open.

**Comment by nemchik** [comment]
#639 needs testing if you wouldn't mind confirming it works for you.
