### ISSUE TITLE
Failed to check latest available yq version

### ISSUE THREAD

**Issue by karl0ss** [GhostWriters/DockSTARTer#463]
Am unable to install any apps today due to failing to check yq version, I have run the curl request in terminal and this is the resposne..

```
{
  "message": "API rate limit exceeded for xx.x.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by karl0ss** [comment]
This this might be a GitHub issue, it seemed to resolve during today, and has now come back, going to close this..

**Comment by kazo0** [comment]
Seem to be experiencing this right now, waited about an hour and still getting errors. Am I better off waiting until tomorrow?

**Comment by nemchik** [comment]
Check https://api.github.com/rate_limit
If your rate (at the bottom) has 0 remaining you'll have to wait for it to reset.

Also it looks like aarch64 binaries weren't posted for the recent update today https://github.com/mikefarah/yq/releases
I'll open an issue on their repo to ask about this. As a workaround if you're using an aarch64 CPU you can run `curl -L "https://github.com/mikefarah/yq/releases/download/2.3.0/yq_linux_arm" -o /usr/local/bin/yq` to install the compatible armhf binary for now.

**Comment by nemchik** [comment]
FYI after actually looking back on DS method of installing yq we use the arm binary for both armhf and aarch64 and have never used the arm64 specific binary because it didn't used to be available when we first made the install script.
