### ISSUE TITLE
resilio

### ISSUE THREAD

**Issue by nemchik** [GhostWriters/DockSTARTer#467]
https://hub.docker.com/r/resilio/sync/
https://hub.docker.com/r/linuxserver/resilio-sync

**Comment by mcaron1234** [comment]
I was thinking of doing a PR for this, from what I can tell the LSIO container looks to be the best choice because its multi-arch support. Have you put any thought into this?

**Comment by nemchik** [comment]
I would agree that the lsio image is the right choice for this.
