### ISSUE TITLE
ds install fails on centos 7.6 during yq install 

### ISSUE THREAD

**Issue by stevenflang** [GhostWriters/DockSTARTer#469]
Initial install on CentOS Linux release 7.6.1810 (Core)

sudo] password for dockeruser:
2019-01-11 17:01:25 [INFO]       yum package manager detected.
2019-01-11 17:01:25 [INFO]       Removing old Docker packages.
..
..
2019-01-11 17:02:48 [INFO]       Installing docker-compose completion.
2019-01-11 17:02:49 [INFO]       Installing latest yq.
2019-01-11 17:02:50 [FATAL]      Failed to install the latest yq.

Added set -x in install_yq.sh
-------Cut------------
-------Cut-------------

2019-01-11 17:13:33 [INFO]       Installing docker-compose completion.
+ local AVAILABLE_YQ
++ curl -H '' -s https://api.github.com/repos/mikefarah/yq/releases/latest
++ grep -Po '"tag_name": "[Vv]?\K.*?(?=")'
+ AVAILABLE_YQ=2.2.1
+ local INSTALLED_YQ
++ yq --version
++ sed -E 's/.* version ([^,]*)(, build .*)?/\1/'
++ true
+ INSTALLED_YQ=
+ local FORCE
+ FORCE=force
+ [[ 2.2.1 != '' ]]
+ info 'Installing latest yq.'
+ tee -a /tmp/dockstarter.log
++ date '+%F %T'
+ echo -e '\e[0m2019-01-11 17:13:34 \e[34m[INFO]\e[0m       Installing latest yq.\e[0m'
2019-01-11 17:13:34 [INFO]       Installing latest yq.
+ [[ x86_64 == \a\a\r\c\h\6\4 ]]
+ [[ x86_64 == \a\r\m\v\7\l ]]
+ [[ x86_64 == \x\8\6\_\6\4 ]]
+ curl -H '' -L https://github.com/mikefarah/yq/releases/download/2.2.1/yq_linux_amd64 -o /usr/local/bin/yq
+ chmod +x /usr/local/bin/yq
+ local UPDATED_YQ
++ yq --version
++ sed -E 's/.* version ([^,]*)(, build .*)?/\1/'
++ true
+ UPDATED_YQ=
+ [[ 2.2.1 != '' ]]
+ fatal 'Failed to install the latest yq.'
+ tee -a /tmp/dockstarter.log
++ date '+%F %T'
+ echo -e '\e[0m2019-01-11 17:13:35 \e[31m[FATAL]\e[0m      Failed to install the latest yq.\e[0m'
2019-01-11 17:13:35 [FATAL]      Failed to install the latest yq.
+ exit 1
+ cleanup
+ [[ /home/dockeruser/.docker == \/\h\o\m\e\/\d\o\c\k\e\r\u\s\e\r\/\.\d\o\c\k\e\r ]]
+ chmod +x /home/dockeruser/.docker/main.sh
+ [[ '' == true ]]
------------Cut-------------------

Problem is this line:
-------Cut------------
+ local UPDATED_YQ
++ yq --version   <- 
++ sed -E 's/.* version ([^,]*)(, build .*)?/\1/'
++ true
-------Cut------------

yq exists and has just been placed in /usr/local/bin

/root# ls -al /usr/local/bin/yq
-rwxr-xr-x. 1 root root 5406999 Jan 11 17:13 /usr/local/bin/yq

This appears to be the expected version. 
/root# yq --version
yq version 2.2.1

root env has a path to /usr/local/bin and so does the user but problem appears to be env related.

* Suggest we use the full path to yq to get the version especially since we know where we put it. 

This is what is causing the env problem. 

On at least Centos 7,  
------Cut---------
/root# cat /etc/sudoers | grep secure_path
Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin
------Cut---------

On Unbuntu 18 it looks like this .. 
-----Cut----------
root@dockerstarter:~# cat /etc/sudoers | grep secure_path
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
------Cut---------

Maybe the above is the actual reason for not finding yq using sudo .. 
I think though to save a user several hours of searching we might consider using the full path to check the yq version. 

---------Cut---------- 
install_yq.sh

 UPDATED_YQ=$( (/usr/local/bin/yq --version 2> /dev/null || true) | sed -E 's/.* version ([^,]*)(, build .*)?/\1/')
--------Cut----------

The above seems to work after adding the full path !

Thank you ..

**Comment by nemchik** [comment]
Thank you for the very detailed report, this is perfect to help me resolve this issue!

`docker-compose` is installed the same way to the same location, so I wonder if maybe we should be adding that location to the path. Your right that using the full path will work and I'll consider that as well, but in leaning towards trying to add the location to the path unless that's out of the question for some reason.

**Comment by nemchik** [comment]
Are your comfortable with testing? I've got #471 with changes that I think should solve the issue.

**Comment by nemchik** [comment]
```bash
cd ~/.docker
git fetch -p
git reset --hard origin/local-symlink
git pull
sudo ds -e
sudo ds -i
 ```
That last command should attempt the install, including yq.

**Comment by nemchik** [comment]
BTW for the curious, I'm not adding anything to the path, nor am I changing the install location. Instead (per the recommendation in the `docker-compose` installation documentation) I'm adding a symbolic link for the binaries to `/use/bin/` which is in the path mentioned above. Since this is recommended by docker for compose and we install yq the same way this will keep new installations clean and not break compatibility with previous installations.
