### ISSUE TITLE
Airsonic not loading on Ubuntu 18.04

### ISSUE THREAD

**Issue by artiedarrell** [GhostWriters/DockSTARTer#470]
Not sure what the issue is.  It appears to be running in Docker, but browsing to x.x.x.x:4040 shows a blank page.

![image](https://user-images.githubusercontent.com/17505190/51065781-0a85b000-15dd-11e9-8d0a-138a20a4fd48.png)

**Comment by nemchik** [comment]
Try http://x.x.x.x:4040/airsonic/

**Comment by artiedarrell** [comment]
haha sigh... thanks man
