### ISSUE TITLE
Add Phlex to list of apps

### ISSUE THREAD

**Issue by mattgphoto** [GhostWriters/DockSTARTer#472]
**Is your feature request related to a problem? Please describe.**
Nope!

**Describe the solution you'd like**
Add Phlex to the list of applications available in DS: https://hub.docker.com/r/digitalhigh/phlex

**Describe alternatives you've considered**
Don't know of any for home automation/voice commands/Google Assistant Integration

**Comment by nemchik** [comment]
Wait, what does this do?

**Comment by mattgphoto** [comment]
:-) Allows for Google Assistant interface to plex: https://github.com/d8ahazard/Phlex/wiki/Introduction

**Comment by nemchik** [comment]
Gotcha. I'm a little bothered (my OCD) by there being kind of two names.

**Comment by mattgphoto** [comment]
Ah, Phlex and Plex, you mean?

**Comment by nemchik** [comment]
No, it says on the wiki that it's also Flex TV and that's also referenced on their docker page.

**Comment by mattgphoto** [comment]
Ah, I see the issue. Two names, with yet another takedown notice from Google and no foreseeable future, just close this out. My apologies!
