### ISSUE TITLE
Add putio-automator

### ISSUE THREAD

**Issue by ismay** [GhostWriters/DockSTARTer#478]
https://github.com/datashaman/putio-automator#docker might be nice for this project. Similar to https://github.com/GhostWriters/DockSTARTer/issues/425, but for put.io. Allows for a blackhole for torrents and retrieves the files to the same folder once downloaded.

**Comment by nemchik** [comment]
Commenting to keep this open.

**Comment by nemchik** [comment]
Keep again. Sorry for the delay. Have a few other things in the works.

**Comment by nemchik** [comment]
Keep this open
