### ISSUE TITLE
how to override ?

### ISSUE THREAD

**Issue by AkgunFatih** [GhostWriters/DockSTARTer#487]
i cant find this path and file anywhere ? `.docker/compose/.env`
where is this file how can i overidde settings

**Comment by nemchik** [comment]
The file is located at `~/.docker/compose/.env` or `/home/your_user/.docker/compose/.env` and anything you can't change by variables in that file can be adjusted with overrides as documented here https://github.com/GhostWriters/DockSTARTer/wiki/Overrides we have a number of override examples on our discord server (chat badge in the readme).

After making changes to the .env file (or the override file) you need to run `sudo ds -c up` to apply the changes.

**Comment by AkgunFatih** [comment]
Thanks for quick response

**Comment by AkgunFatih** [comment]
Hi, i don't want to reopen this issue but i keep getting lost because now i can't find this folder `.docker/config/letsencrypt/nginx/proxy-confs`

**Comment by AkgunFatih** [comment]
whew, so ez.. DockSTARTer is such a time saver ❤️
