### ISSUE TITLE
bug report:I have no "install-docker.sh" file in the .docker folder per the wiki setup instructions

### ISSUE THREAD

**Issue by jmcmike1** [GhostWriters/DockSTARTer#49]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Debian]

**Additional context**

**Comment by nemchik** [comment]
Sorry, we JUST changed this a few hours ago today and the wiki has not yet been updated. Give me a few minutes and I will make the appropriate changes.

**Comment by jmcmike1** [comment]
thanks for the quick reply. I tried the 'main.sh' script but nothing
happened

**Comment by nemchik** [comment]
The wiki has been updated. Please check it out and let me know if you get everything working!

**Comment by jmcmike1** [comment]
That's better!😀
thx
mike
