### ISSUE TITLE
[Fedora] Failed to install dependencies from yum

### ISSUE THREAD

**Issue by UnR34L** [GhostWriters/DockSTARTer#490]
**Describe the bug**
It looks like a script thinks its on a CentOS system (yum) when I'm trying to run it on Fedora 29 Server

**To Reproduce**

Fresh Fedora 29 Server install, nothing else installed
Run these commands:

```
sudo dnf install curl git
bash -c "$(curl -fsSL https://get.dockstarter.com)"
```

Everything looks normal then I get these two lines.

```
[FATAL]      Failed to install dependencies from yum.
[FATAL]      Failed first run install, please reboot and try again.
```

**Comment by nemchik** [comment]
Try running `command -v dnf`

That's how DS determines which package manager you have.

**Comment by UnR34L** [comment]
I got `/usr/bin/dnf`

When I first ran it, it looks like it detected dnf correctly, but when it tries to install compose that's when it mentions yum.

![image](https://user-images.githubusercontent.com/5008396/51421637-ddb33900-1b98-11e9-83e3-9fd284699874.png)

**Comment by UnR34L** [comment]
Thanks, I can atleast get compose working now, it still gives errors with -i

**Comment by UnR34L** [comment]
https://github.com/GhostWriters/DockSTARTer/pull/493

Fired up a new VM, installs compose successfully, fixed!

```
[unr34l@fedora-vm ~]$ docker-compose --version
docker-compose version 1.23.2, build 1110ad0
```

**Comment by nemchik** [comment]
Just to confirm are you saying you ran the commands from #493 and that fixed the issue? Or you just ran the plain install and it worked without the fixes from #493 ?

**Comment by UnR34L** [comment]
I ran the commands from https://github.com/GhostWriters/DockSTARTer/pull/493

I tried it in a VM because I don't want to mess with my production server too much, when you do the pull I'll update and test on that as well, but it worked fine in a VM with those commands.

**Comment by nemchik** [comment]
Awesome! Thank you very much for testing!
