### ISSUE TITLE
Default deluge password does not seem to be "deluge"

### ISSUE THREAD

**Issue by ismay** [GhostWriters/DockSTARTer#492]
**Describe the bug**

In the deluge docs the default password is said to be `deluge`. However, when installing deluge with dockstarter and logging in through the web-ui on port 8112 the default password (i.e. `deluge`) does not work.

**To Reproduce**

1. On a fresh deluge install go to <server>:8112
2. Enter `deluge` as the password
3. See error

**Expected behavior**
I expect the default password to be `deluge`, or for the actual password to be mentioned in the dockstarter docs.

**System (please complete the following information):**

- Ubuntu 18.04.1 LTS

**Additional context**

I fixed this for myself like so (might contain unnecessary steps, but it worked in resetting the password to the default, `deluge`):

- `docker stop deluge`
- `cd ~/.docker/config/deluge`
- `rm auth session.state web.conf web.conf~`
- `docker start deluge`

**Comment by nemchik** [comment]
I don't actually know what to do about this one. Deluge creates all those files on its own, it's not specific to the docker container, so my only thought is asking Deluge themselves to better handle creating the default password when no auth file is found. Aside from that the general method of troubleshooting any container that you just started using and have not really configured is to wipe the config folder and restart the container which would likely have resolved this issue.

**Comment by ismay** [comment]
Yeah if this is an upstream issue then indeed there is not much that dockstarter can do about it.

> Aside from that the general method of troubleshooting any container that you just started using and have not really configured is to wipe the config folder and restart the container which would likely have resolved this issue

For me this wasn’t immediately clear. I deleted some of the config files and reset the password that way, but maybe it’d be nice to note this for users.

Though I don’t know if others are experiencing this as well. At the very least this issue now documents the problem :)!

**Comment by nemchik** [comment]
I will see about adding what I had said about troubleshooting to the wiki, but that option is not usually a first step (just one that we eventually get to). With proper warnings it would be good to have documented.

**Comment by ismay** [comment]
Sounds good, thanks!

**Comment by ismay** [comment]
So I think I figured out what's going on here. I think the problem's not with the default deluge password. That's probably `deluge` like it says in the docs. I noticed that the cookies are conflicting:

<img width="301" alt="screenshot 2019-01-27 at 21 40 11" src="https://user-images.githubusercontent.com/7355199/51806611-285d4100-227c-11e9-8dd3-f8b896551cfa.png">

As you can see two different services are both storing cookies under _session_id, and as all services are served from the same domain deluge is using the value from the wrong cookie. After deleting all cookies for the domain and trying to log in again it works.

**Comment by nemchik** [comment]
Nice!

**Comment by ismay** [comment]
At least I think that that's what it is. I might be wrong, but removing the cookies at reliably fixes the problem (at least temporarily).

**Comment by nemchik** [comment]
I'm going to close this. Feel free to reopen it if you still need help with this.
