### ISSUE TITLE
sudo ds error !

### ISSUE THREAD

**Issue by AkgunFatih** [GhostWriters/DockSTARTer#497]
after trying to setup a failed pi-hole installation i decided to uninstall pi-hole

but now every time i run the command `sudo ds`
i keep getting this error

```bash
2019-01-23 16:44:55 [WARNING]    Attempting to clone DockSTARTer repo to /home/docky/.docker location.
fatal: destination path '/home/docky/.docker' already exists and is not an empty directory.
2019-01-23 16:44:55 [FATAL]      Failed to clone DockSTARTer repo to /home/docky/.docker location.
```

**Comment by nemchik** [comment]
Copy your `/home/docky/.docker/compose/.env` file to a safe location.
If you have a `/home/docky/.docker/compose/docker-compose.override.yml` file copy that to a safe location as well.
Copy your `/home/docky/.docker/config/` folder to a safe location.

Run `sudo rm -rf /home/docky/.docker` and then `bash -c "$(curl -fsSL https://get.dockstarter.com)"` and reboot at the end when prompted.

Copy your files and folders back from their safe locations to their original locations and then run `sudo ds -e` and then `sudo ds -c up`

**Comment by AkgunFatih** [comment]
Thank you for your help it is working fine now :)

**Comment by nemchik** [comment]
Any time, sorry for the trouble!
