### ISSUE TITLE
Add Algo VPN

### ISSUE THREAD

**Issue by AkgunFatih** [GhostWriters/DockSTARTer#501]
https://github.com/trailofbits/algo

**Comment by AkgunFatih** [comment]
> Is there a docker container for this? The documentation looks more like something you'd setup on your host outside of docker.

Hmm looks like algo can't be used in a docker https://github.com/trailofbits/algo/blob/master/docs/deploy-to-unsupported-cloud.md

**Comment by nemchik** [comment]
Because of this I don't think we'll be able to add this directly to DS.
