### ISSUE TITLE
Add Unmanic

### ISSUE THREAD

**Issue by Tharic99** [GhostWriters/DockSTARTer#503]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Unmanic is a library optimizer  for optimizing your video library to a single format. It's still in beta stage, so this is more to keep an eye on it as opposed to adding it to DS currently.

https://github.com/Josh5/unmanic

https://forums.unraid.net/topic/76878-support-josh5-unmanic-library-optimiser/

**Describe alternatives you've considered**
Installing it manually

**Additional context**
None

**Comment by nemchik** [comment]
Commenting to keep this open.

**Comment by nemchik** [comment]
Keep this. Have some other things in dev that I'm going to wrap up first, but I've seen others interested in this on discord so I'll try to get to it soon.
