### ISSUE TITLE
Versioning Number on DS

### ISSUE THREAD

**Issue by robgates** [GhostWriters/DockSTARTer#516]
One for the future maybe but is there is anyway you can include a release / version number in DS ? I know it doesn't take much to update DS to the latest version but I always like to see what version I am running

**Comment by Tharic99** [comment]
I'd certainly like to have the ability to run a version flag like a a `ds -v` to know what version I'm currently running. I also think using tagging in GitHub would be handy. Much like other images in the containers are doing such as Sonarr/Radarr, you could have the ability to hop onto a dev branch or a beta branch more easily in that scenario, correct?

**Comment by nemchik** [comment]
DS has a way for users to test changes from a dev branch. `ds -u origin/dev` assuming that there is a branch in this repo named `dev`. The way it is setup will be `origin` is this repo and you could technically add your own fork under a different remote name such as `myfork` and then use `ds -u myfork/mybranch` to test changes from your fork. I would not recommend actively developing your branch from the same folder that you run your DS in production as that takes additional effort, but having a folder of DS cloned for your fork and then having your production DS folder pull changes that you push to your fork should be quite easy as described above.

**Comment by erik-x** [comment]
I think option two described above by nemchick would be a reasonable start
