### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by jmcmike1** [GhostWriters/DockSTARTer#52]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Debian]

**Additional context**

**Comment by jmcmike1** [comment]
when running the 'docker-compose up -d' script I get the following error:
"couldn't connect to Docker daemon at http+docker://localhost - is it running? If it's at a non-standard location, specify the URL with the DOCKER_Host environment variable"
I have followed you setup with no exceptions so far.

**Comment by nemchik** [comment]
Please list your OS and version.

This sounds to me like you might not have rebooted when asked to do so?

**Comment by jmcmike1** [comment]
I am running Ubuntu 18 on a mac laptop. I did reboot at the prompt but
still get the error.

**Comment by jmcmike1** [comment]
Specifically Ubuntu 18.04 LTS

**Comment by nemchik** [comment]
Also BTW the issue template is meant to be filled out. When opening issues please edit the default message that automatically populated in the issue box and fill out your information and use the Preview tab to see that it looks right before submitting. Here is an example:

***



**Describe the bug**
I get an error message when trying to run `docker-compose up -d`

**To Reproduce**
Steps to reproduce the behavior:
1. Run `bash ~/.docker/main.sh -g`
2. Answer `no` when asked to run containers now
3. Run `cd ~/.docker/compose`
4. Run `docker-compose up -d`
5. See an error message:
```
couldn't connect to Docker daemon at http+docker://localhost - is it running? If it's at a non-standard location, specify the URL with the DOCKER_Host environment variable
```

**Expected behavior**
Containers should start.

**Screenshots**
(You can remove sections that do not apply, in this case copying the error message covers you better than showing a screenshot)

**System (please complete the following information):**
 - OS: Ubuntu Desktop x64
 - Version 18.04

**Comment by jmcmike1** [comment]
sorry, i'm new to this

**Comment by nemchik** [comment]
No problem. Can you post the full log of what happens when you run `sudo bash ~/.docker/main.sh -i`?

**Comment by jmcmike1** [comment]
mcmike@mcmikeU:~$ sudo bash ~/.docker/main.sh -i
[sudo] password for mcmike:
Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [83.2
kB]
Hit:3 https://download.docker.com/linux/ubuntu bionic
InRelease
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2
kB]
Get:5 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6
kB]
Get:6 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 DEP-11
Metadata [112 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 48x48
Icons [25.1 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 64x64
Icons [44.5 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11
48x48 Icons [120 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11
64x64 Icons [192 kB]
Get:11 http://us.archive.ubuntu.com/ubuntu bionic-backports/universe amd64
DEP-11 Metadata [5,100 B]
Get:12 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11
Metadata [204 B]
Get:13 http://security.ubuntu.com/ubuntu bionic-security/universe amd64
DEP-11 Metadata [2,452 B]
Fetched 743 kB in 1s (515 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
100   604    0   604    0     0   1230      0 --:--:-- --:--:-- --:--:--
1227
100 5259k  100 5259k    0     0   481k      0  0:00:10  0:00:10 --:--:--
844k
# Executing docker install script, commit: 36b78b2
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which
is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using
it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq apt-transport-https ca-certificates curl
>/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key
add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu
bionic edge" > /etc/apt/sources.list.d/docker.list
+ [ ubuntu = debian ]
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ sh -c docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:16:13 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:14:23 2018
  OS/Arch:      linux/amd64
  Experimental: false
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to
https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
100 12211  100 12211    0     0  28463      0 --:--:-- --:--:-- --:--:--
28397
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
100   617    0   617    0     0   1214      0 --:--:-- --:--:-- --:--:--
1212
100 10.3M  100 10.3M    0     0  1021k      0  0:00:10  0:00:10 --:--:--
478k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
100 13043  100 13043    0     0  44363      0 --:--:-- --:--:-- --:--:--
44515
groupadd: group 'docker' already exists
Synchronizing state of docker.service with SysV service script with
/lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable docker

Your system needs to reboot for changes to take effect. Would you like to
reboot now? [Yn]

**Comment by nemchik** [comment]
That all looks good to me. Can you try `sudo bash ~/.docker/main.sh -g` (using sudo with this one as well)

**Comment by nemchik** [comment]
Also, say yes at the prompt to bring up the containers (it will run `docker-compose up -d` for you)

**Comment by jmcmike1** [comment]
mcmike@mcmikeU:~$ sudo bash ~/.docker/main.sh -g
[sudo] password for mcmike:
Sorry, try again.
[sudo] password for mcmike:
Could not find
/home/mcmike/.docker/compose/.apps/watchtower/watchtower.ports.yml file.

Would you like to run your selected containers now? [Yn]y
couchpotato is up-to-date
ombi is up-to-date
organizr is up-to-date
nzbget is up-to-date
radarr is up-to-date
sabnzbd is up-to-date
watchtower is up-to-date
deluge is up-to-date
hydra2 is up-to-date
transmission is up-to-date
plex is up-to-date
portainer is up-to-date
tautulli is up-to-date

**Comment by nemchik** [comment]
That looks like it's working. if you use the script and answer yes to running your containers you don't need to run `docker-compose up -d` manually later. You're up and running.

**Comment by nemchik** [comment]
Also could you try running `bash ~/.docker/main.sh -g` without sudo?

I think it's only really an issue if you try running `docker-compose up -d` by itself without sudo. I think the main script works without sudo.

**Comment by jmcmike1** [comment]
I get the same error message when I run without using sudo. no error with
sudo.

**Comment by nemchik** [comment]
You mean running `bash ~/.docker/main.sh -g` without sudo gives you the error?

**Comment by jmcmike1** [comment]
yes

**Comment by jmcmike1** [comment]
sorry for the slow response. I am struggling with Organizr and I cannot get
Sabnzb on port 9090

**Comment by nemchik** [comment]
Why don't you join us on gitter https://gitter.im/GhostWriters/DockSTARTer

We might be able to help with scattered issues on there a little better.
