### ISSUE TITLE
qBittorrent subdomain and subfolder

### ISSUE THREAD

**Issue by mouzzampk2014** [GhostWriters/DockSTARTer#521]
**Is your feature request related to a problem? Please describe.**
Me and most of us are very new to dockers and more importantly configurations and if the files are there than it will save so much time to save and replace the values.
**Describe the solution you'd like**
If the .conf file are already inside the folder than we can just replace the values and everything up and working just like other files. 
**Describe alternatives you've considered**
Currently I have to copy the existing conf and save as qBittorrent.
**Additional context**
Would be very nice if you add the folders :) Thank you

**Comment by nemchik** [comment]
Please post this feature request here https://github.com/linuxserver/reverse-proxy-confs
That is the repository where LSIO maintains the sample configs that are included in the letsencrypt image.
