### ISSUE TITLE
Add Docker FileBot

### ISSUE THREAD

**Issue by Tharic99** [GhostWriters/DockSTARTer#557]
Is your feature request related to a problem? Please describe.
No

Describe the solution you'd like
FileBot is the ultimate tool for organizing and renaming your movies, tv shows or anime, and music well as downloading subtitles and artwork. This is a docker image containing both the current FileBot as well as an older version of the image that has the Donation supported version available. Image has a GUI and very good documentation provided on the compose file and other features/functionality.

https://github.com/jlesage/docker-filebot

https://hub.docker.com/r/jlesage/filebot

Describe alternatives you've considered
Installing it manually

Additional context
None

**Comment by nemchik** [comment]
Keep this. I've been slow to look at new apps.

**Comment by nemchik** [comment]
Keep this.

**Comment by jodfie** [comment]
i'm interested in this as well...

**Comment by nemchik** [comment]
Feature added in #744 needs testing (instructions in the PR).
