### ISSUE TITLE
Plex 5353: bind address already in use

### ISSUE THREAD

**Issue by m7ke** [GhostWriters/DockSTARTer#568]
**Describe the bug**
Receiving the following error:

`ERROR: for plex  Cannot start service plex: driver failed programming external connectivity on endpoint plex (7501c056b2d29c770ec6ee58ee571dddf9ec08c4f8431c99f5be25f9abfca312): Error starting userland proxy: listen udp 0.0.0.0:5353: bind: address already in use
ERROR: Encountered errors while bringing up the project.
2019-02-15 10:54:05 [FATAL]      Docker Compose failed.
`

**System (please complete the following information):**

- OS: Ubuntu
- Version 18.04.2

**Additional context**
On a fresh install of Ubuntu 18.04 with only the default apps (Portainer and Ouroboros) and Plex apps selected.

**Comment by nemchik** [comment]
Port 5353 is used by ahavi-daemon by default on Ubuntu. It's mostly useless. You can choose to disable ahavi on ubuntu or simply change the port for plex to 5354 or something (Plex barely uses this port either).

Port conflicts such as this can happen for various reasons. Our wiki has information about this topic https://github.com/GhostWriters/DockSTARTer/wiki/Port-Conflicts It's a good idea to familiarize yourself with this message and how to handle it. Our discord support can offer more help if you need it.
