### ISSUE TITLE
Hostnames in DS for ouroboros

### ISSUE THREAD

**Issue by TRaSH-** [GhostWriters/DockSTARTer#569]
**Is your feature request related to a problem? Please describe.**
When i get a update notification from ouroboros it shows the following
![image](https://user-images.githubusercontent.com/6155095/52915432-527ead80-32d4-11e9-846f-c7be0fab187d.png)

**Describe the solution you'd like**
I would like to see that it shows the hostname

**Describe alternatives you've considered**
for the time being i'm using a override
```
  ouroboros:
    hostname: myhostname 
```

**Comment by nemchik** [comment]
FYI I will likely set DS up to apply a common hostname to all containers and have a system detected option in the GUI.
