### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by polayer2015** [GhostWriters/DockSTARTer#57]
I have installed the script on Ubuntu 16.04 and ran into one issue.

When I run the generator:
`sudo bash ~/.docker/main.sh -g`

I get:
`Could not find /home/user/.docker/compose/.apps/watchtower/watchtower.ports.yml file.`

Followed by:
`Would you like to run your selected containers now? [Yn]`
 
Everything else processes with no further issues.  Is this something I need to create or is the script responsible for this?

I also wanted to follow up on using secure ports.  I'm trying to change to secure ports when possible, but the script reverts to default ports when I add them manually.  You shared this in the Getting Started section and I'm hoping for instructions.

> We encourage you to have a look at the generated docker-compose.yml file, however if you wish to make changes please consider using overrides (documentation coming soon).

**Comment by nemchik** [comment]
`watchtower.ports.yml` is not needed. Watchtower doesn't use ports, but we can put a dummy file in the repo to prevent the message.

There is a link in the wiki sidebar on the right that explains overrides. Please let me know if you have any questions. I'd like to keep this issue open until we resolve the warning message. If you have troubles with overrides please open a separate issue or join us on gitter to chat. Thanks!

**Comment by nemchik** [comment]
It seems a lot of people are having trouble running `docker-compose up -d` without sudo, even though you actually shouldn't need it. I'll add it to the wiki.

Also as for the VPN you can `docker-compose up -d` and  `docker-compose down` but remember to cd into the folder specified in the wiki.

Also keep in mind if you answer yes when the generator prompts you to run the the containers you don't need to manually run  `docker-compose up -d`

**Comment by JonathonSunshine** [comment]
Thanks, they are all starting up at boot currently. So if you can tell me how to stop that then i'll be all set I think... I think the "Getting Started" could use that info as well. I have a lot of questions, if i'm allowed I'll update the Wiki if you like. Should I start new threads for questions or...

**Comment by nemchik** [comment]
To stop them from starting at boot you would want to adjust the `restart: always` option using overrides. I could also change this into an environment variable for each app so that you wouldn't need to make override files. But for the moment overrides are the best option for what you want. I'd like to get an far section started in the wiki, and I'm fine with others contributing.

**Comment by nemchik** [comment]
@JonathonSunshine If you wouldn't mind joining us on Gitter https://gitter.im/GhostWriters/DockSTARTer I'd like to chat about giving you access to edit the wiki 👍 

I'm closing this issue as #60 resolves the watchtower warning. Other issues can be opened for separate topics if needed.
