### ISSUE TITLE
Missing instructions on Nextcloud configuration

### ISSUE THREAD

**Issue by aDarkling** [GhostWriters/DockSTARTer#571]
Hi.
Wonderful project!

I've just started setting up Nextcloud, though.
There's no instructions any where on setting it up to use the MariaDB docker as its database.

Can anyone illuminate me?

**Comment by nemchik** [comment]
Best place to look is going to be https://hub.docker.com/r/linuxserver/nextcloud and https://hub.docker.com/r/linuxserver/mariadb

You'll want to setup mariadb first and probably phpmyadmin unless you know SQL very well. Then setup nextcloud to use a database from your mariadb setup.

DS gets stuff installed for you, but setting up the app is still something you'll need to look into for each app.

**Comment by highaltidude** [comment]
I think it would be helpful to add this to the app specifics page. I was able to do this by doing what Nemchik said, but wasn't clear from any documentation.

**Comment by nemchik** [comment]
> I think it would be helpful to add this to the app specifics page. I was able to do this by doing what Nemchik said, but wasn't clear from any documentation.

We can add this to the docs. Thanks for the suggestion!

**Comment by angrycuban13** [comment]
> I think it would be helpful to add this to the app specifics page. I was able to do this by doing what Nemchik said, but wasn't clear from any documentation. 

Agreed. Can you please open a new issue so I can track it?
