### ISSUE TITLE
Version detection causing docker install on ds -c up|down

### ISSUE THREAD

**Issue by mcaron1234** [GhostWriters/DockSTARTer#575]
Docker is listing backports as new releases on https://github.com/docker/docker-ce/releases and docker is not making the latest version available to everyone.  These two issue cause dockstarter to think it needs to update docker every time it does a version comparison against the docker repo.

**Comment by erik-x** [comment]
<img width="731" alt="skarmavbild 2019-02-21 kl 18 54 16" src="https://user-images.githubusercontent.com/207301/53190549-23d14180-360a-11e9-8d67-1104387d185f.png">

Not sure If this is related, but my DS nightly creates multiple (close to 100) unused images. Looking at the version-tag on the containers they are of a running number series. Typlcally from 100 and upwards. In the screenshot it has happened to Plex, but the container varies. Yesterday it was the netdata container that spawned a lot of unused images. I have to daily prune the images reallocating GB of wasted space.

**Comment by nemchik** [comment]
@erik-x I believe that issue would not be related to this. If you run `ds -u` to update DS and then `ds -c up`  to recompose your stack and then `ds -p` to prune containers that should resolve the issue. I believe this was related to a problem in Ouroboros that has been resolved.

If you still have this problem please open a new issue and post whatever info you can and we'll have a look. Thanks

**Comment by erik-x** [comment]
Thanks for quick feedback. I’ll try your recipe and check the status tomorrow. In case it persist I’ll raise it as a separate issue.

Cheers
