### ISSUE TITLE
Spawning unused images

### ISSUE THREAD

**Issue by erik-x** [GhostWriters/DockSTARTer#580]
**Describe the bug**
Nightly I have surplus images created. The container spawning the images differs.
(When I last posted on what turned out to be an unrelated issue it was Sabnzbd, now it is let's encrypt)

A few days back I ran "ds -u && ds -c && ds -p", to secure that I was updated to the latest release, and purged the unused images.
Now it is back. Expected behavior is 13 images.

**To Reproduce**
This happens automagically. Please guide me in what I can do to produce logs our other output that can help in reproducing the issue / troubleshooting,

**Expected behavior**
Update to latest/tagged images and removal of the unused images.

**Screenshots**
See attached.
<img width="1127" alt="skarmavbild 2019-02-23 kl 09 26 17" src="https://user-images.githubusercontent.com/207301/53284027-90555900-374e-11e9-88b2-536bc9273d97.png">
<img width="574" alt="skarmavbild 2019-02-23 kl 09 31 20" src="https://user-images.githubusercontent.com/207301/53284032-99dec100-374e-11e9-991d-cb1510044baa.png">

**System (please complete the following information):**

- OS: Ubuntu 18.04.2 LTS

**Additional context**

**Comment by nemchik** [comment]
Please try this:
Disable Ouroboros (through the GUI or .env, whichever you're comfortable with).
Run
```bash
ds -c pull
ds -c down
ds -c up
ds -p
```
Then check how many images you have and please report that here. Please also run `docker ps -a` and post the output here.

After that we'll have to wait a bit to see if the issue continues.

What I'm going for is trying to see if this is an issue with ouroboros updating stuff or if something else is causing the issue. If disabling ouroboros fixes the issue we'll ask their devs to have a look, and we'll if we need to have you using something else to auto update your containers.

**Comment by erik-x** [comment]
Done!

Attached is the output from docker ps -a.

For my learning, what are the different commands that I have now run. (The ones above)

I'll monitor and see what happens and report back.

[docker_running_containers.txt](https://github.com/GhostWriters/DockSTARTer/files/2896993/docker_running_containers.txt)

**Comment by nemchik** [comment]
`ds -h` can show you all of what the ds commands do.

`ds -c pull` pulls the latest images (or specific tags if defined) for all containers defined in your compose file (setup by DS)

`ds -c down` stops and removes all containers in your compose file

`ds -c up` creates and starts all containers from your compose file and pulls any missing images

`ds -p` prunes unused resources such as the docker images you're having trouble with

`docker ps -a` lists all containers (running or not) that have been created on your system.

**Comment by nemchik** [comment]
I wanted to check in and see if you've had any more troubles with this?

**Comment by erik-x** [comment]
I have not had any issues since I disabled Ouroboros. I am however seeing other instabilities in my system that I need to tend to. (Not DS related)

I will get the system in working order and then see if Ouroboros can again be enabled.

Will report back when normal operations has been secured.

**Comment by erik-x** [comment]
Excuse my noob question, but how do I best restore a backup?

https://github.com/GhostWriters/DockSTARTer/wiki/Backups <https://github.com/GhostWriters/DockSTARTer/wiki/Backups>
Holds good information on taking backups, but could maybe be extended with how to best restore them.
(Say I would like to do a full restore from the backups)

/ E

**Comment by nemchik** [comment]
Sorry for not replying to this sooner!

The general idea is you go to the folder where your backups are saved and look inside the `FOLDERNAME.001` folder for each item you want to restore. inside it will be the most recent copy of the folder that would go in your `~/.docker/config` (you may have relocated this, but that's the default location). So you would do this for example: `cp -R /path/to/backups/sonarr.001/sonarr ~/.docker/config/`

You also want to make sure you get the `.compose.backups` folder restored to the config location and then inside that you'll see copies of your `.env` file and if you use a `docker-compose.override.yml` that'll be backed up in there too. The files backed up to this folder will have the date/time they were backed up appended to their name, so you'll want to remove that last bit of the filename and restore them to `~/.docker/compose/`

**Comment by erik-x** [comment]
No worries, I worked it out. Put together a small script to restore the backup.
Somewhat new to Linux but not totally unable to handle it.

I’m having a reoccurring issue with ”no space left on device” issue sinking docker, killing of processes and wrecking havoc with my machine. Still I have plenty of space. Tried everything; disabling dir_index (ext4), reinstalled OS, checked inodes and I have no elaborate mount structures. Any clue to what might cause this? (Think of switching from Ubuntu to CentOS to see if it would make a difference)

**Comment by nemchik** [comment]
This issue you're having is even with Ouroboros disabled? Have you investigated what is taking up the space? You can use something like `ncdu` (installed via apt) to check.

P.S. I run Ubuntu with no issues, but DS should work on CentOS as well.

**Comment by erik-x** [comment]
The Ouroboros issue is gone. Thanks.

Will see if I can hunt down the bug somehow.

/E

**Comment by nemchik** [comment]
Do you still need any assistance with this?

**Comment by erik-x** [comment]
Hi Eric,

No, the issue is gone. Not sure what really caused it but now it is gone.
Did a reinstallation of the whole sever. (Changed from Ubuntu to CentOS, rather of preference and not that I think Ubuntu caused it) So in the reinstalling the complete setup I also got rid of the problem.
