### ISSUE TITLE
Add Bitwarden

### ISSUE THREAD

**Issue by m7ke** [GhostWriters/DockSTARTer#581]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to to install and manage Bitwarden using DockSTARTer. Bitwarden is an open source password manager that easily allows one to host their own password vault, giving the user complete control over their data.

https://help.bitwarden.com/article/install-on-premise
https://hub.docker.com/r/bitwarden/setup

**Describe alternatives you've considered**
Install Bitwarden docker that's not part of the DockSTARTer stack.

**Additional context**
![](https://i.imgur.com/dkzAWA6.png)

**Comment by mouzzampk2014** [comment]
Hi, still happening this weekend :) Thank you

**Comment by nemchik** [comment]
I started to read up on this and wasn't 100% sure about how it needed to work. It might be a bit longer while I continue research.

**Comment by nemchik** [comment]
Looks like this will be our best bet
https://hub.docker.com/r/mprasil/bitwarden/

Linking for reference, still working on it 😄

**Comment by mouzzampk2014** [comment]
I had a chat with them on matrix and they had very active group there too :)

**Comment by nemchik** [comment]
Matrix?

**Comment by mouzzampk2014** [comment]
https://matrix.to/#/#bitwarden_rs:matrix.org

**Comment by nemchik** [comment]
#636 needs testing if you wouldn't mind confirming it works for you.

**Comment by mouzzampk2014** [comment]
Yes please anytime do I need to add in override or it's already in ds? Thanks for the update

**Comment by nemchik** [comment]
Everything is already in DS. If you already have an override I would recommend removing it or commenting it out. I've seen a report already that the first run creates the config folder as root (nothing we can really do about that) and you'll need to chown it to your usuer and then restart the container.

**Comment by mouzzampk2014** [comment]
Coolio let me do it tonight:)
