### ISSUE TITLE
Multiple drives setup

### ISSUE THREAD

**Issue by erfly7** [GhostWriters/DockSTARTer#583]
Anyway to get a setup guide on how to implement multiple HDD system?

Have a computer with 1 SSD and 8 HDD

On first attempt to implement Dockstarter could never get PLEX/Sonarr etc. in the Docker system to "see" all the drives which are where all of the media will be stored.

Dockstarter will be installed on the SSD with Ubuntu, however all the media will be stored on the 8 drives.

help please?

**Comment by nemchik** [comment]
You have many options for this but two common ways of doing this are a drive pool/raid or a parent folder with each disk mounted as subfolders.

In a drive pool/raid you would use a raid controller or something like mergerfs to make all your disks into a single pool of storage.

With the parent folder method you would setup for example `/mnt/mediadisks` as the parent and then each disk would be `/mnt/mediadisks/media1` and `/mnt/mediadisks/media2` etc and you can set your media directories in DS to be `/mnt/mediadisks` (the parent, for all media folders regardless of type) and then you would see each subfolder (disk) inside the apps. This method is a bit messier, but it does work.

There are likely other options as well, but these are the common ways I've seen it done.

**Comment by erfly7** [comment]
Not sure want  RAID, disks already filled and don't have  RAID controller

The second method how do you create /mnt/mediadisks and where do you enter in when setting up Dockstarter?

**Comment by nemchik** [comment]
Config > global

**Comment by erfly7** [comment]
Config global is during the setup screens?

**Comment by nemchik** [comment]
Yes. You can also edit `~/.docker/compose/.env` and set the global variables up top for the media folders and then run `ds -c`

**Comment by nemchik** [comment]
Do you still need any assistance with this?

**Comment by erfly7** [comment]
Yes still no idea

**Comment by nemchik** [comment]
I really do recommend you check out google or youtube for some information about what RAID is and how it works. You may also be interested in MergerFS which is very popular these days. Those are probably the easiest option to manage long term.
