### ISSUE TITLE
Antennas

### ISSUE THREAD

**Issue by islanddog** [GhostWriters/DockSTARTer#584]
Docker Link -
https://hub.docker.com/r/thejf/antennas/

**Is your feature request related to a problem? Please describe.**
Nope. I actually love DockSTARTer.

**Describe the solution you'd like**
I would like a solution that integrates my IPTV service into Plex via DockSTARTer. I tried going through Emby (even bought premium) but Plex has my heart. Integration for Antennas, Tvhproxy, xTeve or otherwise would be greatly appreciated. I realize these are 'half' baked solutions but I feel it would hold me over until updates come out from the Plex team.

**Describe alternatives you've considered**
Emby (didn't like it).

**Comment by nemchik** [comment]
Keep this open. Sorry I have not made it around to looking into this yet.

**Comment by nemchik** [comment]
Keep this
