### ISSUE TITLE
Funkwhale support

### ISSUE THREAD

**Issue by raulvasquez** [GhostWriters/DockSTARTer#592]
Would love to see funkwhale added as an alternative to airsonic.

https://funkwhale.audio

**Comment by raulvasquez** [comment]
Docker page https://hub.docker.com/u/funkwhale/

**Comment by nemchik** [comment]
Keep this open. Sorry I have not made it to looking into this yet.

**Comment by nemchik** [comment]
Keep this open. Sorry I have not made it around to looking into this yet.

**Comment by nemchik** [comment]
Keep this
