### ISSUE TITLE
Change netdata tag name

### ISSUE THREAD

**Issue by Xyv** [GhostWriters/DockSTARTer#593]
Hi!

I am running on a rpi3 and was curious to see my netdata image hasn't been updated in the last 6 months.
It appears they changed their tag naming scheme from `netdata/netdata:platform` to `netdata/netdata:version-platform`.
So in my case changing `netdata/netdata:armhf` to `netdata/netdata:latest-armhf` in [netdata.armv7l.yml](https://github.com/GhostWriters/DockSTARTer/blob/f0474faaca1925ca6201748da7bfa7a69276f379/compose/.apps/netdata/netdata.armv7l.yml) is pulling the latest image.

Thanks for your amazing work!
Xyv

**Comment by nemchik** [comment]
It looks like they might be trying to get their container to support proper multi-arch selection without specifying tags. Can you try using just `netdata/netdata` with no tag? I'll be able to get this updated today after that confirmation whether it works or not.

**Comment by Xyv** [comment]
Indeed using `netdata/netdata` works properly!

**Comment by nemchik** [comment]
That's great! I'll get this updated soon.

**Comment by nemchik** [comment]
All done, thanks for reporting this!
