### ISSUE TITLE
Plex file EasyAudioEncoder wrong permission

### ISSUE THREAD

**Issue by sedago** [GhostWriters/DockSTARTer#608]
ds overwrites the permission to the "~/.docker/config/plex/Library/Application Support/Plex Media Server/Codecs/EasyAudioEncoder-141-linux-ubuntu-x86_64/EasyAudioEncoder/EasyAudioEncoder" file which results in transcodes not working in some cases.

Execute bit is missing, so chmod 700 fixes the issue.

**Comment by nemchik** [comment]
https://github.com/GhostWriters/DockSTARTer/pull/606 this will probably fix the issue.

**Comment by nemchik** [comment]
Merge just happened, if you want to run `ds -u` you can see if this fixes the issue (it shouldn't reset the permissions you set on the codecs anymore).

**Comment by sedago** [comment]
Thank you very much, will test it.

**Comment by nemchik** [comment]
I'm going to close this for now but feel free to reopen if you still have troubles.
