### ISSUE TITLE
transmission-daemon should have more settings options or a way to be stopped

### ISSUE THREAD

**Issue by mytvpro** [GhostWriters/DockSTARTer#611]
transmission-daemon settings.json can only be edited and saved without being overwritten by stopping the daemon first. i have entered the docker container but cannot figure out how to stop it. i have tried several ways without success. currently the default folder should be set differently and i would like to enable more than 5 queued downloads. also would like to add username and password. not seeing how to do this so i'll need to remove the docker app and install it the traditional way on host system

**Comment by nemchik** [comment]
Rather than trying to stop the app inside the container, just stop the whole container.
```bash
docker stop transmission
```
Then edit your settings file and start it back up again.

**Comment by mytvpro** [comment]
sorry i was under some misconception that running the container again after stopping would cause it to revert to its orginal state

**Comment by nemchik** [comment]
Not a problem. You would be correct if we (DS) was not mapping persistent storage using volumes. Then anything you do would be only inside the container. But since we map the config volume for each app it has a place to keep its settings when stopping/starting/recreating containers.

**Comment by mytvpro** [comment]
> Not a problem. You would be correct if we (DS) was not mapping persistent storage using volumes. Then anything you do would be only inside the container. But since we map the config volume for each app it has a place to keep its settings when stopping/starting/recreating containers.

oh i see so i should find the config on the host machine?

**Comment by mytvpro** [comment]
found

**Comment by mytvpro** [comment]
sorry for so many messages. i stopped the container edited the file and started the container but that doesn't seem to have triggered transmission to load the new settings file. would you have a suggestion?

**Comment by nemchik** [comment]
The file should be in `~/.docker/config/transmission/settings.json` please make sure you're editing the file in that location.
