### ISSUE TITLE
Trouble installing on Ubuntu 18.04 new install

### ISSUE THREAD

**Issue by artiedarrell** [GhostWriters/DockSTARTer#617]
**Describe the bug**
/home/user/.docker/.scripts/install_compose.sh: line 5: 18805 Segmentation fault      (core d                        umped) pip install -IUq "urllib3[secure]" > /dev/null 2>&1
2019-03-29 15:57:18 [WARNING]    Failed to install urllib3[secure] from pip. This can usually be                         ignored.
/home/user/.docker/.scripts/install_compose.sh: line 5: 18824 Segmentation fault      (core d                        umped) pip install -IUq docker-compose > /dev/null 2>&1
2019-03-29 15:57:50 [FATAL]      Failed to install docker-compose from pip.

**To Reproduce**
New Ubuntu 18.04 install, only installed Apache and Docker, before trying to install DockSTARTer

tried doing:
sudo systemctl stop docker
sudo systemctl disable docker
sudo apt-get remove docker-ce
sudo ds -i

to no effect

**Comment by nemchik** [comment]
Try running `sudo pip install -IUq docker-compose` and if there are any errors post them here.

**Comment by artiedarrell** [comment]
```
user@server:~$ sudo pip install -IUq docker-compose
Segmentation fault

```

**Comment by nemchik** [comment]
Is that the only thing it displays?

**Comment by artiedarrell** [comment]
correct

**Comment by nemchik** [comment]
Try without the `q`.

```bash
sudo pip install -IU docker-compose
```

**Comment by artiedarrell** [comment]
seems to have made progress

```

Installing collected packages: six, backports.ssl-match-hostname, docopt, PyYAML, ipaddress, docker-pycreds, idna, urllib3, certifi, chardet, requests, websocket-client, asn1crypto, enum34, pycparser, cffi, cryptography, pynacl, pyasn1, bcrypt, paramiko, docker, dockerpty, cached-property, functools32, jsonschema, texttable, docker-compose
  Running setup.py install for backports.ssl-match-hostname ... done
  Running setup.py install for docopt ... done
  Running setup.py install for PyYAML ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for dockerpty ... done
  Running setup.py install for functools32 ... done
  Running setup.py install for texttable ... done
Successfully installed PyYAML-3.13 asn1crypto-0.24.0 backports.ssl-match-hostname-3.7.0.1 bcrypt-3.1.6 cached-property-1.5.1 certifi-2019.3.9 cffi-1.12.2 chardet-3.0.4 cryptography-2.6.1 docker-3.7.2 docker-compose-1.24.0 docker-pycreds-0.4.0 dockerpty-0.4.1 docopt-0.6.2 enum34-1.1.6 functools32-3.2.3.post2 idna-2.8 ipaddress-1.0.22 jsonschema-2.6.0 paramiko-2.4.2 pyasn1-0.4.5 pycparser-2.19 pynacl-1.3.0 requests-2.20.1 six-1.12.0 texttable-0.9.1 urllib3-1.24.1 websocket-client-0.56.0
Segmentation fault

```

**Comment by nemchik** [comment]
Were you able to figure out what this was? I have another user mentioning the same issue. My next recommendation was going to be adding `-vv` to get some more info about what's failing.

**Comment by artiedarrell** [comment]
no idea... 

sudo pip install -IU docker-compose

works, but if you use 

bash -c "$(curl -fsSL https://get.dockstarter.com)"

it fails

Ubuntu 18.04 fresh out of the box.... just tried again, same issue.

**Comment by nemchik** [comment]
so does `ds -i` work now?

**Comment by artiedarrell** [comment]
yes trying to install some of the packages now

**Comment by laravelish** [comment]
why is this closed ? its not fixed yet

**Comment by nemchik** [comment]
@magik20 closed it. Others seem to be having the same or very similar issues though and I'm working on a fix, but the results are very inconsistent.

**Comment by robby-dermody** [comment]
I am having the same issue too. It breaks updates of a previously working Dockstarter setup. I believe the issue is due to a new version of docker compose? (https://github.com/docker/compose/releases/tag/1.24.0). I also see https://github.com/docker/compose/issues/2738.

It seems the `sudo pip install -IUq docker-compose` command used by the script fails, while `sudo pip install docker-compose` works?

**Comment by nemchik** [comment]
We merged a fix in recently https://github.com/GhostWriters/DockSTARTer/pull/621

If you run `ds -u` and then `ds -i` it should resolve the issue.

There is still an issue with CentOS which is being addressed in #623 (still needs testing on CentOS).

**Comment by robby-dermody** [comment]
That fixed the error. However, after every run of `ds` (e.g. to add a new app), it wants to re-install docker. e.g.:

```
2019-04-02 10:41:27 [INFO]       Merging docker-compose.yml complete.
2019-04-02 10:41:32 [INFO]       Creating containers for all enabled services.
2019-04-02 10:41:33 [INFO]       Removing snap Docker package.
2019-04-02 10:41:33 [INFO]       Installing latest docker. Please be patient, this can take a while.
```

**Comment by nemchik** [comment]
The version expected as of writing is `18.09.4`. You should be able to run `docker --version` and see that you have that version (or newer) installed. If not DS will try to install the latest available version. That's a bit of a separate issue, so if you'd like you can open a new issue and we can see what's going on, or join us on Discord and we can help there.

**Comment by robby-dermody** [comment]
`Docker version 18.09.3, build 774a1f4`

Interesting that the version is not being updated to the latest. I'll check into this a bit more today and tomorrow and if I can't figure it out will create an issue with the relevant info. Thanks!

**Comment by nemchik** [comment]
The install is done using https://get.docker.com/
It has instructions right up top about installing using the script, you could try doing it manually and seeing if you get updated.

**Comment by Fotoblysk** [comment]
Today I had the same issue, it somehow succeded when installed newest docker stopping docker demon and installing compose with `sudo pip install -IUq docker-compose`. I will try to reproduce this on clean install, but I'm not sure if I didn't done something more. 
```
uname -r
4.18.0-17-generic
python -V
Python 2.7.15rc1
pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
docker -v 
Docker version 18.09.5, build e8ff056
docker-compose -v
docker-compose version 1.24.0, build 0aa5906
```

**Comment by nemchik** [comment]
Please note we're using python3 for pip and compose now. Can you run `ds -i` and if you have any issues post your log in a new issue and we'll look into getting it fixed.
