### ISSUE TITLE
Booksonic docker image

### ISSUE THREAD

**Issue by juligreen** [GhostWriters/DockSTARTer#618]
New app request: [Booksonic](https://github.com/linuxserver/docker-booksonic).
It's a subsonic fork for audiobooks and there already is a linuxserver docker image.

**Comment by nemchik** [comment]
Should be a pretty easy add. I need to work on getting these requests done (PRs welcome).

**Comment by juligreen** [comment]
@mcaron1234 has added this image in april.
I will close the issue.
