### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by mgik20** [GhostWriters/DockSTARTer#628]
I saw that Plex had an update (Version 1.15.3.858), so I attempted to update all containers / dockstarter 

2019-04-04 20:03:12 [INFO]       apt package manager detected.
2019-04-04 20:03:12 [INFO]       Removing old Docker packages.
2019-04-04 20:03:13 [INFO]       Updating repositories.
2019-04-04 20:03:47 [INFO]       Upgrading packages. Please be patient, this can take a while.
2019-04-04 20:04:19 [FATAL]      Failed to upgrade packages from apt.

Ubuntu 18.04 fresh install, fairly new DS install, ... maybe 4-5 days old.

**Comment by nemchik** [comment]
For that message, please run `sudo apt-get -y dist-upgrade` and you will probably get an error. You'll need to fix whatever is wrong that's causing the error you see.

As for Plex, DS sets up the ouroboros container to update your docker apps for you once a day at 4am, but you can run an update anytime by running `ds -c pull` and then `ds -c`

HOWEVER

Apps inside docker containers will only be updated if the docker image is updated. The docker image is used to create the docker container. The Plex image is maintained by Plex's official repository and they have a tendency to not keep the image up to date very well.

**Comment by mgik20** [comment]
strangely `sudo apt-get -y dist-upgrade` then running `ds` worked

its strange because for the past 3-4 days when running `ds` i never had this happen before today.

thanks!
