### ISSUE TITLE
Quassel-core support

### ISSUE THREAD

**Issue by rodrigorodrigo** [GhostWriters/DockSTARTer#629]
This would probably be an easy app to add

**Is your feature request related to a problem? Please describe.**
Not really. Its just that, in my opinion, quassel is the best irc client around.

**Describe alternatives you've considered**
I have already used alternatives such as bouncers (znc) and thelounge. I'd rather use quassel as it has proper clients for all major platforms

**Additional context**
https://github.com/linuxserver/docker-quassel-core

**Comment by nemchik** [comment]
#724 adds this and will merge shortly.
