### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by simplymathematics** [GhostWriters/DockSTARTer#630]
**Describe the bug**
I have dock starter running inside an ubuntu 16.04 vm (vbox) on Windows. My server crashes like once a day. If you could help me track down the appropriate log files, that would be a huge help. Thanks!

**To Reproduce**
Wait

**Expected behavior**
Not crash

**Screenshots**

**System (please complete the following information):**

- OS: Ubuntu
- Version 16.04

**Additional context**

**Comment by nemchik** [comment]
Off the top of my head this doesn't sound like an issue caused by DockSTARTer itself. Our Discord server would be a good place to continue this conversation.
