### ISSUE TITLE
Plex password Prompts appears to be from .htaccess

### ISSUE THREAD

**Issue by daveb92** [GhostWriters/DockSTARTer#631]
When accessing Plex under a subfolder i am getting the splash screen, then I am getting what looks to be a .htpasswd / .htaccess password prompt, it stays up for 5-10 seconds, then it goes away, not sure where i should be looking for this in the logs? 

I am running the LetsEncrypt container redirecting all to https based on the guide in wiki.

I have confirmed the proxy-config for the plex site and no authentication is enabled?

Thanks for the great work team!

**Comment by nemchik** [comment]
Does this happen when you access it locally? (ex http://192.168.x.x:32400/ instead of the proxy address)

**Comment by daveb92** [comment]
Doesn't happen when I go direct, but proxy address it does still

**Comment by nemchik** [comment]
There may be something going in with the other files in your nginx config for the letsencrypt container. the other files you'd want to check would be in `~/.docker/config/letsencrypt/nginx/`. There's an `nginx.conf`, `proxy.conf`, `ssl.conf`, `site-confs/default` and maybe more. Any of those that have auth in them could affect the plex proxy. It's also possible that another proxy config file you have in the proxy-confs folder could be causing it.

**Comment by daveb92** [comment]
Found it! I had organizr installed, I have since removed it, but had left the organizr config folder under the proxy-confs with `auth _basic "Restricted" `turned on.. leaving file active, but commenting these lines out fixes the problem! 
thanks for the pointers sorry to waste your time, appreciate the help!

**Comment by nemchik** [comment]
No worries! Glad you have it working.
