### ISSUE TITLE
Configure Beets

### ISSUE THREAD

**Issue by bentux** [GhostWriters/DockSTARTer#632]
Hi,
I just need more informations about the Beets configuration.
If I just run Beets after install, nothing (music) is display.
If I try to change the configuration in the docker-compose.yml changing the ${MEDIADIR_MUSIC} from /music to /shared/Media/Music nothing is diplay...
The same with the config.yalm.

Thanks in advance

**Comment by nemchik** [comment]
The `docker-compose.yml` file is not meant to be modified. DockSTARTer will overwrite it when it recreates the file which happens anytime you run `ds -c`. Within DS GUI or your `~/.docker/compose/.env` file you can edit `MEDIADIR_MUSIC` to point to `/shared/Media/Music` and then your apps will see that folder mapped to `/music`. This is how Docker (not specifically DS) handles mapping folders into containers. One big benefit of doing it this way is that if you ever move your media to a new disk and mount it as `/shared2/Media/Music` you only need to adjust your variable and then recreate your containers (`ds -c` does this if you change a variable) and all your apps will still be able to see `/music` and not need to be reconfigured to point to your new folder.

The same would apply to all other `MEDIADIR_` folders, and the `DOWNLOADSDIR` (which maps to `/downloads`). If you need any more information feel free to ask. I'm going to close this but you can of course still comment. We're also very active on Discord and you can chat with us there for support as well.

**Comment by bentux** [comment]
Thanks for the reply. My Mediadir were already ok and work well with Plex.
It was a specific url or just myserver.com:8337?
I have just a blank page with beets at the right top corner for now...

**Comment by nemchik** [comment]
try http://lan.ip:8337/
