### ISSUE TITLE
Goaccess Addition

### ISSUE THREAD

**Issue by mattgphoto** [GhostWriters/DockSTARTer#641]
**Describe the solution you'd like**
Addition of https://goaccess.io/download#docker to DockSTARTer

**Additional context**
After getting started with DockSTARTer, I'm now using it as my main reverse proxy. With this in mind, a lot more traffic will start going through it. in addition to monitoring logs on command line, this would give me a sort of 'at a glance' view as to how much traffic each service is using, and could be handy for those using DS and public services (organizr, heimdall, etc) to see statistical/log information.

**Comment by UnR34L** [comment]
DS already supports an application that does the same thing: https://github.com/netdata/netdata

**Comment by nemchik** [comment]
We also have both Radarr and Couchpotato, Sonarr and Sick(whatever it's called now), and various other options that have alternatives. We can look into including this in DS. Sorry I've been fairly  busy and have not had time to look into it myself.

**Comment by mattgphoto** [comment]
> DS already supports an application that does the same thing: https://github.com/netdata/netdata

Not to be a nagger, but netdata _doesn't_ do the same thing. It does some of what Goaccess does, but not all of it. Netdata can show you current nginx active connections and requests. Goaccess shows bandwidth usage, valid/failed requests, unique visitors, information you'd want to know by looking at the logs, but without having to stare at the access.log itself.

**Comment by mattgphoto** [comment]
> We also have both Radarr and Couchpotato, Sonarr and Sick(whatever it's called now), and various other options that have alternatives. We can look into including this in DS. Sorry I've been fairly busy and have not had time to look into it myself.

No worries, been looking into trying to do this via override for a while now, and may end up going with a different solution that might be easier: https://github.com/GregYankovoy/docker-goaccess

**Comment by mattgphoto** [comment]
Got a working override now on this and rp config.

**Comment by nemchik** [comment]
Keep this

**Comment by dutran88** [comment]
Tried instructions from https://dockstarter.com/advanced/overrides/ 

Doesn't work :(

**Comment by dutran88** [comment]
I got it to work: here's my override.yml

`
version: "3.4"  # this must match the version in docker-compose.yml 

services:                                                                                                                
 letsencrypt:                                                                                                             
 volumes:                                                                                                                  
- ${DOCKERCONFDIR}/guacamole/logs/:/var/log/guacamole/                                                                  - ${DOCKERCONFDIR}/goaccess/logs/:/var/log/goaccess/

  goaccess:
    container_name: goaccess
    image: gregyankovoy/goaccess
    hostname: ${DOCKERHOSTNAME}
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    ports:
    - 7889:7889
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/goaccess:/config:rw
    - ${DOCKERCONFDIR}/letsencrypt/log/nginx/:/opt/log:ro

`

**Comment by nemchik** [comment]
So I'm a bit torn on this.

- First concern is the official image seems a bit unclear in the documentation with regards to getting what the `gregyankovoy` does.
- Second without adding the letsencrypt log folder this container seems like it doesn't really do much.

I don't love the idea of having this container depend on the letsencrypt container for a few reasons. Can other container logs be used? Can multiple container logs be used at the same time?

I'm ok with the idea of having just the base of the container and requiring overrides to add the logs from other containers. This means this container would require some additional attention to setup, but it wouldn't be the only one.

Thoughts?

**Comment by mattgphoto** [comment]
1. The official image has websockets running on a different port, IIRC. greg made it so you don't need to set a different port/page for it.
2. Correct. goaccess is just for any/all web logs. Apache, Nginx, CloudFront, etc.

Any web logs can be used. Not necessarily letsencrypt logs. I use it for letsencrypt logs myself, so I can easily see where accesses are from (China mostly) and what they're trying to do. (access .cfg files that don't exist in my case)

As for base of container being setup, sounds fine!
