### ISSUE TITLE
Use of `exec' to avoid masking exit codes

### ISSUE THREAD

**Issue by phenonymous** [GhostWriters/DockSTARTer#648]
See: https://github.com/GhostWriters/DockSTARTer/pull/646#discussion_r276299870

The current implementation of recursive script calling hides the exit codes of those script:
```bash
# example 1
(bash script.sh) || true
exit
```
This will cause the parent script to always exit with code 0 and thereby masking the exit code of the child script. A possible solution is the following
```bash
# example 2
(bash script.sh) || declare CHLD_EXIT=$?
exit ${CHLD_EXIT:-0}
```
While this does not mask the exit code of the child script, a better solution would be to not use child scripts at all and instead replace the current bash-process with a new one. By using `exec`, a bash built-in, the above examples can be avoided and the script will exit normally with the intended exit code. There is also a perfomace gain in using `exec` because it will keep number of processes to 1 and keep `SHLVL` at the same level no matter how many recursive calls. The higher `SHLVL` is, incrementing by 1 for every sub-shells spawned, the higher the impact will be on performance.
```bash
# example 3
exec bash script.sh
```

**Comment by nemchik** [comment]
I just did a quick search and the only places it looks like I've got a subshell followed by an exit are in main.sh

https://github.com/GhostWriters/DockSTARTer/blob/e30a3d8d5247631cf657c8ab3bfd0b6b59bffdcd/main.sh#L188-L189
https://github.com/GhostWriters/DockSTARTer/blob/e30a3d8d5247631cf657c8ab3bfd0b6b59bffdcd/main.sh#L200-L201
https://github.com/GhostWriters/DockSTARTer/blob/e30a3d8d5247631cf657c8ab3bfd0b6b59bffdcd/main.sh#L206-L207

The two with `|| true` (first and third examples) sound like they would be pretty easy to just replace with `exec ...`

In the case of the middle example I'm honestly not concerned at all with what the exit code is other than that it's not `0`. In that case I have the fatal to inform the user that their first run install was not successful. I've actually been considering doing something with the cleanup function to detect the exit code and possibly take additional actions or spit out warnings for non-zero exits. That could be done in place of the fatal there but it would be more generic as it would catch any failure, not just first run install failures.

Thoughts?

**Comment by nemchik** [comment]
Here's what I think you're wanting done: https://github.com/GhostWriters/DockSTARTer/commit/92c76916b3b26345a0a3e451a190dac7c0c400ee

**Comment by phenonymous** [comment]
It is still possible to have a fatal if the install was not sucessful. But since we replace the shell with a new one, the user still gets informed if something couldn't be installed and exits on error.

I like the idea of handling exit codes in a trap function. But just to clear so there's no confusing, when using `exec` traps in the script that called `exec` will never get triggered. They will however get triggered for the new shell.

I made some proposed changes to https://github.com/GhostWriters/DockSTARTer/commit/92c76916b3b26345a0a3e451a190dac7c0c400ee
