### ISSUE TITLE
Use terminal capabilities instead of hard-coded ANSII codes

### ISSUE THREAD

**Issue by phenonymous** [GhostWriters/DockSTARTer#649]
#### termcap
Terminal capability
#### terminal
The terminal the current terminal emulator is emulating.
Examples of terminals
* xterm
* xterm-256color
* screen

Examples of terminal emulators
* gnome-terminal
* putty

### Background
Using hard-coded ANSII codes, while widely used, is considered bad practice. This is because not all terminals implements ANSII codes the same way. So what you are trying to achieve with ANSII codes, be it coloring text for example, the results may not be consistent across different terminals.

### Solution
`tput(1)`, a front-end to `terminfo(5)` which is a database that holds all the termcaps for a large number of terminals, allows one to use termcaps on any terminals without needing to know the specific escape-sequence for said terminals. `tput setaf 1`, which tells the terminal to print any following text in red, ensures that the color will always be red no matter what terminal is in use provided that said terminal supports at least 8 colors. See https://github.com/phenonymous/DockSTARTer/commit/a0413f1271ad84dacf626f438ac021d4bc3761d2 for a possible solution

```diff
diff --git a/main.sh b/main.sh
index ddc0585..7bcc30d 100755
--- a/main.sh
+++ b/main.sh
@@ -73,11 +73,11 @@ readonly DETECTED_HOMEDIR=$(eval echo "~${DETECTED_UNAME}" 2> /dev/null || true)
 
 # Colors
 # https://misc.flogisoft.com/bash/tip_colors_and_formatting
-readonly BLU='\e[34m'
-readonly GRN='\e[32m'
-readonly RED='\e[31m'
-readonly YLW='\e[33m'
-readonly NC='\e[0m'
+readonly BLU="$(tput setaf 4)"
+readonly GRN="$(tput setaf 2)"
+readonly RED="$(tput setaf 1)"
+readonly YLW="$(tput setaf 3)"
+readonly NC="$(tput sgr0)"
 
 # Log Functions
 readonly LOG_FILE="/tmp/dockstarter.log"
```
The above proposed solution does not take into account when a terminal does not have the termcap to set the foreground color or restore default color. Altough this would be very rare it still has to be handled. A terminal that does not support colors does not necessarily mean the lack of `setaf` termcap, it would just be variations of white/gray/black.

There are numerous ways this can be handled, below are two possible solutions, which will just be an empty string in case of failure
```bash
readonly BLU="$(tput setaf 4 2> /dev/null)"
readonly GRN="$(tput setaf 2 || echo '')"
```

This is also a problem with the current implementation, there is no way telling what escpae sequence `\E[34m` will do on a terminal that does not support changing the foreground.

**Comment by nemchik** [comment]
I like this a lot. I think I prefer `readonly BLU="$(tput setaf 4 2> /dev/null)"` as it seems more deliberate.

**Comment by nemchik** [comment]
If there's no other important things to keep in mind about this would you mind making a PR?

**Comment by phenonymous** [comment]
No it is pretty straight forward. However, I will do some research on the "correct" way to handle missing termcaps.

**Comment by phenonymous** [comment]
Please take a look at https://github.com/phenonymous/DockSTARTer/commit/34aab1afb946123369c6bb6c08a48b02acb0dc96
I know it might seem too much but I sincerely do think this is the best way to handle it.
```bash
# Check if standard output is open and attached to a terminal.
[[ -t 1 ]]
```
cron will not pass this test so we just set the colors to empty strings
```bash
# Will write -1 to the standard output if the current terminal does not support colors. 
# The exit code is always 0 so the script won't exit if the terminal does not support colors.
tput colors
```

**Comment by nemchik** [comment]
I love the color logic, but tell be about
`if [[ -n ${PS1:-} ]] || [[ ${-} == *"i"* ]]; then` vs `if [[ -t 1 ]]; then`

**Comment by phenonymous** [comment]
That if statement will never be true. Demonstrated by this script
```bash
#!/usr/bin/env bash

# Will not trigger because running a script is never an interactive shell
if [[ ${-} == *"i"* ]]; then
	echo "Shell is interactive"
fi

# PS1 is only set for login- and interactive shells
if [[ -n $PS1 ]]; then
	echo "Prompt is available"
fi

if [[ -t 1 ]]; then
	echo "This will be visible, since this is a terminal and has a standard output"
fi
```

**Comment by phenonymous** [comment]
You could also use `tty -s` but that command is not always available but it is more straight forward because it will return 0 if the current process is a terminal and 1 if it is not.
```bash
if tty -s; then
    echo "I'm a terminal"
fi
```

**Comment by nemchik** [comment]
I don't like the idea that `tty` may not be available and would rather use the builtin. I did some testing and believe we should go with `if [[ -t 1 ]]; then`

**Comment by nemchik** [comment]
That being said if you would prep a PR with these changes (for color) and also swap the `if [[ -n ${PS1:-} ]] || [[ ${-} == *"i"* ]]; then` I've got inside main for `if [[ -t 1 ]]; then` we can run it through testing and merge it in!
