### ISSUE TITLE
Unable to connect Sickrage (sickchill) to a torrent client - [Errno 404] Not Found

### ISSUE THREAD

**Issue by mildfuzz** [GhostWriters/DockSTARTer#651]
After installing both deluge and transmission along side Sickrage, I am unable to run a successful test in sickrage torrent.

![image](https://user-images.githubusercontent.com/196705/56419190-5063ab80-6291-11e9-870c-70b073320bbb.png)

I have tried `localhost`, `0.0.0.0`, `127.0.0.1` and the machines local IP and hostname along side the correct ports. Torrent services are running and accessible via web clients.

My suspicion is that the sickrage container isn't able to call out for some reason, but I am not sure how I can evidence this.

**Comment by phenonymous** [comment]
`localhost`, `0.0.0.0` and `127.0.0.1` all points to the container itself, in this case sickrage.

Try this from a terminal
```console
# docker ps -q | xargs -n 1 docker inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} {{ .Name }}' | sed 's/ \// /'
```
This will list all containers and their docker-ip. From that list, try using the ip for transmission instead. If that does not work, try using the host ip instead. You can get that from
```console
$ ip route show
```

**Comment by nemchik** [comment]
Useful command, but you'll want to use the the container hostname. The container IPs are dynamic.

**Comment by phenonymous** [comment]
Also, I see why this might be confusing. From the computer that hosts the docker containers, all network routing is handled by docker. This is why when you go to portainer for example, `http://localhost:9000`, docker routes the traffic from your computer to the docker container. But when you are inside the container, for example if you got to portainer and want to add another endpoint and you use `localhost`, that will no longer point to your computer, it will be portainer itself.

This is a security measure. Think of it as you can see into a container but the container can't see out.

**Comment by mildfuzz** [comment]
That command is super useful, thanks :)
