### ISSUE TITLE
Do not force install dependencies

### ISSUE THREAD

**Issue by phenonymous** [GhostWriters/DockSTARTer#662]
From `run_script.sh`
```bash
# part of
run_install() {
    run_script 'install_docker' force
    run_script 'install_compose' force
    run_script 'install_yq' force
}
```
There might be some users that already have `docker` or `docker-compose` installed and do not want that version removed. Like myself for example; I use `docker.io` inside `lxc` containers because `docker.io` is tweaked to work better in containers than the official version.
I use DS because it is easy to get all the apps up and running quickly, kudos, but I always have to remove the `docker` version DS force installs and reinstall `docker.io`. The same goes for `docker-compose` for which I download the binary directly - usually because I run on systems that don't have python.

The problematic code is this line; which is the same for all above scripts
```bash
# Replaced with PROGRAM to generalize
if vergt "${AVAILABLE_PROGRAM}" "${INSTALLED_PROGRAM}" || [[ -n ${FORCE} ]]; then
``` 
which will always be true no matter what. I do not think it is good to force install if a user don't want to without asking to confirm first.
I'm taking a leap here and guess that the "force" argument is for Travis? If so then I would propose the following change
```diff
diff --git a/.scripts/install_docker.sh b/.scripts/install_docker.sh
index 0af9392..5e65242 100644
--- a/.scripts/install_docker.sh
+++ b/.scripts/install_docker.sh
@@ -18,27 +18,34 @@ install_docker() {
         fi
     fi
     if vergt "${AVAILABLE_DOCKER}" "${INSTALLED_DOCKER}" || [[ -n ${FORCE} ]]; then
-        if [[ -n "$(command -v snap)" ]]; then
-            info "Removing snap Docker package."
-            snap remove docker > /dev/null 2>&1 || true
+        if [[ ${TRAVIS:-} != "true" ]] && [[ -z ${FORCE} ]]; then
+            info "Found installed Docker version ${INSTALLED_DOCKER} but can be updated to ${AVAILABLE_DOCKER}"
         fi
-        info "Installing latest docker. Please be patient, this can take a while."
-        local GET_DOCKER
-        GET_DOCKER="$(mktemp)"
-        curl -fsSL get.docker.com -o "${GET_DOCKER}" > /dev/null 2>&1 || fatal "Failed to get docker install script."
-        sh "${GET_DOCKER}" > /dev/null 2>&1 || fatal "Failed to install docker."
-        rm -f "${GET_DOCKER}" || warning "Temporary get.docker.com file could not be removed."
-        local UPDATED_DOCKER
-        UPDATED_DOCKER=$( (docker --version 2> /dev/null || echo "0") | sed -E 's/.* version ([^,]*)(, build .*)?/\1/')
-        if vergt "${AVAILABLE_DOCKER}" "${UPDATED_DOCKER}"; then
-            #TODO: Better detection of most recently available version is required before this can be used.
-            echo # placeholder
-            #fatal "Failed to install the latest docker."
+        if [[ ${TRAVIS:-} == "true" ]] || run_script 'question_prompt' Y "Do you want update Docker?"; then
+            if [[ -n "$(command -v snap)" ]]; then
+                info "Removing snap Docker package."
+                snap remove docker > /dev/null 2>&1 || true
+            fi
+            info "Installing latest docker. Please be patient, this can take a while."
+            local GET_DOCKER
+            GET_DOCKER="$(mktemp)"
+            curl -fsSL get.docker.com -o "${GET_DOCKER}" > /dev/null 2>&1 || fatal "Failed to get docker install script."
+            sh "${GET_DOCKER}" > /dev/null 2>&1 || fatal "Failed to install docker."
+            rm -f "${GET_DOCKER}" || warning "Temporary get.docker.com file could not be removed."
+            local UPDATED_DOCKER
+            UPDATED_DOCKER=$( (docker --version 2> /dev/null || echo "0") | sed -E 's/.* version ([^,]*)(, build .*)?/\1/')
+            if vergt "${AVAILABLE_DOCKER}" "${UPDATED_DOCKER}"; then
+                #TODO: Better detection of most recently available version is required before this can be used.
+                echo # placeholder
+                #fatal "Failed to install the latest docker."
+            fi
+        else
+            warning "New version of Docker will not be installed, this might cause issues"
         fi
     fi
 }
 
 test_install_docker() {
-    run_script 'install_docker'
+    run_script 'install_docker' force
     docker --version || fatal "Failed to determine docker version."
 }
```
```diff
diff --git a/.scripts/run_install.sh b/.scripts/run_install.sh
index 331e29c..c13ccf6 100644
--- a/.scripts/run_install.sh
+++ b/.scripts/run_install.sh
@@ -4,7 +4,7 @@ IFS=$'\n\t'
 
 run_install() {
     run_script 'update_system'
-    run_script 'install_docker' force
+    run_script 'install_docker'
     run_script 'install_machine_completion'
     run_script 'setup_docker_group'
     run_script 'enable_docker_systemd'
```

edit: proposed change only includes docker as an example, but it would be the same for the others

**Comment by phenonymous** [comment]
After further inspection this expands over multiple scripts. I made some changes and tested it and it works as expected. Here's some output

#### Older Docker version found, user wants to keep that version
![Screenshot from 2019-04-23 10-40-15](https://user-images.githubusercontent.com/29523105/56567590-8c5e7f80-65b5-11e9-96ff-6dcd97acdea7.png)

#### Older Docker version found, user wants to update
![Screenshot from 2019-04-23 10-45-05](https://user-images.githubusercontent.com/29523105/56567684-c039a500-65b5-11e9-85aa-065a6883ae2f.png)

#### The output of `ds -i` when DS installed Docker for you already
![Screenshot from 2019-04-23 10-47-32](https://user-images.githubusercontent.com/29523105/56567745-db0c1980-65b5-11e9-9aba-f8ee5cfb3265.png)

**Comment by phenonymous** [comment]
The above output can be viewed here, with some minor language improvements https://github.com/phenonymous/DockSTARTer/tree/v0.6-alpha-%23662

**Comment by nemchik** [comment]
`FORCE` actually isn't for Travis at all. When DS runs `generate_yml` it needs to be able to use `yq` and so it runs `install_yq` without `FORCE` which checks for the installed version and the available version and only runs the install if a newer version is available. The other installs work the same way. So for example if you're running a beta version of docker-ce (with a higher version number than the most recent stable release) you'll always be ahead and `install_docker` won't ever end up doing anything.

The `test_*` functions at the bottom of each script are for Travis (or any other CI/CD or even local) tests. Those instructions Travis to run the functions required to confirm the code is working. Right now we're only considering a non-zero exit to be a failure. I'm the future these can be expanded to do more involved unit tests. The code that runs the tests is in main.sh

**Comment by phenonymous** [comment]
Alright so I was wrong about force for Travis but really, that is not what the issue is about. I can expand further unless your comment was only about Travis and force?

**Comment by nemchik** [comment]
Anyway I'm not opposed to discussing this idea. I think it would be a good thing to do but I've (as usual) got some requirements:

- we need a consistent way to determine if the user has the dependency already. Not just installed, but compatible with what DS needs.
- currently we run the installs if there's a newer version. We can reconsider defining minimum (and possibly maximum) versions and only run the installs if the requirements aren't met, or we keep it like it is which will keep the dependencies up to date anytime the users run DS

**Comment by nemchik** [comment]
Yeah the first comment was only about travis. I began typing the second and had to leave for work so I just was able to finish sending it (and I can't remember if I had more thoughts on the matter but that's what I've got so far).

**Comment by phenonymous** [comment]
> So for example if you're running a beta version of docker-ce (with a higher version number than the most recent stable release) you'll always be ahead and install_docker won't ever end up doing anything.

Please correct me if I'm wrong but say you have a beta version of Docker and pretend it is 2 and the stable release of Docker is version 1. Then
```bash
if vergt "${AVAILABLE_DOCKER}" "${INSTALLED_DOCKER}" || [[ -n ${FORCE} ]]; then
# 1 > 2 This is false
# -n ${FORCE} this is always true since -n returns "True if the length of string is non-zero."
```
Because of the `||` which just requires one test to be true and of them is always true since running the install script will install docker with this argument `run_script 'install_docker' force`.
The test might as well just be
```bash
if [[ -n ${FORCE} ]]; then
```

**Comment by phenonymous** [comment]
And again
> After further inspection this expands over multiple scripts.

It is just not the `install_docker.sh` but `update_system.sh` and `run_{apt,dnf,yum}.sh` also. Those scripts removes all docker packages except for docker-ce which is what DS installs for you. Because those scripts runs before `install_docker.sh` the user never get the chance to decide what to do, DS decides for you.

Please look at my tag and you can test it yourself. Also as shown in the first image attachment, it throws a warning if you decide to keep the version of docker already installed. So at that point the user has been warned. I fail to see, just like forcing the location DS should be in, why DS should force which version of docker to use?

**Comment by nemchik** [comment]
test.sh
```bash
#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

vergte() { printf '%s\n%s' "${2}" "${1}" | sort -C -V; }
vergt() { ! vergte "${2}" "${1}"; }
verlte() { printf '%s\n%s' "${1}" "${2}" | sort -C -V; }
verlt() { ! verlte "${2}" "${1}"; }

install() {
    local AVAILABLE=1
    local INSTALLED=2
    local FORCE=${1:-}
    if vergt "${AVAILABLE}" "${INSTALLED}" || [[ -n ${FORCE} ]]; then
        echo "Condition has been met."
    else
        echo "Condition has NOT been met."
    fi
}

echo "Install without force."
install
echo
echo "Install with force."
install force

```

results
```bash
baines@yori:~$ bash test.sh
Install without force.
Condition has NOT been met.

Install with force.
Condition has been met.
```

**Comment by phenonymous** [comment]
Exactly, so if you have a higher version of docker and force is not set it wont do anything. But in production you have force so it will install docker no matter what.

**Comment by nemchik** [comment]
Yes, but we don't always use force, and the install itself will not remove docker-ce, so if you've already got a higher version of docker-ce installed the install will still run but nothing really happens.

I'm not saying that's the best solution, but it's not caused any major issues up to this point. Like I said above if we can meet some requirements then I'm ok with changing how this is handled.

**Comment by phenonymous** [comment]
I'm sorry but I'm not very fond of that answer. The docker install override depends on what you set it to between updates?

We are making different assumptions here. You are letting the external docker install script handle versioning, which is fine for docker-ce.
But that assumption is not within the scope of this issue.

I get what you are doing with force but I don't know how it was meant to be dealt with from the users point of view, are we supposed to edit the script?

While it has not caused any issues before, it has for me, an avid user, and I don't think I'm the only one. Hence why I'm raising this issue.

Also while digging through this I noticed that DS removes packages silently, an entire different issue but it had to be handled to make my proposed change work.

One really should not remove anything without prompting first.

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by phenonymous** [comment]
I'll keep working on this to fufill your requirements and get back to you when I have a new tag ready

**Comment by nemchik** [comment]
The external script is officially supported by docker. It uses the package manager on your system to install docker-ce or if there is a new version available it will update you to that version. That's just basic behavior for the supported package managers (apt, dnf, and yum). For any package where you send the `install` directive it will install the latest available version if you don't already have it (which effectively is an upgrade ifyou do already have it).

For the purpose of what you're getting at with this issue I agree this method is not ideal because we are only supporting docker-ce when in reality it is possible for DS to function with other releases of docker. At this point based on https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix we require Docker Engine 17.09.0+ because we have our compose file using version 3.4 and we do actually make use of some features up to 3.3 if I remember correctly. Also it looks like docker-compose did not support version 3.4 until compose version 1.17.0 which I was only able to dig out by reviewing their releases on github. The docker engine does not have to be docker-ce, that was just the easiest for DS to get working in a wide capacity for end users (given the officially supported script).

Users are not meant to edit the script. At this point users are meant to use docker-ce in order to use DS. That may change based on the outcome of the discussions and development here.

I half-heartedly agree about not removing packages silently. We actually ran a poll in discord and users voted that DS should not prompt when running `ds -i` and other commands like that. The GUI still does prompt for many things. The prompts (GUI, and previously CLI) do not indicate that packages would be silently removed, only that DS will install dependencies. Some other places where we silently remove things that are incompatible with DS are in `install_docker` we remove the docker snap package, and in `install_compose` we remove any existing docker-compose and use pip to uninstall `docker-py` as it is incompatible with docker-compose when installed via pip which has thus far proven to be the most reliable way to install compose. We used to install compose using the binary but docker does not officially offer precompiled binaries for ARM CPUs.

So circling back to the idea of not force installing dependencies: as long as we can confirm that the user has a version of docker and compose that meet the minimum requirements of DS itself (that may change in the future - we might up the compose file versions to something newer than 3.4 at some point) then I'm ok with not requiring the specific install methods DS uses, but we have to account for "what if they have docker, but it's an older version that does not meet DS minimum?" we are not going to cover upgrading every distribution of docker that the users might have, but prompting to install/upgrade the one method we will support would be fine (and would need to remove incompatible installations of docker as it currently does). That logic applies as well to compose. yq is a bit of a different story because there are other distributions of yq around but they do not all behave the same and have the same options. The one we are using is the most minimal I could find and only installs a binary. The other major yq distribution installs via python pip and has other dependencies (it relies on jq as well) so I'm not convinced on switching to that one or allowing it in place of the one we currently use because it's not an exact match for how we use it (like I said they behave differently).

**Comment by phenonymous** [comment]
I see there's alot more to it after your explanation. So after reading this I gather that there are 3 real dependencies.

1. `docker` - self explanatory why it's needed. The main dependecy is No.2
2. `docker-compose` - needed to run the generated yaml for apps to run. The version needed depends on the individual app parts. And this in turn puts a minimum requirement for which version of docker to use.
3. `yq` - to process all yaml

So I don't have an issue with `yq` being forced installed, it should not cause issues for anyone mainly because; It is not packaged by any distribution - I don't consider brew/snap/adding ppa to count as being packaged by a distribution.

I do not see an issue with force installing `docker-compose` either other than it uses `pip`. On the top of my head I don't know if `pip` is used for any other purposes than docker-compose - if it isn't then maybe that could be phased out in favour of the binary (which I think is what `pip` is downloading). Also, I might be wrong on this, but when running `install_compose.sh` bash is in sudo mode and hence python will run with privileged rights. This causes `pip` to install any packages as a global package located somewhere in `/etc/pythonXX/../site-packages` instead of a user package located, usually, in `$HOME/.local/bin/../site-packages`. Again I might be wrong on python running with privileged rights.
If it is true then that would be a different issue not related to this. Not unless `pip` is only used for `docker-compose` and what I said is true - and, if you would agree we should pull the binary directly, then that would be in the scope of this isse.

The main issue is the forcing of what docker package to use. But, I have a revised proposal based on this thread. How about this;

Declare a global variable `COMPOSE_YML_VERSION` or something, give it the value of the current compose version used by DS and put in `main.sh`
```bash
# main.sh
readonly COMPOSE_YML_VERSION="3.4"
```
let the yaml in `compose/.reqs` read from that variable
```yml
# v2.yml
version: "${COMPOSE_YML_VERSION}"
```
*I suppose this is not necessary but my reasoning is that you'd only have to do versioning in one place.*

Now, that we know what compose version to use we can scrape https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix to get the minimum required docker version for DS to run sucessfully. Combining this with the progress I already made (mainly not removing all docker packages except docker-ce before we know what version is installed, if any) we can compare if the installed version of docker meets the minimum required version.
Then, assuming docker already exists;

- If it meets the requirement, good
- If it does not meet the requirement then remove the old docker and install `docker-ce`

We remove the old docker package by using the universal removal I made in `install_docker.sh`. We do not try to figure out what the package name of the installed docker and update it - that is too complex and besides it should already be latest available docker after `update_system.sh`. Instead,  we install `docker-ce` using the method that is currently used today. 

For `docker-compose`, I guess we could force install to latest compose, however, if `docker-compose` already is installed then maybe we could detect if it was downloaded directly or by using `pip` and then determine the update method (`curl` or `pip`). 

I'm not entirely sure how to handle this, because it all depends. I'll have to do some research wether `docker-compose` is backwards compatible. If it is then force installing/updating compose is fine - if it is not then that's an issue, and that is an issue for the current version of DS also.

Another way is doing something like the handling existing `docker` version, as proposed in this comment. But then you would have to do some reverse-engineering on finding the minimum `docker-compose` version required for the current version of 'compose file format' used, as there does not seem to be a compatibility matrix between `docker-compose` and the file format version. To see what I mean, look at https://github.com/docker/compose/releases - docker-compose version `1.22.0` was the first version to introduce file format version `3.7`, you can see whater version of docker you need to have but there's no telling that in order to use `3.7` you need at least version `1.22.0` of docker-compose.

And that is why, if it is backwards compatible, it might be enough to just force update to the latest `docker-compose`

**Comment by nemchik** [comment]
I see there has been some edits to the comments here but I just noticed them right now. I'll have to come back and read what's been changed (don't have time right this second).

**Comment by nemchik** [comment]
If #726 doesn't fully address the needs here we can reopen or make a new issue for something that would follow up on this.
