### ISSUE TITLE
View connection / configuration for apps

### ISSUE THREAD

**Issue by nigelhooper** [GhostWriters/DockSTARTer#665]
**Is your feature request related to a problem? Please describe.**
I am have just migrated to DockSTARTer from AtomicToolKit (ATK), ATK has a menu option to view the configuration for installed apps, I cant see an equivalent in DS.

**Describe the solution you'd like**
A menu option that shows me the urls and default usernames and password etc for the applications I have installed

**Describe alternatives you've considered**
Googling default settings for all the apps, paying attention when installing DS rather than blindly accepting the defaults without reading them :-)

**Additional context**

**Comment by nemchik** [comment]
This is a good idea, we'll have to determine how to keep this manageable over time though. I have some thoughts on how to handle this such as including it as comments in the yml files for each app where it would be applicable.

**Comment by nemchik** [comment]
Keep this.

I've actually just recently merged in some major changes that should make maintaining this type of information possible and not too difficult to keep up with over time. I've got plenty I still want to get done before taking this on, but the ground work is laid and everything has been smooth so far.

**Comment by nemchik** [comment]
Keep this
