### ISSUE TITLE
BitWarden Documentation

### ISSUE THREAD

**Issue by nemchik** [GhostWriters/DockSTARTer#666]
Relocating https://github.com/GhostWriters/DockSTARTer-wiki/issues/8

We need a page for Bitwarden explaining that the config folder will be created with root ownership but can be chowned to whatever user if desired.

**Comment by salvationtower** [comment]
I'm happy to do something for one.

**Comment by nemchik** [comment]
Please submit a PR to the add the file here https://github.com/GhostWriters/DockSTARTer/tree/docs/docs and navigation link in this file https://github.com/GhostWriters/DockSTARTer/blob/docs/mkdocs.yml

**Comment by nemchik** [comment]
Closed via #673
