### ISSUE TITLE
Documentation for all apps

### ISSUE THREAD

**Issue by nemchik** [GhostWriters/DockSTARTer#676]
I think we should make a documentation page for every app in DS whether we have something special to say about it or not. Each page should have at least some basic instructions about where the app can expect to see files like `/movies` or how to connect it to other apps (ex: on the page for ombi explain to enter `sonarr` as the hostname to connect to sonarr and stuff like that).

Each app page should be included in the navigation and the filenames should be lowercase.

**Comment by nemchik** [comment]
This is open to anyone to contribute, even one page at a time. Help is welcome.

**Comment by nemchik** [comment]
I've started a branch to create placeholder pages for all apps that are currently missing pages.

**Comment by nemchik** [comment]
#700 has created placeholder pages, but I'd like to keep this open until a decent majority of the pages have real content

**Comment by nemchik** [comment]
Keep this

**Comment by mjmaurer** [comment]
Are the docs open source?

**Comment by nemchik** [comment]
Yes. https://github.com/GhostWriters/DockSTARTer.com

Also just visiting the pages of https://dockstarter.com/ you'll see edit buttons on the top right corner of every page. Changes are reviewed and approved before becoming live.

**Comment by nemchik** [comment]
This will be ongoing and doesn't need an issue here.
