### ISSUE TITLE
Change basepath for all Media types.

### ISSUE THREAD

**Issue by chriscn** [GhostWriters/DockSTARTer#681]
**Is your feature request related to a problem? Please describe.**
It is frustrating to manually add `/media/external/Media` in front of all my media types.
**Describe the solution you'd like**
Setting a base path and set the different Media types after the base paths.

**Comment by nemchik** [comment]
To be clear are you talking about how the paths are represented inside the containers? For example you set DS `MEDIADIR_TV` variable to `/media/external/Media/tv` and the apps inside containers will see `/tv`. If I'm understanding your request you want the app on the inside to see `/media/external/Media/tv` ?
