### ISSUE TITLE
Password protect Rutorrent

### ISSUE THREAD

**Issue by silveringking** [GhostWriters/DockSTARTer#682]
Recently I've installed rutorrent and I tried to password protect it, I tried to install nginx and password protect my rutorrent, obvious didn't work, you can't password protect an image running on docker...

Anyway I thought it would be a cool feature password protect rutorrent/rtorrent, since this is pretty exposed.

What do you say?

**Comment by nemchik** [comment]
ruTorrent runs via nginx and the configs for it should be inside your config/appdata folder. You can add http auth to that and it'll require a username and password.
