### ISSUE TITLE
Portainer Agent

### ISSUE THREAD

**Issue by mouzzampk2014** [GhostWriters/DockSTARTer#697]
Hi, I have couple of machines running DockSTARTer one with Portainer and the other one without Portainer. But I think we can set Portainer Agent on second machine so on first machine Portainer can read the information? Any ideas how can I do that? Thank you so much

I can enable Portainer Agent on Second Machine. But how first machine will communicate with second machine?

```### PORTAINERAGENT
PORTAINERAGENT_ENABLED=false
PORTAINERAGENT_BACKUP_CONFIG=true
PORTAINERAGENT_NETWORK_MODE=
PORTAINERAGENT_PORT_9001=9001

**Comment by nemchik** [comment]
In portainer there's an option to connect a new host using portainer agent. It just asks for host name or IP address I think.

**Comment by billotronic** [comment]
Endpoints -> Add Enpoint -> Fill in info -> Smile
