### ISSUE TITLE
Addition of BiglyBT

### ISSUE THREAD

**Issue by raz4725** [GhostWriters/DockSTARTer#720]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. I am a long time Azureus -> Vuze user and BiglyBT is the latest in that trend of software.

**Describe the solution you'd like**
It looks like there's a docker package for BiglyBT and OpenVPN/VNC @ https://hub.docker.com/r/fullaxx/biglybt. 

To be honest, a split VPN (either make only way to access would be reverse proxy, for instance, and all traffic is VPN, or make the container accessible internally, but block all torrent traffic in and out that isn't VPN) to access the web portion would suffice (guides on HTPCGudies to do this with Transmission), but this adds extra functional.

**Describe alternatives you've considered**
No such alternative exists as far as I know. There were guides to split VPN on Linux, but not sure if there's one in DS. BiglyBT has some cool pluses that other clients don't have, as well, and a few that will get me flak. Ask me about it on Discord if you're wondering what I mean.

**Additional context**
N/A

**Comment by nemchik** [comment]
Keep open

**Comment by nemchik** [comment]
Sorry I haven't gotten to this, I've been pretty busy with work. I'm not opposed to it being added to the roster. Pull requests welcome.
