### ISSUE TITLE
Please add Piwigo

### ISSUE THREAD

**Issue by mjwitter** [GhostWriters/DockSTARTer#721]
**Is your feature request related to a problem? Please describe.**
This is a feature request to please add the Piwigo docker image to Dockstarter. Piwigo is open source photo gallery software for the web. Designed for organisations, teams and individuals.

**Describe the solution you'd like**
Could you please add the linuxserver docker image of Piwigo - https://hub.docker.com/r/linuxserver/piwigo/

**Comment by nemchik** [comment]
Keep this

**Comment by hannonq** [comment]
+1 to this idea :)
