### ISSUE TITLE
chmod: cannot access '/usr/local/bin/docker-compose': No such file or directory

### ISSUE THREAD

**Issue by eekfonky** [GhostWriters/DockSTARTer#74]
HypriotOS/armv7: pirate@black-pearl in ~
$ sudo bash ~/.docker/main.sh -g

[INFO]        Would you like to run your selected containers now?
[Yn]y
chmod: cannot access '/usr/local/bin/docker-compose': No such file or directory
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by TommyE123** [comment]
It sounds like `Docker-Compose` didn't install correctly in the previous step.

Did you run `sudo bash ~/.docker/main.sh -i` and reboot without any errors?

What do you get if you run `docker-compose --version`?

**Comment by eekfonky** [comment]
No, it appears it didn't install correctly;

```
HypriotOS/armv7: pirate@black-pearl in ~
$ sudo bash ~/.docker/main.sh -i
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:3 https://download.docker.com/linux/raspbian stretch InRelease
Hit:4 https://packagecloud.io/Hypriot/rpi/debian stretch InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12211  100 12211    0     0  11816      0  0:00:01  0:00:01 --:--:-- 11832
chmod: cannot access '/usr/local/bin/docker-compose': No such file or directory
```

**Comment by TommyE123** [comment]
I hope you don't mind but I've added you to the support chatroom on [Gitter](https://gitter.im/GhostWriters/DockSTARTer), Let me know when you have a few mins and we can get it up and running with you :smile:

**Comment by nemchik** [comment]
Ended up we needed to install compose a different way

```
sudo apt-get remove docker-compose
sudo apt-get install python-pip
sudo pip install docker-compose
```

This may be true for all ARM systems, or only for some specific OS. We'll investigate more as time allows and keep this issue open until a change is made that would resolve it properly.

**Comment by nemchik** [comment]
The fix for this issue it's now merged into master.
