### ISSUE TITLE
Add support for Fedora 30

### ISSUE THREAD

**Issue by UnR34L** [GhostWriters/DockSTARTer#742]
https://download.docker.com/linux/fedora/30/x86_64/stable/Packages/

If you do, maybe open https://github.com/GhostWriters/DockSTARTer/issues/678 ?

**Comment by nemchik** [comment]
https://docs.docker.com/install/linux/docker-ce/fedora/
30 is not yet officially supported by docker-ce. You may be able to get https://test.docker.com installed which would allow DS to work.

29 works fine and does not have the permissions issue seen in #678 but if 30 still has this issue after being added to the list of officially supported platforms I'll have another look at fixing it.
