### ISSUE TITLE
When containers are recreated/upgraded they use 'compose_default' network instead of 'bridge'

### ISSUE THREAD

**Issue by LandonStewart** [GhostWriters/DockSTARTer#752]
**Describe the bug**
When the containers are recreated due to updates (I think) they are recreated using the `compose_default` network instead of the `bridge` network despite the `docker-compose.override.yml` file.

I can fix this by changing all of the containers to the bridge network manually via:
```
$ docker container list | awk '{ print "docker network connect bridge " $1  }' | grep -v CONTAINER  | sh
$ docker container list | awk '{ print "docker network disconnect compose_default " $1  }' | grep -v CONTAINER  | sh
```

I'd rather not have to do that though of course.

**To Reproduce**

1. Unfortunately I don't know how to force the containers to be recreated so I cannot provide this

**Expected behaviour**
I'd expect the network to be used by the containers to always stay as `bridge` instead of changing because I have the following in .docker/compose/docker-compose.override.yml:
```
version: "3.4"
networks:
  default:
      driver: bridge
```

**System (please complete the following information):**

- OS: `Ubuntu`
- Version `18.04.2 LTS`

**Additional context**
I'm using the ouroboros container which is probably how the containers are getting recreated when they need to be updated.

**Comment by nemchik** [comment]
DS actually does not specify a `network` or `network_mode` by default which results in docker-compose deciding to add all created containers to a "user defined" bridge network named `<foldername>_default`. In our case the `docker-compose.yml` file exists in a folder named `compose` so the resulting network is `compose_default`.

So what you're seeing is containers are in fact in bridge mode, and seem to be working as expected (default behavior for docker-compose).

The default bridge network (simply named `bridge` and not `compose_default`) is not considered a user defined network and lacks DNS resolution between containers. For example two containers using the default bridge (for example let's say sonarr and letsencrypt) cannot run something like `docker exec letsencrypt curl http://sonarr:8989/` (thus proving that the containers can resolve by name) however on the `compose_default` network this would be successful.

So to reiterate, `compose_default` is a user defined bridge network that should function just the same as the built-in default `bridge` network but also include DNS resolution between containers. If you are trying to troubleshoot an issue with the way this works please join our Discord for assistance. https://discord.gg/YFyJpmH

**Comment by LandonStewart** [comment]
For anyone else having this problem...

Create a file `~/.docker/compose/docker-compose.override.yml` with the following for each container you want to override the network for:

```
version: "3.4"
services:
  ombi:
    network_mode: bridge
  sonarr:
    network_mode: bridge
```

Then recreate all your containers via:
`$ sudo ds -c down; sudo ds -c pull; sudo ds -c up`

**Comment by nemchik** [comment]
I would recommend against the `network_mode: bridge` override you have mentioned.

First, you can simply set the variables for each app in `~/.docker/compose/.env` for `<appname>_NETWORK_MODE` to `bridge` (ex: `SONARR_NETWORK_MODE=bridge`) and this would accomplish what you have posted.

Second (and this is the more important one!) using the `bridge` network mode prevents created apps from being added to the `compose_default` bridge network which allows for DNS resolution. The `bridge` and `compose_default` networks are both bridge networks, both use defined ports, both allow you to remap ports, etc. The difference is `bridge` does not do DNS name resolution, so in Sonarr you cannot setup nzbget or deluge by simply typing their name for the hostname, you have to type your host IP address, which is not ideal (especially if you have DHCP and your system IP might change). If you use the `compose_default` network it will do everything that the `bridge` network does PLUS you can just enter the app names to connect. Here are screenshots to illustrate my point:

Using `compose_default` (do not use an override, and leave `<appname>_network_mode` blank):
![image](https://user-images.githubusercontent.com/725456/60919545-aa09bf80-a25b-11e9-8c17-0934d1b060da.png)

Using `bridge`:
![image](https://user-images.githubusercontent.com/725456/60919574-bdb52600-a25b-11e9-8c0a-2a6870bbbdbe.png)

As you can see in the second screenshot my LAN IP address (of my docker host) is required (not ideal). The first screenshot is simpler to maintain over time, especially if I were to change IP addresses, or move my apps to another system in the future.
