### ISSUE TITLE
502 Bad Gateway when using own domain, letsencrypt and nzbgetvpn

### ISSUE THREAD

**Issue by DotDotSpaceDotDot** [GhostWriters/DockSTARTer#753]
**Describe the bug**
When using letsencrypt with own domain, subfolders and nzbgetvpn or transmissionvpn 502 Bad Gateway is displayed.

**To Reproduce**

1. Set up container as normal for local network access
2. Set up letsencrypt container to access containers using own domain  
3. Access nzbgetvpn or transmissionvpn via https://domain.com/nzbgetvpn/
4. 502 Bad Gateway is displayed

**Expected behavior**
https://domain.com/nzbgetvpn/ to display nzbget web interface in web browser.

**Screenshots**

**System (please complete the following information):**

- OS: Ubuntu Server
- Version 18.04.2 LTS

**Additional context**
This appears to be due to missing proxy configuration files for nzbgetvpn and transmissionvpn in letsencrypt??

**Comment by nemchik** [comment]
You'll have to adjust the proxy config files. Look for `set $upstream_nzbget nzbget;` and change it to `set $upstream_nzbget nzbgetvpn;`

**Comment by nemchik** [comment]
P.s. if you need more assistance with this issue please join our discord (link in the readme)

**Comment by DotDotSpaceDotDot** [comment]
Thanks. That worked well for nzbgetvpn but did not work for transmissionvpn. 
Any assistance in getting transmissionvpn work work be great.

**Comment by nemchik** [comment]
Are you able to access transmissionvpn locally?

**Comment by DotDotSpaceDotDot** [comment]
Hi, all sorted. I had firewall enabled in docker override. Why i don't know!! Any way removed the firewall entry and all good.
Thanks for your help.
