### ISSUE TITLE
Cannot find downloads - NZBGet

### ISSUE THREAD

**Issue by mickeygoldsmith** [GhostWriters/DockSTARTer#757]
My apologies as I'm a noob, but I used NZBget and mapped the Global Variables to the external HDD plugged into my rPI. But I went to check the folder (as I use Sonarr in conjunction with NZBget) and I cannot find the download.

What am I missing?

**Comment by nemchik** [comment]
In nzbget (and all other apps that have a need to see the downloads folder) it's located at `/downloads` not the original location of your disk.

**Comment by mickeygoldsmith** [comment]
Where is this /downloads folder? in the root? in the /home/user/downloads? I checked both of those, and I still can't find it. I also did  a search and I couldnt find it....is there any way to make the downloads go to the external hard drive, as initially planned?

**Comment by nemchik** [comment]
The apps inside the containers will see `/downloads` (in the root) but on your actual system it'll be mapped to the `DOWNLOADSDIR` that you set in DS config menu. The variable can also be found and edited in the `~/.docker/compose/.env` file. If you do edit the file you need to run `ds -c` to make the changes take effect.

**Comment by mickeygoldsmith** [comment]
the ~/.docker/compose/.env file has the below....correctly set...and yet, the downloads aren't there...

# Global Settings
COMPOSE_HTTP_TIMEOUT=60
DOCKERCONFDIR=/home/pi/.config/appdata
DOCKERGID=999
DOCKERHOSTNAME=downloader
DOCKERLOGGING_MAXFILE=10
DOCKERLOGGING_MAXSIZE=200k
DOCKERSHAREDDIR=/home/pi/media/USBHDD1/shares
DOWNLOADSDIR=/home/pi/media/USBHDD1
MEDIADIR_AUDIOBOOKS=/home/pi/media/USBHDD1/audiobooks
MEDIADIR_BOOKS=/home/pi/media/USBHDD1/books
MEDIADIR_COMICS=/home/pi/media/USBHDD1/comics
MEDIADIR_MOVIES=/home/pi/media/USBHDD1/Movies
MEDIADIR_MUSIC=/home/pi/media/USBHDD1/music
MEDIADIR_TV=/home/pi/media/USBHDD1/TV
PGID=1000
PUID=0
TZ=America/New_York

**Comment by nemchik** [comment]
Maybe `DOWNLOADSDIR` should be `/home/pi/media/USBHDD1/downloads` (just a recommendation).

In nzbget settings what do you have for the downloads location?

**Comment by mickeygoldsmith** [comment]
Do I change the settings? I read that you weren't supposed to... (although, I did try to put in the /home/pi/media/USBHDD1 directory, since Sonarr is supposed to rename and move the file to the correct directory - and there I can see is the correct directory)...

![image](https://user-images.githubusercontent.com/51180290/61094244-57c3cc80-a41c-11e9-8b68-443303794f14.png)

**Comment by nemchik** [comment]
Containers cannot see your home folder from the inside (of the container).

Your nzbget paths should like exactly like this: Nzbget https://imgur.com/gallery/rdvZ73g

Sonarr only needs to have a root directory setup to point to `/tv` and you don't set any other folders (it detects them).

**Comment by mickeygoldsmith** [comment]
Understood...but that still leaves two questions:
1) Does Sonarr move the file to the TV folder then? And if so, will it move it to an external HDD folder, like whats above (/home/pi/media/usbhdd1)? If not, how do i get it there?
2) If it cant do #1, how do I get the downloads out of the container?

**Comment by nemchik** [comment]
1. Yes and yes. You have `/tv` mapped to `/home/pi/media/USBHDD1/TV` and sonarr will move and rename and organize completed downloads from nzbget into your tv folder automatically.
2. N/A because 1 is yes

**Comment by mickeygoldsmith** [comment]
I just tried it, and it did not work....

**Comment by nemchik** [comment]
In sonarr what do you have set as your root folder (where it saves tv)? Also can you send a screenshot of your nzbget connection settings in sonarr?

**Comment by mickeygoldsmith** [comment]
in sonarr, the root folder is /tv

![image](https://user-images.githubusercontent.com/51180290/61095567-f1da4380-a421-11e9-9070-89ebd61d91eb.png)

**Comment by nemchik** [comment]
For host you can just put `nzbget` instead of the IP.

Is there anything in nzbget or sonarr logs showing it tried and failed to download or import?

**Comment by mickeygoldsmith** [comment]
no, it says successful...

**Comment by nemchik** [comment]
That's a bit confusing. Does it say exactly what it did?

**Comment by mickeygoldsmith** [comment]
"Move for The.Detour.S04E04.iNTERNAL.720p.WEB.H264-AMRAP successful"
"Moving completed files for The.Detour.S04E04.iNTERNAL.720p.WEB.H264-AMRAP"

**Comment by nemchik** [comment]
And what files do you have in `/home/pi/media/USBHDD1/TV` ?

**Comment by mickeygoldsmith** [comment]
old folder structures (used from my previous rpi 3b+, and I am trying to move this process to the rpi 4b  to take advantage of the gigabit ethernet and USB 3.0 speeds)

**Comment by nemchik** [comment]
And this episode file isn't in there in a subfolder for the show somewhere?

**Comment by mickeygoldsmith** [comment]
Nope...

**Comment by nemchik** [comment]
Can you open portainer and look at sonarr and see where it thinks your tv folder is?

Also run `docker exec sonarr ls -a /tv` and post the output here.

**Comment by mickeygoldsmith** [comment]
1) i dont know how to do that
2) it correctly lists the TV folder on the external HDD

**Comment by nemchik** [comment]
For portainer http://192.168.6.208:9000/

For the folder in sonarr it's listing the external disk and not the TV show you tried to download? Can you try another episode and see if it imports correctly now that we've adjusted a few things?

**Comment by mickeygoldsmith** [comment]
sonarr:
<img width="912" alt="Screen Shot 2019-07-11 at 10 13 22 PM" src="https://user-images.githubusercontent.com/51180290/61097391-33222180-a429-11e9-85f8-0d590a62cdc7.png">

nzbget:
<img width="987" alt="Screen Shot 2019-07-11 at 10 15 00 PM" src="https://user-images.githubusercontent.com/51180290/61097449-619ffc80-a429-11e9-99a4-61f50ba15294.png">

I tried it before, thats when I posted it moved successfully (which it didn't)....does doing this on a rpi4 matter?

**Comment by nemchik** [comment]
I don't think it matters that you're using an rpi4.

Can you try a new episode?

Also are you using radarr? Does it have the same issue? (Root folder for radarr is `/movies`)

**Comment by mickeygoldsmith** [comment]
Yes, I am also using radarr, Yes, the same issue occurs with radarr...

Yes, I tried a new episode, and the same issue occurred...

**Comment by nemchik** [comment]
If the apps are saying they successfully imported your media but it's not showing up that's an issue. I'm about down for the night, but I recommend joining our discord for further support https://discord.gg/YFyJpmH

**Comment by mickeygoldsmith** [comment]
Okay, but I dont know what im doing there....

**Comment by nemchik** [comment]
There are others who can help troubleshoot. You can link to this issue so you don't have to re explain everything. I have some other ideas about what to look for, but it'll have to be tomorrow. Possibly someone in the chat helps get you sorted before then.
