### ISSUE TITLE
Prompt for VPN Directory for .OVPN files/credentials

### ISSUE THREAD

**Issue by beebbb** [GhostWriters/DockSTARTer#759]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Make it easier for newcomers to get their *VPN applications up and running by prompting for a path where .OVPN/credentials files are stored and map it into containers that require it during the Full Setup/VPN Configuration. This should mean that those who are unfamiliar with the current ```~/.config/appdata``` structure should be able to have their containers usable without any intervention post-setup and reduce the need for support.

**Additional context**
This feature should also make it useful for experienced users who switch VPN providers in the future.

I have not considered the scenario where someone might wish to use different VPN configurations for different applications.

**Comment by nemchik** [comment]
> I have not considered the scenario where someone might wish to use different VPN configurations for different applications.

I would recommend overrides for this scenario.

**Comment by nemchik** [comment]
I will definitely implement this.

The first consideration I can think of is transitioning existing setups to this new method. I think the best way to do that will be to find any `*.ovpn` files in `openvpn` subfolders inside the app config folders and copy those files to the designated openvpn folder defined in the variable. I'm thinking of using `~/.config/appdata/.openvpn/` by default. This would happen automatically for users updating DS so there would not be an opportunity to specify a different folder, but users can change it and relocate the files any time later.

Currently we have an `env_sanitize` function that triggers at the correct time to handle this task, but I don't feel this function should be moving files around. I'll either want to rename this function or create a new one that covers this and possibly other tasks.
