### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by nemchik** [GhostWriters/DockSTARTer#76]
-   [x] Menu to make selection easy
-   -   [x] Display detected `TimeZone` on host and set in `.env` file. (suggest changing system if not correct)
-   -   [x] Display detected `user` and `group` and set in `.env` file along with PUID and PGID
-   -   [x] Prompt default media folder locations
-   -   -   [x] Allow to change media folder locations
-   -   [x] Prompt default config folder location
-   -   -   [x] Allow to change config folder location
-   -  [x] Prompt to select desired apps
-   -  [x] Prompt to run `docker-compose up -d` (making it optional)

**Comment by nemchik** [comment]
From the wiki


-   [ ] Menu to make selection easy
-   -   [ ] Prompt to fill in environment variables
-   -   -   [ ] Prompt to set timezone
-   -   -   [ ] Prompt to set user and group
-   -   -   [ ] Prompt to set folder locations
-   -   -   [ ] Set permissions on folders/files (755/644)
-   -   -   [ ] Set ownership on folders/files (user:group)
-   -   -   [ ] Check for apps using the same port
-   -   [ ] Prompt to select desired apps
-   -   -   [ ] Prompt to run `docker-compose up -d` (making it optional)
-   -   [ ] Prompt to enable/disable reverse proxy per app in letsencrypt config
-   -   [ ] Possibly prompt to select which apps should be configured to use a VPN (depending on how we end up handling VPN)

**Comment by TommyE123** [comment]
Closing as all R1 points have been completed.

**Comment by nemchik** [comment]
Do we feel like the GUI branch is ready to merge into master?
