### ISSUE TITLE
Grafana cannot create directory

### ISSUE THREAD

**Issue by eitchtee** [GhostWriters/DockSTARTer#761]
**Describe the bug**
Setting up Grafana out of the box, without changing any global or app-based configuration will have the app hang, stuck on a permission error as seen on the log below.

```
mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied,
GF_PATHS_DATA='/var/lib/grafana' is not writable.,
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later,
```
The reason for this seem to be that Grafana's appdata folder's ownership is set as root:root instead of the user's id and group id as configured on the docker-compose.yml file.

I've managed to fix it by changing `/.config/appdata/grafana/` ownership to the UID and GID configured on dockerSTARTer globar variables, in this case 1000:1000.

**System (please complete the following information):**

- OS: Ubuntu
- Version: 18.04.2

**Comment by nemchik** [comment]
The grafana image is a bit odd in this way. I think they expect to to make the folder and setup permissions before starting the container. The only thought I have that could get around this is to not specify the user which would leave the container running as root, but that seems like a bad idea.

**Comment by eitchtee** [comment]
Peharps adding a warning to the user about the changes needed to be made or an entry on the documentation could suffice for now.

Or, haven't dug around the code to see how it works, but couldn't DS just create the folder itself and append the right permissions? A hacky, but worth solution.

**Comment by nemchik** [comment]
Indeed DS could, but that becomes unmanageable at scale (80+ apps). Most apps don't need extra attention, and I've tried to keep everything as generic as possible.

I'm fine with documenting being added to https://dockstarter.com/apps/grafana/ (use the edit button).

**Comment by eitchtee** [comment]
I understand. At least this issue is logged now in case anyone ever stumbles upon the same problem.

I will have a go at the docs once I have some free time.

**Comment by nemchik** [comment]
The docs are pretty particular about formatting, but you'll see a build run on any pull request made (the edit button interface guides you through making a PR). If the build fails the logs will tell you what needs to be fixed.

**Comment by eitchtee** [comment]
I've made a pull request on the documentation explaining how to fix this issue.

Thank you.

**Comment by eitchtee** [comment]
I'm closing this since a workaround was found.
