### ISSUE TITLE
Un-deprecate samba

### ISSUE THREAD

**Issue by nemchik** [GhostWriters/DockSTARTer#770]
Ref #498

**Comment by TRaSH-** [comment]
https://github.com/TRaSH-/docker-compose-override/blob/master/samba/docker-compose.override-samba.yml

When a fresh/clean install the /appdata/samba has root credentials and then it doesn't work.
if you do a
`sudo chown -R user:user ~/.config/appdata/samba` and restarting the container you're able to access the share
