### ISSUE TITLE
nvidia-docker2 support

### ISSUE THREAD

**Issue by niXta1** [GhostWriters/DockSTARTer#781]
**Is your feature request related to a problem? Please describe.**
Passing through nvidia GPU to a container.

**Describe the solution you'd like**
Be able to use docker compose v2.3 or find a better way to get GPU to a container

**Describe alternatives you've considered**
1. Override (needs to be using compose v2.3 i think?).
2. Set the nvidia GPU to be used in all containers by modifying docker config.

This is on Ubuntu 18 with latest stabile docker.

**Comment by nemchik** [comment]
If you're taking about Plex we've got documentation about adding the device to the container https://dockstarter.com/apps/plex/#hardware-transcoding that same method should at least be similar with other containers of you're not talking about Plex. Those other containers might also have their own documentation about how to get the device in. All that is just done via overrides.

That covers adding it to specific containers as needed, but not globally to all containers. I'm curious what your reasoning is for wanting it on ALL containers?

Also about the compose versions, what example do you have that if specific to version 2.x that does not work on 3.x?

**Comment by niXta1** [comment]
> If you're taking about Plex we've got documentation about adding the device to the container https://dockstarter.com/apps/plex/#hardware-transcoding that same method should at least be similar with other containers of you're not talking about Plex. Those other containers might also have their own documentation about how to get the device in. All that is just done via overrides.
> 
> That covers adding it to specific containers as needed, but not globally to all containers. I'm curious what your reasoning is for wanting it on ALL containers?
> 
> Also about the compose versions, what example do you have that if specific to version 2.x that does not work on 3.x?
Yes, this is regarding Plex.

AFAIK nvidia GPU does not work with /dev/dri. It hasn't worked with any other docker setup, why would it work here?

AFAIK nvidia-docker2 'only' (I just read, don't shoot the messenger) works with v2.3 (https://github.com/NVIDIA/nvidia-docker/wiki#do-you-support-docker-compose).

If I can't use v2.3 with dockstarter, maybe it's possible to enable in the docker conf? It's just an idea.

Thanks for the quick reply!

**Comment by nemchik** [comment]
https://github.com/NVIDIA/nvidia-docker/blob/master/README.md#quickstart according to their readme nvidia-docker2 is now deprecated. There should be an alternative way to achieve using their runtime, but I haven't dug that far into it.

**Comment by niXta1** [comment]
> https://github.com/NVIDIA/nvidia-docker/blob/master/README.md#quickstart according to their readme nvidia-docker2 is now deprecated. There should be an alternative way to achieve using their runtime, but I haven't dug that far into it.

Sorry, my bad, it's not called docker-2 anymore. 
There's not really a name for it (unless nvidia-docker?) as far as I can see but what you need to install is 'nvidia-container-toolkit' to get it running. So let's call it nvidia-container-toolkit for now.

At the end it says:

> Do you support Docker Compose?
> Yes, use Compose format 2.3 and add runtime: nvidia to your GPU service. Docker Compose must be version 1.19.0 or higher. You can find an example here.

So, to get it working you need to: 
1. Install 'nvidia-container-toolkit' according to the instructions.
2. use Compose format 2.3.
3. add 'runtime: nvidia' in the compose file.

**Comment by nemchik** [comment]
It looks like the new GPU support in docker 19.03 just needs to be added to compose for version 3.x. there's a few open issues on their GH you can follow.

https://github.com/docker/compose/issues/6691
https://github.com/docker/compose/issues/4657
https://github.com/docker/compose/issues/6239

The first one is more promising and the last one seems less likely given the GPU support added to engine.

**Comment by niXta1** [comment]
> It looks like the new GPU support in docker 19.03 just needs to be added to compose for version 3.x. there's a few open issues on their GH you can follow.
> 
> [docker/compose#6691](https://github.com/docker/compose/issues/6691)
> [docker/compose#4657](https://github.com/docker/compose/issues/4657)
> [docker/compose#6239](https://github.com/docker/compose/issues/6239)
> 
> The first one is more promising and the last one seems less likely given the GPU support added to engine.

As far as I can see, the newest of those is 3 months old with no reply and was closed... It doesn't look too promising?

**Comment by nemchik** [comment]
I have tried in the past to allow the compose file version to be set by the user but have not been successful. I have some ideas about how I could do it, but this requires the compose templates we use to be made a little more version agnostic than they currently are. There's not a big demand for this at the moment, and some apps require features from newer compose versions (ex: labels introduced in compose file version 3.3). It makes more sense to request older apps to update than to restrict newer apps from functionality.

**Comment by daveb92** [comment]
I can confirm i have this working, override file for Plex is as below: 

version: "3.4"  # this must match the version in docker-compose.yml
services:
  plex:
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility

I set it up a while ago, but i do know that i had to change the docker to use the nvidia runtime as default in /etc/docker/daemon.json

{
 "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}

**Comment by niXta1** [comment]
> 
> 
> I can confirm i have this working, override file for Plex is as below:
> 
> version: "3.4" # this must match the version in docker-compose.yml
> services:
> plex:
> environment:
> - NVIDIA_VISIBLE_DEVICES=all
> - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
> 
> I set it up a while ago, but i do know that i had to change the docker to use the nvidia runtime as default in /etc/docker/daemon.json
> 
> {
> "default-runtime": "nvidia",
> "runtimes": {
> "nvidia": {
> "path": "nvidia-container-runtime",
> "runtimeArgs": []
> }
> }
> }

Sweet! Option nr. 2 it is!
