### ISSUE TITLE
Version 2 Available

### ISSUE THREAD

**Issue by halfagascan** [GhostWriters/DockSTARTer#785]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by halfagascan** [comment]
This is from https://github.com/bl0m1/xtevedocker, progress has been made, documentation, and support. 
Pleases consider

**Comment by nemchik** [comment]
Closing this since we only need one issue for an app #784

Feel free to leave your comments about the Docker image there.
