### ISSUE TITLE
Raspbian install not working - Docker-ce install fails.

### ISSUE THREAD

**Issue by swd120** [GhostWriters/DockSTARTer#787]
Raspbian install not working - Docker-ce install fails.

+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
E: Sub-process /usr/bin/dpkg returned an error code (1)
2019-08-16 05:15:29 [FATAL ]   Failed to install docker.
2019-08-16 05:15:30 [ERROR ]   DockSTARTer did not finish running successfully.

**Comment by nemchik** [comment]
Can you try
```
sudo apt-get update
sudo apt-get dist-upgrade
```
Then go grab the script from https://get.docker.com/ and run it (the instructions are in the top of the file).

**Comment by kazo0** [comment]
I am having the same issue on rpi. I ran the commands you mentioned and got the following errors:

Output from sudo apt-get  dist-upgrade
```
Setting up docker-ce (5:19.03.1~3-0~raspbian-stretch) ...
A dependency job for docker.service failed. See 'journalctl -xe' for details.
invoke-rc.d: initscript docker, action "start" failed.
 docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-07-21 10:22:26 EDT; 1 months 8 days ago
     Docs: https://docs.docker.com
 Main PID: 435 (dockerd)
   CGroup: /system.slice/docker.service
           ├─  435 /usr/bin/dockerd -H unix://
           ├─ 1575 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3579 -container-ip 172.18.0.9 -container-port 3579
           ├─ 7788 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 7878 -container-ip 172.18.0.5 -container-port 7878
           ├─ 8300 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8083 -container-ip 172.18.0.8 -container-port 8083
           ├─ 8814 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8989 -container-ip 172.18.0.4 -container-port 8989
           ├─14023 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 9117 -container-ip 172.18.0.6 -container-port 9117
           ├─18391 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 9091 -container-ip 172.18.0.3 -container-port 9091
           └─23855 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 9000 -container-ip 172.18.0.2 -container-port 9000

Aug 27 04:08:36 htpc dockerd[435]: time="2019-08-27T04:08:36.002104605-04:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Aug 27 04:08:56 htpc dockerd[435]: time="2019-08-27T04:08:56.282832520-04:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Aug 28 04:01:49 htpc dockerd[435]: time="2019-08-28T04:01:49.406208222-04:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Aug 29 04:03:14 htpc dockerd[435]: time="2019-08-29T04:03:14.462943914-04:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Aug 29 20:14:28 htpc systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 29 20:14:28 htpc systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Aug 29 20:18:13 htpc systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 29 20:18:13 htpc systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Aug 29 20:26:01 htpc systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 29 20:26:01 htpc systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

After that, output from the get.docker.com script:
```
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by kazo0** [comment]
Running `journalctl -xe` gives:

```
Aug 29 20:44:39 htpc systemd-logind[350]: Removed session c4.
-- Subject: Session c4 has been terminated
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID c4 has been terminated.
Aug 29 20:44:43 htpc systemd[1]: Reloading.
Aug 29 20:44:43 htpc systemd[1]: apt-daily-upgrade.timer: Adding 47min 14.492949s random time.
Aug 29 20:44:43 htpc systemd[1]: apt-daily.timer: Adding 4h 13min 50.508062s random time.
Aug 29 20:44:43 htpc systemd[1]: Reloading.
Aug 29 20:44:44 htpc systemd[1]: apt-daily-upgrade.timer: Adding 37min 11.071771s random time.
Aug 29 20:44:44 htpc systemd[1]: apt-daily.timer: Adding 4h 14min 26.239967s random time.
Aug 29 20:44:44 htpc systemd[1]: docker.socket: Socket service docker.service already active, refusing.
Aug 29 20:44:44 htpc systemd[1]: Failed to listen on Docker Socket for the API.
-- Subject: Unit docker.socket has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit docker.socket has failed.
--
-- The result is failed.
Aug 29 20:44:44 htpc systemd[1]: Dependency failed for Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit docker.service has failed.
--
-- The result is dependency.
Aug 29 20:44:44 htpc systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
```

**Comment by kazo0** [comment]
Running `sudo service docker stop` before running `sudo ds -i` seems like a workaround for now.

**Comment by nemchik** [comment]
This is sounding like in big cases apt may have been in a broken state before attempting to use DS.

I'm no ruling out that something broke during the first run of DS that wasn't broken before running DS (AKA DS fault) but we've had other user's report success on rpi recently so I'm not sure yet.

**Comment by nemchik** [comment]
I've updated the install instructions in the readme (and homepage) with a separate section for raspbian. I've also tweaked the installer a bit (just that if you rerun the curl bash it'll try to reinstall dependencies).

I've had one user confirm the new instructions work for them. If anyone else would like to confirm on a clean install of raspbian we'll close this issue.

**Comment by petersw730** [comment]
I just tried a clean install under Rasbian Buster Lite, following the new directions (thanks for that!).  Everything went fine until the end, when I got a fatal error of:

2019-09-19 00:10:00 [FATAL ]   Failed to install python cryptography dependencies from apt.
2019-09-19 00:10:00 [ERROR ]   DockSTARTer did not finish running successfully.

**Comment by kazo0** [comment]
Just an FYI a clean install on a Raspberry Pi 4 running Buster worked without issue for me using the new installation steps.

**Comment by nemchik** [comment]
@petersw730 can you try to run `sudo apt-get -y install build-essential libssl-dev libffi-dev python3-dev`

**Comment by ethanmdavidson** [comment]
The updated raspbian steps didn't work for me, I was still getting the same error (on Raspberry Pi 1 B rev2). However, I stumbled upon [this issue](https://github.com/moby/moby/issues/38175) which (if I'm understanding correctly) says it is a problem with the latest version of containerd not being packaged for ARM. The solution is to [install the ARM compiled version by Hypriot](https://github.com/moby/moby/issues/38175#issuecomment-531108985). 

Also somewhate unrelated, but I'll mention it here in case anyone else is in the same boat: once docker was running this way, the armhf/hello-world container wasn't working (no output). Solution here was [using the hypriot/armhf-hello-world container](https://stackoverflow.com/questions/52233182/docker-run-does-not-display-any-output)

**Comment by nemchik** [comment]
If you can confirm the commands required to get this working on a fresh install it might be able to be added to the get.docker.com script that DS uses. I may even be able to propose the changes.

**Comment by ethanmdavidson** [comment]
Device: Raspberry Pi 1 Model B rev 2
OS: Raspbian Buster Lite (2019-09-26)
From a fresh image:
1. `wget -O /tmp/containerd.io_1.2.10-1_armhf.deb --content-disposition https://packagecloud.io/Hypriot/rpi/packages/raspbian/buster/containerd.io_1.2.10-1_armhf.deb/download.deb`
2. `sudo apt install /tmp/containerd.io_1.2.10-1_armhf.deb`
3. `sudo apt-get install curl git`
4. `bash -c "$(curl -fsSL https://get.docker.com)"`
5. (optional, to test install) `sudo docker run hypriot/armhf-hello-world`

**Comment by thaJeztah** [comment]
This should be resolved now with the container.io_1.2.10-2 package; https://github.com/moby/moby/issues/38175#issuecomment-540355951

> Hey guys!
> 
> Just released new [containerd.io package](https://download.docker.com/linux/raspbian/dists/buster/pool/stable/armhf/containerd.io_1.2.10-2_armhf.deb) version 1.2.10-2 to the https://download.docker.com repositories, please let me know if that resolves all issues related to this segmentation fault, I do not currently have a armv6 machine to test on.
>
> Sorry for the late update on this, hopefully this issue is now resolved
