### ISSUE TITLE
Current setup does not allow Plex to work with Traefik

### ISSUE THREAD

**Issue by hannonq** [GhostWriters/DockSTARTer#798]
**Describe the bug**
I am setting my apps behind Traefik, and I've been able to make it work with Nextcloud now.
My next try was Plex, and, for what I see in the tutorials out there, I need to add the following to my docker-compose file (did it for Nextcloud and it works fine):

```yml
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
...
services:
  plex:
    networks:
        - traefik_proxy
```
But when I run `sudo ds -c up`, I get the error 

```
ERROR: 'network_mode' and 'networks' cannot be combined  
2019-09-02 21:12:38 [FATAL ]   Docker Compose failed.  
2019-09-02 21:12:38 [ERROR ]   DockSTARTer did not finish running successfully.
```
The problem seems to happen due to the fact that `network_mode` is defined in the `plex.netmode.yml` file, and the `docker-compose.override.yml` can only add and change stuff from the original yml file, not delete.

**To Reproduce**
Setup Traefik and create an override for plex with the example yml described above.

**Expected behavior**
I would expect the possibility to delete/ignore some of the defaults from the `.apps` folder.

**System (please complete the following information):**

- Ubuntu Server
- Version 18.04

Do you see any way to work around this problem?

**Comment by nemchik** [comment]
If you leave network mode blank the netmode file won't be included.

https://github.com/GhostWriters/DockSTARTer/blob/5969625ede81e3e5f6cad479d205ca4fee947457/.scripts/yml_merge.sh#L31

**Comment by hannonq** [comment]
Ah yes, of course!
Thanks for the quick reply :)

The network works now (still working on making Plex available outside my network, though. But that has nothing to do with DockSTARTer.)
