### ISSUE TITLE
Code-Server install from GUI breaks environment 

### ISSUE THREAD

**Issue by dutran88** [GhostWriters/DockSTARTer#799]
**Describe the bug**
when installing codeserver from gui, it would set all running container to false on environment.

**To Reproduce**

1. Go to 'docker ds'
2. Click on 'codeserver app'
3. Run docker-compose

**Comment by nemchik** [comment]
Fix merged. Please run `ds -u` and then check the compose backups folder in config appdata to restore a copy of your .env
