### ISSUE TITLE
Changes to transmissionvpn settings.json overwritten every time

### ISSUE THREAD

**Issue by trolley** [GhostWriters/DockSTARTer#810]
**Describe the bug**
I stop the transmissionvpn container and edit settings.json in ~/.config/appdata/transmissionvpn, but when the container is started again the file is overwritten and the settings are lost.

**To Reproduce**

1. docker stop transmissionvpn
2. Edit ~/.config/appdata/transmissionvpn/settings to enable ratio limit, for example.
3. docker start transmissionvpn

**Expected behavior**
Settings should persist if edited while the container is stopped.

**Screenshots**

**System (please complete the following information):**

- OS: Ubuntu
- Version 18.04.3

**Additional context**

**Comment by nemchik** [comment]
https://haugene.github.io/docker-transmission-openvpn/arguments/#transmission_configuration_options

Unfortunately the way this container was made the settings are overwritten intentionally. You can define the values you want using environment variables in an override file https://dockstarter.com/advanced/overrides/
