### ISSUE TITLE
App Addition: Synclounge

### ISSUE THREAD

**Issue by mattgphoto** [GhostWriters/DockSTARTer#818]
**Is your feature request related to a problem? Please describe.**
Nope!

**Describe the solution you'd like**
Request for synclounge docker image/container to be listed as an available application: https://github.com/samcm/SyncLounge

**Describe alternatives you've considered**
Don't know of another service that allows for watching plex together with your friends.

**Comment by CLHatch** [comment]
I'd be interested in this as well.  They do have Docker images available for it:

https://hub.docker.com/r/starbix/synclounge

**Comment by CLHatch** [comment]
I noticed that this is being worked on.  Any ETA of any kind on it?

**Comment by mturley** [comment]
+1, this would be awesome.

**Comment by nemchik** [comment]
Here's a link to the PR https://github.com/GhostWriters/DockSTARTer/pull/875

@MagicalCodeMonkey has been working on it. He's also been working on improvements to SyncLounge itself, so those might need to be done before our PR to add it to DS is ready. I'll defer to him whenever he feels like it's good to go or needs testing. Volunteering for testing would happen in our discord server.

**Comment by MagicalCodeMonkey** [comment]
The docker image needs to be updated to support new variables and fix some issues. Once that is done, I'll be able to update anything need in the PR and then have some other people test!

**Comment by mattgphoto** [comment]
> The docker image needs to be updated to support new variables and fix some issues. Once that is done, I'll be able to update anything need in the PR and then have some other people test!

Will be happy to test on docker!

**Comment by MagicalCodeMonkey** [comment]
I posted information for testing in the DS Testing channel! Have at it! 😄

**Comment by MagicalCodeMonkey** [comment]
SyncLounge has been added! Update DockSTARTer and you should be good to go!

Documentation can be found at https://dockstarter.com/apps/synclounge/

**Comment by CLHatch** [comment]
> SyncLounge has been added! Update DockSTARTer and you should be good to go!
> 
> Documentation can be found at https://dockstarter.com/apps/synclounge/

If I'm not mistaken, the example for the "Override Servers List" in the documentation is incorrect.

Shouldn't  the line:
`        - ${DOCKERSHAREDDIR}/synclounge/servers.json:/defaults/servers.json`
actually be
`        - ${DOCKERCONFDIR}/synclounge/servers.json:/defaults/servers.json`

**Comment by mattgphoto** [comment]
Yep, it should be `${DOCKERCONFDIR}/synclounge/servers.json:/defaults/servers.json`

**Comment by MagicalCodeMonkey** [comment]
Damn! I knew I forgot something...

**Comment by CLHatch** [comment]
> Damn! I knew I forgot something...

BTW, I wasn't sure if you'd see the message here since it was closed, so I opened an issue regarding it on the documentation site also.
