### ISSUE TITLE
Grafana wont get network connection

### ISSUE THREAD

**Issue by dualznz** [GhostWriters/DockSTARTer#830]
**Describe the bug**
After installation of grafana when trying to access webui it responds with 404 not found, i looked on portainer within "containers" and sure enough there is no **IP Address** or **Published Ports**

**To Reproduce**

- Download grafana via sudo ds
- Try connecting to webUI via port: 3000

**Expected behavior**
WebUI should load up as intended and it should also appear on portainer as a network connected service

**Screenshots**
[https://cdn.discordapp.com/attachments/520006609414651916/643278741060976651/unknown.png](https://cdn.discordapp.com/attachments/520006609414651916/643278741060976651/unknown.png)
[https://cdn.discordapp.com/attachments/520006609414651916/643278960448241725/unknown.png](https://cdn.discordapp.com/attachments/520006609414651916/643278960448241725/unknown.png)

**System**

- OS: Ubuntu
- Version 18.04.3 LTS

**Additional context**
Attempted to acquire logs via "docker logs grafana" command and it responds with
`GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied`

This only denies on grafana i tried doing it with plex and it responded with the logs for the container

**Comment by nemchik** [comment]
Please try running `sudo chown -R $USER:$USER ~/.config/appdata/grafana && docker restart grafana`
