### ISSUE TITLE
Matrix-Synapse Server

### ISSUE THREAD

**Issue by MKE1138** [GhostWriters/DockSTARTer#840]
**Describe the solution you'd like**

Matrix is an open standard for decentralized communication. It’s a collection of servers and services used for online messaging which speak a standardized API that synchronizes in real time.

Matrix uses homeservers to store your account information and chat history. They work in a similar way to how an email client connects to email servers through IMAP/SMTP. Like email, you can either use a Matrix homeserver hosted by somebody else or host your own and be in control of your own information and communications.

I would find it very useful to have Matrix-Synapse as an available container!

**Comment by nemchik** [comment]
Is there a docker container for this that we can add?

**Comment by MKE1138** [comment]
Yep!

Matrix (the server): 

https://hub.docker.com/r/matrixdotorg/synapse/

Riot.im (a popular client): https://github.com/bubuntux/docker-riot-web/

**Comment by jodfie** [comment]
i'll make an Override page for this until it is decided on including it in DS @nemchik can you assign to me?

**Comment by angrycuban13** [comment]
> Yep!
> 
> 
> 
> Matrix (the server): 
> 
> 
> 
> https://hub.docker.com/r/matrixdotorg/synapse/
> 
> 
> 
> Riot.im (a popular client): https://github.com/bubuntux/docker-riot-web/

So would you like to see both added or just the one?

**Comment by MKE1138** [comment]
> > Yep!
> > Matrix (the server):
> > https://hub.docker.com/r/matrixdotorg/synapse/
> > Riot.im (a popular client): https://github.com/bubuntux/docker-riot-web/
> 
> So would you like to see both added or just the one?

Both would be great. I happen to like the riot (now called Element) front-end, but there’s a lot of others so offering people the option to use whatever front-end they’d like would be well-received by the rest of the community, I think!

**Comment by dylanmtaylor** [comment]
Looks like Riot.im was renamed to Element? https://element.io/

**Comment by dylanmtaylor** [comment]
Working on adding Element (formerly Riot.im) in #1061

**Comment by MKE1138** [comment]
Yeah, I think they rebranded a few months ago…

-M
—
Mike Bougie
mike@browncoat.ca | +1 (514) 973-8249
