### ISSUE TITLE
Add gBridge as an option in services of DockSTARTer

### ISSUE THREAD

**Issue by soile1991** [GhostWriters/DockSTARTer#842]
**Describe the solution you'd like**
Be able to configure and manage gBridge from DockSTARTer

**Additional context**
https://doc.gbridge.io/selfHosted/hostItYourself.html#set-up-gbridge-in-docker

**Comment by dualznz** [comment]
I too would like this in DS for alot of my automation tools

**Comment by soile1991** [comment]
gBridge was discontinued
