### ISSUE TITLE
Unifi container not being assigned alternate ports

### ISSUE THREAD

**Issue by shuffleznl** [GhostWriters/DockSTARTer#851]
Not sure if this classifies as 'bug report', but was wondering if I should report findings somewhere (as some apps do get alternate ports set by default).

**Describe the bug**
Several ports in newer containers are already assigned to others (which are earlier in alphabet).
E.g. unifi.ports.yml
Port 6789: in use by NZBget
Port 8081: in use by Guacamole

But for others like Organizr: 80 conflicts, but gets 8006 (for me), Monitor gets 8004, so Letsencrypt can keep 80.

**To Reproduce**
`sudo ds` -> select apps, choose Guacamole, NZBget and Unifi -> compose or `sudo ds -c`

**Expected behavior**
Get alternate ports suggested when confirming variables

**System**
HP Z2 Mini

- OS: Ubuntu
- Version 18.04 LTS

**Additional context**

**Comment by nemchik** [comment]
From https://github.com/GhostWriters/DockSTARTer/blob/master/.github/CONTRIBUTING.md

> `<APPNAME>_PORT_<ORIGINAL_PORT>=<USER_PORT>` (optional) is included based on what is needed by the app. There can be multiple ports. Ports should be sorted numerically. `<ORIGINAL_PORT>` is whatever port the app uses inside the container. `<USER_PORT>` is the port the user will use, and should default to be the same as the `<ORIGINAL_PORT>` unless it is a [Well-known port](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Well-known_ports) in which case it should be moved to another port. Certain rare exceptions are made where the primary function of an app requires it be using a specific port

Essentially I try to avoid port conflicts out of the box for common ports like 80 and 443, but for the rest it's up to the user (you) to decide which ports to move around. I love the idea of being as user friendly as possible and not giving you anything to worry about when you start up a new container, but also this is a very easy problem to fix and very common with docker containers wanting the same port so I try to look at is as the first learning experience for users to learn more about how docker works. Even explaining that it feels like a cop-out, but I have not found a better way to handle it other than accepting the support requests that come with it.
