### ISSUE TITLE
new ds install fails in "Installing latest docker-compose" on fresh install of Centos 7 latest 

### ISSUE THREAD

**Issue by stevenfla** [GhostWriters/DockSTARTer#861]
new ds install fails in "Installing latest docker-compose" on fresh install of Centos 7 latest 

**To Reproduce**
install CentOS-7-x86_64-Minimal-1908.iso
yum update
install stated preq for ds
reboot  
login 
bash -c "$(curl -fsSL https://get.dockstarter.com)"
Failed to install the latest docker-compose
rebooted 
executed ds -i -x 

log output 
----------Cut---------------
+ echo -e '2020-01-26 09:35:47 [INFO  ]   Installing latest docker-compose.'
2020-01-26 09:35:47 [INFO  ]   Installing latest docker-compose.
+ run_script run_python -m pip install -IUq docker-compose
+ local UPDATED_COMPOSE
++ docker-compose --version
++ sed -E 's/.* version ([^,]*)(, build .*)?/\1/'
++ echo 0
+ UPDATED_COMPOSE=0
+ vergt 1.25.3 0
+ vergte 0 1.25.3
+ printf '%s\n%s' 1.25.3 0
+ sort -C -V
+ fatal 'Failed to install the latest docker-compose.'
+ tee -a /tmp/dockstarter.log
++ date '+%F %T'
+ echo -e '2020-01-26 09:35:59 [FATAL ]   Failed to install the latest docker-compose.'
2020-01-26 09:35:59 [FATAL ]   Failed to install the latest docker-compose.
+ exit 1
+ cleanup
+ local -ri EXIT_CODE=1
+ repo_exists

--------Cut-------------------

 which docker-compose
/usr/local/bin/docker-compose

 docker-compose --version
docker-compose version 1.25.3, build unknown

ls -al /usr/local/bin/docker-compose
-rwxr-xr-x. 1 root root 213 Jan 26 11:29 /usr/local/bin/docker-compose

* Could open a 2nd issue but think this may be related to this one in addition to vergt #860

Suffering from a related problem on previously installed ds instance with same Centos version
Updated ds at some point in the past and am now seeing these errors. 

------Cut------
which docker-compose
/usr/bin/docker-compose

docker-compose --version
/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)
docker-compose version 1.24.0, build 0aa5906
---------Cut---------

 Thank you

**Comment by nemchik** [comment]
```
sudo nano /etc/sudoers
```
Locate the line with `secure_path`
Comment it out by adding `#` to the very beginning of the line
Reboot
Try to install DS again from the instructions on the home page

**Comment by stevenfla** [comment]
Worked perfectly ! Thank you very much for your time. 

For the other host reporting the dependency errors in python when compose is run, made the same change. re-ran the dependency installation, which did install a few things but did not help with the 
compose dependence errors noted above in previous post. 

Noted the following: 
/usr/bin/docker-compose was present where on the new successful install it's in /usr/local/bin
So removed /usr/bin/docker-compose, ran ds and installed dependencies. DS installed compose 
in /usr/local/bin which this newly installed version now has no dependency warnings.

Thank you again for your help and time !!
