### ISSUE TITLE
OpenVPN-AS - container name and letsencrypt subfolder label conflict

### ISSUE THREAD

**Issue by Antexa** [GhostWriters/DockSTARTer#864]
Hey, 

According to nginx site-conf : https://github.com/linuxserver/reverse-proxy-confs/blob/master/openvpn-as.subdomain.conf.sample : 

```
location /admin {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_ovpn openvpn-as;
        proxy_pass https://$upstream_ovpn:943;
    }

```

```
root@deb:/# ping openvpnas
PING openvpnas (172.19.0.6): 56 data bytes
64 bytes from 172.19.0.6: seq=0 ttl=64 time=0.281 ms
64 bytes from 172.19.0.6: seq=1 ttl=64 time=0.111 ms
64 bytes from 172.19.0.6: seq=2 ttl=64 time=0.094 ms
^C
--- openvpnas ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.094/0.162/0.281 ms
root@deb:/# ping openvpn-as
ping: bad address 'openvpn-as'
```

The default container name of openvpn should be openvpn-as instead of openvpnas ? 
Could it be possible to rename the openvpn-as app according to the site-conf dns resolve entry ? 

`set $upstream_ovpn openvpn-as;`

**Comment by nemchik** [comment]
DockSTARTer uses container names as variables in your `.env` file. Dashes (`-`) are not valid in variable names. As such this project simply omits the dashes. You can easily modify the proxy sample to remove the dash from the upstream name.

`set $upstream_ovpn openvpnas;`

**Comment by Antexa** [comment]
Fair enough, I think you could add it in the documentation. 

This is not a big issue, easy to find, but I think it could be appreciate by other users.

**Comment by nemchik** [comment]
That's not a bad idea. All of our doc pages have an edit button in the top right corner if you'd like to contribute ;)

I'm on mobile all day today so I likely won't get around to it today.
