### ISSUE TITLE
Can't install Dockstarter Ubuntu fails

### ISSUE THREAD

**Issue by chest069** [GhostWriters/DockSTARTer#866]
**Describe the bug**

I am using Ubuntu 64bit and do sudo apt-get install curl git and that goes fine. I then do bash -c "$(curl -fsSL https://get.dockstarter.com)" and I get the following:
2020-02-04 02:03:50 [INFO  ]   Updating repositories.
2020-02-04 02:03:54 [FATAL ]   Failed to get updates from apt.
2020-02-04 02:03:54 [ERROR ]   DockSTARTer did not finish running successfully.
2020-02-04 02:03:54 [ERROR ]   DockSTARTer did not finish running successfully.
I am then found at the command prompt.

**To Reproduce**
To reproduce run:
bash -c "$(curl -fsSL https://get.dockstarter.com)"
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
The program show download and install no problem.
**Screenshots**

**System**
(please complete the following information):
OS: Ubuntu
- OS: [e.g. Debian]
Version 18.04
**Additional context**
Can you let me know what to do? Thanks for any help. chest069@gmail.com

**Comment by nemchik** [comment]
Sorry for the delay here. Can you run
```
sudo apt-get update
```
and post the output here?
