### ISSUE TITLE
App list descriptions blank

### ISSUE THREAD

**Issue by KleeziE** [GhostWriters/DockSTARTer#868]
What am I missing here?

![IMG-0410](https://user-images.githubusercontent.com/5607847/74080835-f63cfe00-49fc-11ea-8421-2e91eeb41715.JPG)

**Comment by robschwieb** [comment]
Same here. Thought it might be an issue with Ubuntu 18.04 Server so I tried the standard Desktop edition and no dice.

**Comment by nemchik** [comment]
This seems like an issue with yq. I've reproduced something similar.

Can anyone having the issue run `yq-go --version` and post the output here?

**Comment by schbaeggle** [comment]
```
pi@raspberrypi:~ $ yq-go --version
yq version 3.1.0
```

**Comment by robschwieb** [comment]
rob@ubuntu-server:~$ yq-go --version
yq version 3.1.0

**Comment by nemchik** [comment]
Looks like an issue with yq 3.1.0. Please have a look at the testing instructions in https://github.com/GhostWriters/DockSTARTer/pull/869

**Comment by nemchik** [comment]
A proper more permanent fix is now merged. Anyone seeing this should run
```
ds -u
ds -i
ds -c
```
