### ISSUE TITLE
Mellow is stable enough to be a part of DockSTARTer

### ISSUE THREAD

**Issue by mouzzampk2014** [GhostWriters/DockSTARTer#873]
Hi, 
I am using mellow override from last couple of months without any issues. 
Currently no `arm` image but developer working on it.  Developer is very active and keep adding new features.
Mellow works with Ombi, Tautulli, Radarr and Sonarr and send notifications to Discord Bot. But developer already working on Slack and Telegram.
Two tags are available, `latest` and `develop`
Thanks

**Comment by nemchik** [comment]
Can you link to their project homepage or github as well as their docker hub image?

**Comment by mouzzampk2014** [comment]
Here we go https://github.com/v0idp/Mellow and https://hub.docker.com/r/voidp/mellow/

**Comment by nemchik** [comment]
Sorry I missed that this got marked. Is there any benefit to this over requestrr?

**Comment by mouzzampk2014** [comment]
Hi, I dont think there is any except tautulli stats but requestrr is already stable enough and working perfectly fine with number of features missing from Mellow. So let's keep it close.
