### ISSUE TITLE
Please add Tdarr

### ISSUE THREAD

**Issue by chest069** [GhostWriters/DockSTARTer#874]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like for this to be added because even though Unamic is similar Tdarr offers more control.

**Describe alternatives you've considered**
I have tried Unamic which you include but I don't like that it offers very little in the way of control.

**Additional context**

**Comment by jodfie** [comment]
i'll make an Override page for this until it is decided on including it in DS @nemchik can you assign to me?
