### ISSUE TITLE
Unable to run first full configruation

### ISSUE THREAD

**Issue by pavili0n** [GhostWriters/DockSTARTer#876]
[WARN  ]   /home/user/.docker/compose/.env not found. Copying example template.
[WARN  ]   Please verify that ~ is not used in /home/user/.docker/compose/.env file.
[ERROR ]   Unable to find labels for "APPNAME"
[FATAL ]   Failed to find "APPNAME"_ENABLED in /home/user/.docker/compose/.env
[ERROR ]   DockSTARTer did not finish running successfully.

After running the initial git and running sudo reboot - when running DS for the first time and selecting the packages I always receive the above errors stating failed to find "" in /.env

**System**

Ubuntu 18.04 Server

**Comment by nemchik** [comment]
Which apps were selected?

**Comment by pavili0n** [comment]
I have tried with several different apps from Portainer , Sonarr, Radarr, Sabnzbd,

**Comment by JonSchaeffer** [comment]
I am also having this issue with apps Jackett, Portainer, Sonarr, Radarr, Plex, Samba, TransmissionVPN, and Ombi.

**Comment by nemchik** [comment]
Can either of you post the contents of `~/.docker/compose/.env` here please?

**Comment by JonSchaeffer** [comment]
`# Global Settings
COMPOSE_HTTP_TIMEOUT=60
DOCKERCONFDIR=/home/jon/.config/appdata
DOCKERGID=999
DOCKERHOSTNAME=DockSTARTer
DOCKERLOGGING_MAXFILE=10
DOCKERLOGGING_MAXSIZE=200k
DOCKERSHAREDDIR=/home/jon/.config/appdata/shared
DOWNLOADSDIR=/mnt/downloads
MEDIADIR_AUDIOBOOKS=/mnt/medialibrary/audiobooks
MEDIADIR_BOOKS=/mnt/medialibrary/books
MEDIADIR_COMICS=/mnt/medialibrary/comics
MEDIADIR_MOVIES=/mnt/medialibrary/movies
MEDIADIR_MUSIC=/mnt/medialibrary/music
MEDIADIR_TV=/mnt/medialibrary/tv
PGID=1000
PUID=1000
TZ=America/Chicago

# VPN Settings
LAN_NETWORK=192.168.2.0/24
NS1=1.1.1.1
NS2=8.8.8.8
VPN_ENABLE=yes
VPN_OPTIONS=
VPN_OVPNDIR=/home/jon/.config/appdata/.openvpn
VPN_PASS=
VPN_PROV=custom
VPN_USER=

# END OF DEFAULT SETTINGS
OUROBOROS_CLEANUP="true"
OUROBOROS_CRON="0 4 * * *"
OUROBOROS_ENABLED=false
OUROBOROS_IGNORE=""
OUROBOROS_INTERVAL="300"
OUROBOROS_LOG_LEVEL="info"
OUROBOROS_MONITOR=""
OUROBOROS_NETWORK_MODE=""
OUROBOROS_NOTIFIERS=""
OUROBOROS_REPO_PASS=""
OUROBOROS_REPO_USER=""
OUROBOROS_SELF_UPDATE="true"
PORTAINER_ENABLED=false
PORTAINER_NETWORK_MODE=""
PORTAINER_PORT_9000="9000"
`

This was unedited by me and I believe copied from the .env.example the first time I ran `ds`.

**Comment by nemchik** [comment]
Please run `yq-go --version`

**Comment by JonSchaeffer** [comment]
`yq version 3.2.0`

**Comment by nemchik** [comment]
Wait... @JonSchaeffer you have false for both apps above being enabled. Did you disable them from the menu?

**Comment by nemchik** [comment]
I've found what's going on. This is a bug. I'll fix it shortly.

**Comment by nemchik** [comment]
Please run one of the following
```
# x86_64/amd64
sudo curl -fsL "https://github.com/mikefarah/yq/releases/download/3.1.2/yq_linux_amd64" -o /usr/local/bin/yq-go

# armv7/armhf
sudo curl -fsL "https://github.com/mikefarah/yq/releases/download/3.1.2/yq_linux_arm" -o /usr/local/bin/yq-go

# armv8/aarch64
sudo curl -fsL "https://github.com/mikefarah/yq/releases/download/3.1.2/yq_linux_arm64" -o /usr/local/bin/yq-go
```
Then everything should work fine.

There's an issue with version 3.2.0 of yq https://github.com/mikefarah/yq/issues/381

DS will not upgrade your version of yq unless it's below version 3.1.0, so the version installed by the commands above should work correctly.

**Comment by JonSchaeffer** [comment]
Working now on my end. Thanks! :D

**Comment by pavili0n** [comment]
Thanks all had to step out shortly after submitting glad to hear the issue had been found and worked on
