### ISSUE TITLE
Failed to find "DELUGEVPN"_ENABLED in .env

### ISSUE THREAD

**Issue by ohthehugemanatee** [GhostWriters/DockSTARTer#877]
**Describe the bug**
Updated to latest master branch, and now can't get through configuration. Once I select the services to run, I crash back to the prompt with error:
`Failed to find "DELUGEVPN"_ENABLED in /home/ohthehugemanatee/.docker/compose/.env` 

In this case, DelugeVPN is alphabetically the first service I had specified In my .env file, but it works with any service. In my .env file, I do indeed have `DELUGEVPN_ENABLED`. Looks like the quotes are being included literally.

**To Reproduce**
1) Existing installation from version `776bab053a12dc45018e3bbfe1d171abc731f554`. I also tried with a fresh .env file and had the same problem, though.
2) run `ds` from the prompt. In the menu: Configuration > Select Apps. Or Full Installation works, too.
3) Select at least one app and hit "OK"
4) Observe error.

**Expected behavior**
It should find the existing configuration and move on to the configuration menus.

**System**

- OS: Ubuntu
- Version: 18.04 LTS

**Comment by nemchik** [comment]
This is actually a duplicate issue. The solution is here https://github.com/GhostWriters/DockSTARTer/issues/876#issuecomment-592984719

A permanent fix will be available when the issue with yq is resolved.
