### ISSUE TITLE
Problem: package docker-ce-3:19.03.7-3.el7.x86_64 requires containerd.io >= 1.2.2-3, but none of the providers can be installed

### ISSUE THREAD

**Issue by MillerBoss** [GhostWriters/DockSTARTer#879]
**Describe the bug**
Installing DockSTARTer fails with error `Problem: package docker-ce-3:19.03.7-3.el7.x86_64 requires containerd.io >= 1.2.2-3, but none of the providers can be installed` 

**To Reproduce**
Ran:
`sudo yum install curl git`
`bash -c "$(curl -fsSL https://get.dockstarter.com)"`
Receive error:
```
...
2020-03-08 12:43:31 [NOTICE]   Upgrading packages. Please be patient, this can take a while.
CentOS-8 - AppStream                                                                        13 kB/s | 4.3 kB     00:00
CentOS-8 - Base                                                                             11 kB/s | 3.8 kB     00:00
CentOS-8 - Extras                                                                          5.4 kB/s | 1.5 kB     00:00
Docker CE Stable - x86_64                                                                  156 kB/s | 3.5 kB     00:00
Error:
 Problem: package docker-ce-3:19.03.7-3.el7.x86_64 requires containerd.io >= 1.2.2-3, but none of the providers can be installed
  - cannot install the best update candidate for package docker-ce-3:18.09.1-3.el7.x86_64
  - package containerd.io-1.2.10-3.2.el7.x86_64 is excluded
  - package containerd.io-1.2.13-3.1.el7.x86_64 is excluded
  - package containerd.io-1.2.2-3.3.el7.x86_64 is excluded
  - package containerd.io-1.2.2-3.el7.x86_64 is excluded
  - package containerd.io-1.2.4-3.1.el7.x86_64 is excluded
  - package containerd.io-1.2.5-3.1.el7.x86_64 is excluded
  - package containerd.io-1.2.6-3.3.el7.x86_64 is excluded
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
2020-03-08 12:43:33 [FATAL ]   Failed to upgrade packages from dnf.
2020-03-08 12:43:33 [ERROR ]   DockSTARTer did not finish running successfully.
2020-03-08 12:43:33 [ERROR ]   DockSTARTer did not finish running successfully.
```

The machine has been rebooted and command ran multiple times with the same error.

**System**
- OS: CentOS
- Version 8.1.1911
Fresh install

**Comment by nemchik** [comment]
Hi! Sorry for the delayed response! It looks like CentOS 8 is not currently fully supported by `docker-ce` which is what DS tries to install for you.

https://github.com/docker/docker-install/issues/154
https://github.com/docker/docker-ce-packaging/pull/416

That being said you may be able to find a way to manually install docker (preferably `docker-ce` but other options might work as well). Once installed as long as you can run `docker --version` and see a version number above `17.09.0` DS should skip attempting to install `docker-ce` for you and should work.
https://github.com/GhostWriters/DockSTARTer/blob/9c7cf2f39068a4daeee84f2f5d62659e93469505/.scripts/install_docker.sh#L6

**Comment by nigelhooper** [comment]
Sorry to hijack, but I have hit the same problem as OP also on CentOs 8.1.  I have tried 
 sudo dnf -y  install docker-ce --nobest

and then
 docker --version

which gives me
 Docker version 19.03.8, build afacb8b

But when I rerun 
  bash -c "$(curl -fsSL https://get.dockstarter.com)"

I am still stuck with
package docker-ce-3:19.03.8-3.el7.x86_64 requires containerd.io >= 1.2.2-3, but none of the providers can be installed

**Comment by nigelhooper** [comment]
I have got a little further, you can manually install  containerd.io as follows:
cd /tmp
sudo yum install wget
sudo wget https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
sudo yum install containerd.io-1.2.6-3.3.el7.x86_64.rpm

But I then get stuck at:
[FATAL ]   Failed to install the latest docker-compose.

I have tried:
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

but still cant get past:
[FATAL ]   Failed to install the latest docker-compose.

docker-compose --version gives:
docker-compose version 1.25.4, build unknown

**Comment by nigelhooper** [comment]
I believe I have finally got there:

 sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose

sudo chmod +x /usr/bin/docker-compose

hope this helps @MillerBoss

**Comment by nemchik** [comment]
Looks like this should be resolved upstream now.
