### ISSUE TITLE
Provide option to choose directory where data will be stored

### ISSUE THREAD

**Issue by Antakor** [GhostWriters/DockSTARTer#881]
**Is your feature request related to a problem? Please describe.**
Root partition doesn't have much space, but there is no quick way to choose another directory for all data directories. The only option would be to manually configure the directories for all services manually, but there should be a simpler alternative.

**Describe the solution you'd like**
A global configuration option to change the `/mnt/` in front of all data paths to something else

**Describe alternatives you've considered**
Symlinking `/mnt` to `/another/path` but nextcloud will not let me configure an administrator account and shows a database error.

**Comment by nemchik** [comment]
You can actually set whatever paths you want for the paths DS uses to mount volumes into containers. If you have a look at `~/.docker/compose/.env` all the paths can be edited from there. Feel free to change them to whatever you like. After making changes to this file you will need to run `ds -c` to make the changes take effect. You can also change these from the GUI in the `ds` config menu.

Keep in mind that the paths inside the container will not usually match the paths on your host system. Individual readmes for each app container will tell you what mounts to expect. Most containers in DS use linuxserver.io images, so you can often look up for example `linuxserver/nextcloud` on google to see the readme and find where the path inside the container will me. DS has a variable for nextcloud's data folder `NEXTCLOUD_DATADIR` which mounts a volume to `/data` inside the container.
