### ISSUE TITLE
Cloudflare dns default settings needs RRTYPE set to A not a

### ISSUE THREAD

**Issue by prabbit237** [GhostWriters/DockSTARTer#882]
**Describe the bug**

The default settings for cloudflaredns result in "ERROR: Failed To Get Public IPv4 Address"

**To Reproduce**

Add CloudflareDNS with default settings for CLOUDFLAREDDNS_RRTYPE

````
           ┌────────────────────┤ DockSTARTer ├─────────────────────┐
           │ What would you like set for CLOUDFLAREDDNS_RRTYPE?     │
           │                                                        │
           │                    Keep Current A                      │
           │                    Use Default  a                      │
           │                    Enter New                           │
           │                                                        │
           │                                                        │
           │            ┌────┐               ┌────────┐             │
           │            │ Ok │               │ Cancel │             │
           │            └────┘               └────────┘             │
           │                                                        │

````
Using the default of (lowercase) "a" results in the following section not working:
````
  if [ "$RRTYPE" == "A" ]; then
    # try dns method first.
    IP_ADDRESS=$(dig +short @1.1.1.1 ch txt whoami.cloudflare | tr -d '"')

    # if dns method fails, use http method
    if [ "$IP_ADDRESS" = "" ]; then
      IP_ADDRESS=$(curl -sf4 https://ipinfo.io | jq -r '.ip')
    fi

    echo $IP_ADDRESS
````
**Expected behavior**

Expected that it'd find the public IP address to match the DNS.

**Screenshots**

**System**
(please complete the following information):

- OS: [e.g. Debian] 

Linux Photo 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
Changing to A works fine. But the OOBE setup uses a and it breaks and not in an obvious way.

**Comment by nemchik** [comment]
That is not what I am seeing. We default to an uppercase `A`
https://github.com/GhostWriters/DockSTARTer/blob/b303d1f2a6cf83155c6d8a6c50d1ab4d73b01fa2/compose/.apps/cloudflareddns/cloudflareddns.labels.yml#L14
I navigated to that menu myself and I see an uppercase `A` for `Use Default`

**Comment by nemchik** [comment]
Please try running `ds -u` and then `ds -vi` to ensure you are up to date.

**Comment by prabbit237** [comment]
That'll teach me to "update first, ask questions later" *laugh* And clue one to you that I hadn't done so would have been that I was talking about *CLOUDFLAREDDNS_RRTYPE* and it's now *CLOUDFLAREDDNS_RECORDTYPES*

Anyways, yeah, the update shows A as being the default now. It did take me some time of poking around in the cloudflaredns docker image itself to figure out WHY it wasn't working as the error message from there wasn't clear/detailed but that's not Dockstarter's fault.
