### ISSUE TITLE
Documentation for back up and restore 

### ISSUE THREAD

**Issue by soile1991** [GhostWriters/DockSTARTer#884]
**Is your feature request related to a problem? Please describe.**
Since the backup function was removed can you tell us which directories we should backup? 

**Describe the solution you'd like**
Add a step by step guide on documentation on how to back up and restore (directories config files etc).

**Comment by nemchik** [comment]
At this point the recommendation is to use duplicati. They have their own documentation about backup and restore. Which folders you backup is really up to you. DS backups (that were removed) defaulted to backing up your `DOCKERCONFDIR` directory. Your `.env` file (`~/.docker/compose/.env`) contains a variable named `DOCKERCONFDIR`. It's usual value will be `/home/$USER/.config/appdata`, but you can change it if you want, and older installs of DockSTARTer defaulted to a different location.

You're also welcome to use any other backup solution you might prefer, and backup any folders you'd like.

**Comment by jodfie** [comment]
reopen haven't done it yet.

**Comment by angrycuban13** [comment]
Actively being worked on

**Comment by angrycuban13** [comment]
[rsnapshot](https://dockstarter.com/apps/rsnapshot/) has been added and I will actively work on getting [Duplicacy](https://dockstarter.com/apps/rsnapshot/) added to our repositry of apps.
