### ISSUE TITLE
Error on Compose with fresh Pi-Hole application selected

### ISSUE THREAD

**Issue by kazo0** [GhostWriters/DockSTARTer#901]
**Describe the bug**
Adding the Pi-Hole app to DS causes an error on Compose

**To Reproduce**

- Add Pi-Hole as an app
- Run `ds -c`

**Expected behavior**
Pi-Hole container should be created

**Actual behavior**
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.pihole.ports contains an invalid type, it should be a number, or an object
services.pihole.ports contains an invalid type, it should be a number, or an object
services.pihole.ports contains an invalid type, it should be a number, or an object
2020-04-26 23:58:54 [FATAL ]   Docker Compose failed.
2020-04-26 23:58:54 [ERROR ]   DockSTARTer did not finish running successfully.
```

**System**
(please complete the following information):

- OS: Raspbian
- Version: 10 (buster)

**Additional context**

**Comment by kazo0** [comment]
As of [Docker Pi-Hole v4.2.2](https://hub.docker.com/r/pihole/pihole/) it looks like ServerIP is no longer needed and cannot be used in the ports

**Comment by nemchik** [comment]
You'll need to open `~/.docker/compose/.env` and find the `PIHOLE_ServerIP` variable and set it to your server IP address.

The default value `192.168.x.x` is not a valid IP address, and this is why compose is giving an error.
