### ISSUE TITLE
failes to complete docker installs

### ISSUE THREAD

**Issue by Jmilesy** [GhostWriters/DockSTARTer#905]
when i try to run DockSTARTer it allows me to go through all teh settings, but at the end i receive the following: 
2020-05-03 14:26:27 [FATAL ]   Failed to run yml merge script.
2020-05-03 14:26:27 [ERROR ]   DockSTARTer did not finish running successfully.

I installed as per the instructions, and could run the programme, it is just when it gets to the stage of confirming the global settings.

any help would be gratefully received.

**Comment by nemchik** [comment]
Helping on Reddit
https://www.reddit.com/r/DockSTARTer/comments/gcqthk/fails_to_finish/
