### ISSUE TITLE
Support for 20.04 LTS

### ISSUE THREAD

**Issue by renedis** [GhostWriters/DockSTARTer#907]
It won't install on Ubuntu Server 20.04 LTS.

Installing docker won't work either. But I can set the sources.list to eoan and after that docker does work. Except this trick won't work for dockSTARTer.

Please fix this or tell me how to bypass

**Comment by nemchik** [comment]
If you can run `docker --version` DS should work fine. Just run `ds` and go to config > full.

Keep in mind that DS doesn't officially support installations that aren't officially supported by `docker-ce` which (as of writing) doesn't support 20.04.

I strongly recommended you stick with 18.04 until docker makes official stable releases for 20.04.

**Comment by renedis** [comment]
20.04 has been released on 23-04-2020 as stable.

**Comment by renedis** [comment]
Got it working with manually installing docker and docker-compose.
For docker I had to edit the soucres.list to eoan or bionic.

I also needed to manually remove /tmp/dockstarter.log each time if I want to run DS.
It only runs if I start it from home folder/.docker and run "./main.sh"

**Comment by nemchik** [comment]
DockSTARTer uses the official `docker-ce` install script https://github.com/docker/docker-install

This relies on stable releases of `docker-ce` in the official docker repos https://download.docker.com/linux/ubuntu/dists/

As of writing there is no release at all (not even test releases) for 20.04 (focal).

Those releases are not in our control. I will again recommended that you use an Ubuntu LTS that has a stable release of `docker-ce`, which at the moment is 18.04.

**Comment by trendless** [comment]
Although there still appears to be no stable release for 20.04, DockSTARTer does install, but only after a fresh reboot, then ds only runs after a fresh reboot. This error shows up every time install/run is attempted if not after a fresh reboot:

`/home/[username]/.docker/main.sh: line 295: /tmp/dockstarter.log: Permission denied
tee: /tmp/dockstarter.log: Permission denied
2020-05-20 15:16:57 [ERROR ]   DockSTARTer did not finish running successfully.`

Not looking for support, just providing info. Great project, nemchik, Thanks!

**Comment by tezgno** [comment]
I would like to see if this can be revisited. As of May 18th, the official 20.04 Focal release of docker-ce has been published. I have the official release installed and it is still breaking after running once. So something else, outside of official release of docker, is causing an issue.

**Comment by tezgno** [comment]
> Although there still appears to be no stable release for 20.04, DockSTARTer does install, but only after a fresh reboot, then ds only runs after a fresh reboot. This error shows up every time install/run is attempted if not after a fresh reboot:
> 
> `/home/[username]/.docker/main.sh: line 295: /tmp/dockstarter.log: Permission denied tee: /tmp/dockstarter.log: Permission denied 2020-05-20 15:16:57 [ERROR ] DockSTARTer did not finish running successfully.`
> 
> Not looking for support, just providing info. Great project, nemchik, Thanks!

This is now available:

https://download.docker.com/linux/ubuntu/dists/focal/stable/

Yet it still isn't working with the official docker-ce.

**Comment by trendless** [comment]
My mistake, tezgno. Thanks for the correction. [This](https://docs.docker.com/engine/install/ubuntu/) is the page where I still didn't see 20.04 listed; must be out of date.

**Comment by tezgno** [comment]
Ah! Good find trendless. I suspect that they published the repo but have yet to update their page. This was released only two days ago.

**Comment by trendless** [comment]
Perhaps something in the latest Docker update, DockSTARTer, and/or the way 20.04 handles log files or file locks is blocking access to /tmp/dockstarter.log...

**Comment by nemchik** [comment]
This seems like a permissions issue that I've been chasing like a ghost for some time. it only seems to happen when a new Ubuntu version is released and then somehow settles down after some time without anything recognizable changing. Regardless I can look into a fix and will report back here when I come up with something.

**Comment by nemchik** [comment]
Please have a look at the test instructions here https://github.com/GhostWriters/DockSTARTer/pull/914 and let me know if this resolves the issue for anyone running 20.04 who was previously having issues.

**Comment by tezgno** [comment]
Just tried those instructions and, unfortunately, still not working for me:

`tezgno@request:/tmp$ ds -fiv
tee: /tmp/tmp.FylURX6MYC: Permission denied
2020-05-21 00:16:04 [INFO  ]   Setting permissions for /home/tezgno/.docker/main.sh
tee: /tmp/tmp.FylURX6MYC: Permission denied
2020-05-21 00:16:04 [ERROR ]   DockSTARTer did not finish running successfully.
`

**Comment by nemchik** [comment]
@tezgno i've pushed an additional change just now. can you try to rerun the test instructions from the top and let me know if that gets it?

**Comment by tezgno** [comment]
That did it!

**Comment by trendless** [comment]
Appears to be working for me, too. I tested `ds` immediately before running the #914 instructions; it errored at the end, but I can run `ds` with no issues, repeatedly now. I'll test after reboot and make some changes and monitor things and report back if I run into it again.

```user@server:~$ cd ~/.docker
user@server:~/.docker$ git fetch -p
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 2), reused 6 (delta 2), pack-reused 0
Unpacking objects: 100% (6/6), 6.32 KiB | 1.05 MiB/s, done.
From https://github.com/GhostWriters/DockSTARTer
 * [new branch]      log        -> origin/log
user@server:~/.docker$ git reset --hard origin/log
HEAD is now at d9ac940 Skip chown on mktemp log
user@server:~/.docker$ cd ~/
user@server:~$ ds -fiv
2020-05-20 18:58:25 [INFO  ]   Setting permissions for /home/user/.docker/main.sh
2020-05-20 18:58:25 [INFO  ]   Taking ownership of /home/user/.docker/main.sh for user 1000 and group 1000
2020-05-20 18:58:25 [INFO  ]   Setting file and folder permissions in /home/user/.docker/main.sh
2020-05-20 18:58:25 [INFO  ]   Setting executable permission on /home/user/.docker/main.sh
2020-05-20 18:58:25 [INFO  ]   Updating repositories.
2020-05-20 18:58:32 [NOTICE]   Upgrading packages. Please be patient, this can take a while.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  apport-symptoms libglu1-mesa libxatracker2 libxss1 libxvmc1 python3-blinker
  python3-entrypoints python3-httplib2 python3-jwt python3-lazr.uri
  python3-problem-report python3-simplejson python3-systemd python3-wadllib
  x11-apps x11-session-utils xbitmaps xfonts-scalable xinit xinput
  xserver-xorg-core xserver-xorg-input-all xserver-xorg-input-libinput
  xserver-xorg-input-wacom xserver-xorg-video-all xserver-xorg-video-amdgpu
  xserver-xorg-video-ati xserver-xorg-video-fbdev xserver-xorg-video-intel
  xserver-xorg-video-nouveau xserver-xorg-video-qxl xserver-xorg-video-radeon
  xserver-xorg-video-vesa xserver-xorg-video-vmware
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2020-05-20 18:58:32 [INFO  ]   Installing dependencies.
2020-05-20 18:58:33 [INFO  ]   Installing python dependencies.
2020-05-20 18:58:33 [INFO  ]   Removing unused packages.
2020-05-20 18:58:41 [INFO  ]   Cleaning up package cache.
2020-05-20 18:58:42 [INFO  ]   Removing conflicting Docker packages.
2020-05-20 18:58:42 [NOTICE]   Installing latest docker. Please be patient, this can take a while.
2020-05-20 18:58:42 [INFO  ]   Downloading docker install script.
2020-05-20 18:58:43 [INFO  ]   Running docker install script.
# Executing docker install script, commit: 26ff363bcf3b3f5a00498ac43694bf1c7d9ce16c
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20
^C
2020-05-20 18:58:52 [ERROR ]   DockSTARTer did not finish running successfully.
2020-05-20 18:58:52 [ERROR ]   DockSTARTer did not finish running successfully.
user@server:~$ ds
user@server:~$ ds

**Comment by nemchik** [comment]
@trendless please run `ds -fiv` but don't press Ctrl+c when it shows up. Let it sit and finish.

**Comment by trendless** [comment]
> @trendless please run `ds -fiv` but don't press Ctrl+c when it shows up. Let it sit and finish.

If I run into any further issues, I will. Like I said, regardless of any "error", everything's working fine.

**Comment by nemchik** [comment]
#914 is now merged. You can run `ds -vu` to update DS. You already have the changes so it won't make a big difference, but `ds -u` is how you update whenever you want to (the `-v is just verbose). You can also update DS though the menu.

**Comment by trendless** [comment]
Tyvm, good sir!
*--*

*  trendless..*

**Comment by tezgno** [comment]
Thanks very much. I'm back on the master branch and all is working correctly!
