### ISSUE TITLE
Prometheus and default exporters would be a great alternative for monitoring purposes!

### ISSUE THREAD

**Issue by lmarzliak** [GhostWriters/DockSTARTer#910]
This request is not related to a problem and this is just another set of tools to help users monitor systems. This also works grate with containers.

**Describe the solution you'd like**
"Prometheus is a free software application used for event monitoring and alerting. It records real-time metrics in a time series database built using a HTTP pull model, with flexible queries and real-time alerting". As the site description says it can store dataset from almost any thing and put in a beaultiful monitoring dashboard using grafana for example. 

It consists in a capture tool (prometheus node exporter) and prometheus itself.

https://prometheus.io/

**Comment by jodfie** [comment]
Can you edit your issue and the template and provide links or information on this @lmarzliak ?

**Comment by lmarzliak** [comment]
> Can you edit your issue and the template and provide links or information on this @lmarzliak ?

done. if you need further information just let me know.

br,
