### ISSUE TITLE
How to remove {DOCKERHOSTNAME} from one of the container?

### ISSUE THREAD

**Issue by ajhorvath20** [GhostWriters/DockSTARTer#912]
Hi, need little help with qbittorrent image. I am using wireguard in client mode and want to connect qbittorrent too. Only thing is stopping is this error, if I used the image in override then works fine but when I use it from ds then I get this error, I think because both are conflicting. I was talking the same with linuxserver team.

`ERROR: for qbittorrent  Cannot create container for service qbittorrent: conflicting options: hostname and the network mode`

Thank you so much

**Comment by angrycuban13** [comment]
What if you create an override for `qbittorrent` to use a different hostname? For instance:

```qbittorrent:
    hostname: qbittorrent```

**Comment by nemchik** [comment]
This actually sounds like a legit bug I need to fix.

**Comment by nemchik** [comment]
Ok, wait not a bug. Please post your override file as well as the section in your .env file containing your qbittorrent variables.
