### ISSUE TITLE
Adding sqlitebrowser

### ISSUE THREAD

**Issue by mytvpro** [GhostWriters/DockSTARTer#916]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
could add this to list of included apps https://hub.docker.com/r/portiad/sqlitebrowser/dockerfile/

**Additional context**
is there s a guide to adding our own apps to our local ds? then we could stop bugging you guys....

**Comment by angrycuban13** [comment]
Nothing is restricting you from adding your own applications. You just need to use a `docker-compose.override.yml` file to specify what you want to use. You can find how to do so [here](https://dockstarter.com/advanced/overrides/)

**Comment by mytvpro** [comment]
Thank you I found out about the override after this

**Comment by nemchik** [comment]
It's still valid to ask for apps to be included, so I'm going to reopen this. I haven't put time into adding new stuff in a while.

**Comment by jodfie** [comment]
i'll make an Override page for this until it is decided on including it in DS @nemchik can you assign to me?

**Comment by angrycuban13** [comment]
@mytvpro is there another project that is being maintained? That project has not been touched in over 5 years.
