### ISSUE TITLE
coach potato username & password

### ISSUE THREAD

**Issue by mildfuzz** [GhostWriters/DockSTARTer#917]
I have installed coachpotato. It required a username and password to get into the UI. I did not set one, it's not an option when setting app config and I can't find a config file anywhere that might contain it. HELP.

**Comment by nemchik** [comment]
I can't see any documentation on couchpotato's website about a default username and password.

You can try running the following
```
docker stop couchpotato
ds -p
# THIS NEXT LINE WILL CLEAR ALL COUCHPOTATO SETTINGS (so you can start over from scratch with couchpotato)
rm -Rf ~/.config/appdata/couchpotato
ds -c
```

**Comment by mildfuzz** [comment]
Tried this. Same result.

Incidentally, my appdata folder is empty.

**Comment by mildfuzz** [comment]
correct username was found in `~/.docker/config/couchpotato/config.ini`
