### ISSUE TITLE
Qnap Dockerstart

### ISSUE THREAD

**Issue by RobertVilaplana** [GhostWriters/DockSTARTer#919]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RobertVilaplana** [comment]
This project can run on Qts Linux s.o. in Qnap Nas? It's x86 arquitectura

**Comment by angrycuban13** [comment]
[Here](https://dockstarter.com/introduction/#system-requirements) is the list of system requirements
