### ISSUE TITLE
Deemix removed from docker

### ISSUE THREAD

**Issue by supra89t** [GhostWriters/DockSTARTer#927]
**Describe the bug**
Cannot install Deemix

**To Reproduce**

- Run DS
- Select Deemix
- See error:
2020-06-06 22:44:38 [NOTICE]   /home/plex/.docker/compose/.env does not contain any disabled apps.
Pulling deemix (bocki/deemix:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling deemix (bocki/deemix:)...
ERROR: pull access denied for bocki/deemix, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
2020-06-06 22:45:12 [FATAL ]   Docker Compose failed.
2020-06-06 22:45:12 [ERROR ]   DockSTARTer did not finish running successfully.

**System**
(please complete the following information):

- OS: Ubuntu 20.04 (Legacy installer)

**Comment by timelf123** [comment]
https://github.com/Bockiii/deemix-docker

> Dockerhub removed this container, that's why I have permanently moved to gitlab.
> Go to gitlab to see how to run this container:
> https://gitlab.com/Bockiii/deemix-docker

**Comment by nemchik** [comment]
@Bockiii would you be able to PR an update to the new image location?

**Comment by nemchik** [comment]
PR Merged.
