### ISSUE TITLE
default options for docker daemon

### ISSUE THREAD

**Issue by yitang** [GhostWriters/DockSTARTer#929]
**Describe the bug**
I add DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4" to /etc/default/docker but it has no effects to the /etc/resolv.conf file inside a container. 

**Expected behavior**
I would expect the container use google's DNS. but I get 

nameserver 127.0.0.11
options ndots:0

in /etc/resolv.conf 

**System**
raspberry pi 4

**Comment by nemchik** [comment]
DockSTARTer sets pihole up using the NS1 and NS2 variables in the VPN variable section in your .env file. You shouldn't need to modify files on the host.

**Comment by yitang** [comment]
ok. let me try NS1 and NS2 variables. but what if I don't want to install pihole?

**Comment by nemchik** [comment]
Then you would probably want to configure your host to use different nameservers. That will be easier than configuring docker to do it.
