### ISSUE TITLE
bullseye?

### ISSUE THREAD

**Issue by iopusl** [GhostWriters/DockSTARTer#930]
Just installed Linux Mint 20.  Tried installing DS, but no go because it's based on Debian Bullseye.  Any idea how I can work around?  Sorry for the inconvenience.

E: The repository 'https://download.docker.com/linux/debian bullseye Release' does not have a Release file.
2020-06-15 18:48:42 [FATAL ]   Failed to install docker.

**Comment by nemchik** [comment]
It looks like docker doesn't have a release for bullseye. This is out of our control in this repo, it's up to docker to build a release with support for bullseye. In the meantime, Ubuntu 20.04 LTS is supported and it's what I would recommend.

**Comment by nemchik** [comment]
P.s. DockSTARTer will eventually work on bullseye, but DockSTARTer depends on docker (and some other tools) and we need them to support the new OS releases in order for DockSTARTer to work.

**Comment by iopusl** [comment]
Thank you very much for your reply. Might have to go Ubuntu.

**Comment by angrycuban13** [comment]
If your issue is resolved feel free to close it, thanks!
