### ISSUE TITLE
Traktarr Image

### ISSUE THREAD

**Issue by idolize** [GhostWriters/DockSTARTer#937]
It'd be awesome to have official support for [Traktarr](https://github.com/l3uddz/traktarr)

**Describe the solution you'd like**
There is already an actively-maintained Docker image available here: https://hub.docker.com/r/eafxx/traktarr

**Describe alternatives you've considered**
Another alternative image here: https://hub.docker.com/r/cloudb0x/traktarr

**Additional context**
> Traktarr uses Trakt.tv to find shows and movies to add in to Sonarr and Radarr, respectively

This script is really nice because it allows a customizable config file with tons of rules for automatically importing content into Radarr and Sonarr (much more customization than the built-in lists support in Radarr/Sonarr)

**Comment by angrycuban13** [comment]
#948 should hopefully get this one closed

**Comment by angrycuban13** [comment]
Merged to master.

**Comment by idolize** [comment]
Thanks!

**Comment by idolize** [comment]
@angrycuban13 is this only for x86? I get the following error: "2020-07-10 04:47:58 [ERROR ]   Failed to include /home/pi/.docker/compose/.apps/traktarr/traktarr.armv7l.yml file." on a Raspberry Pi 4.

**Comment by nemchik** [comment]
PR merged to resolve.

**Comment by angrycuban13** [comment]
My bad 😅
