### ISSUE TITLE
Can't seem to update 

### ISSUE THREAD

**Issue by karl0ss** [GhostWriters/DockSTARTer#940]
trying to run a update to DockSTARTer ..

```
➜  ~ sudo ds
2020-06-28 13:12:14 [NOTICE]   Updating DockSTARTer to origin/master.
2020-06-28 13:12:16 [ERROR ]   Unable to find labels for TTRSS
➜  ~

```

whats going on?

**Comment by nemchik** [comment]
Ttrss was deprecated and removed. You will have to edit your `~/.docker/compose/.env` and remove all the ttrss variables. Freshrss is the recommended alternative.

**Comment by karl0ss** [comment]
Ok, thanks.

**Comment by karl0ss** [comment]
One thing it has one, is killed and removed the container, is there anyway I can somehow run it again to export the yaml to import to fresh?

**Comment by nemchik** [comment]
I believe the container was completely removed from docker hub. Your config should still be at `~/.config/appdata/ttrss` or `~/.docker/config/ttrss` and you may be able to somehow get what you need from there.

**Comment by karl0ss** [comment]
Ah right, thanks for the update on a Sunday..

**Comment by nemchik** [comment]
Anytime
