### ISSUE TITLE
Permission issue for Radarr docker on mounted share in /mnt/medialibrary/movies

### ISSUE THREAD

**Issue by ionutm80** [GhostWriters/DockSTARTer#950]
# Bug report

Hi, I have installed the program in an Ubuntu 20.04 VM inside FreeNAS. Everything works perfectly except one minor issue related to permissions. The Linux user created during instalation of Ubuntu is “ionut”. The program defines /mnt/medialibrary/movies as the pathwhere Radarr to import movies and indeed is working great together with Transmission for achieving this. However my existing library sits on FreeNAS so I’m able to mount it with NFS share in the /mnt/medialibrary/movies. The host user “ionut” above has write permission on the mounted share (tested by creating and removing new folders) and has UID=1000 and GID=1000. Before mounting the share Radarr is able to import movies into the folder / has write access. After the share is mounted Radarr is getting permission denied error.
The permissions on the folder /mnt/medialibrary/movies after mounting the shares are:
ionut@ubuntu-vm:/mnt/medialibrary$ ls -la
total 182
drwxr-xr-x+   8 root  root  4096 Jul  7 16:09 .
drwxr-xr-x    4 root  root  4096 Jul  7 16:09 ..
drwxr-xr-x+   2 root  root  4096 Jul  7 16:09 audiobooks
drwxr-xr-x+   2 root  root  4096 Jul  7 16:09 books
drwxr-xr-x+   2 root  root  4096 Jul  7 16:09 comics
drwxrwxr-x  164 ionut ionut  164 Jul  8 10:41 movies
drwxrwxr-x    9 ionut ionut    9 Jul  7 17:17 music
drwxrwxr-x   17 ionut ionut   17 Jul  7 16:57 tv
Please tell me how can I fix this because is driving me crazy. I do aplogize in advance if this is not considered a bug but I have nowherelse to ask. Thanks a lot for your understanding!

**Comment by ionutm80** [comment]
The NFS is mounted through /etc/fstab like this:
192.168.1.81:/mnt/Homeserver/Media/Temporary_Movies /home/ionut/media/movies nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0
Where 192.168.1.81 is the FreeNAS host.

**Comment by ionutm80** [comment]
[radarr.txt](https://github.com/GhostWriters/DockSTARTer/files/4893235/radarr.txt)

I have also attached the Radarr log.

**Comment by ionutm80** [comment]
Folder permissions from inside the Radarr Docker:

drwxrwxr-x 163 abc abc 163 Jul 8 23:47 movies

and the gid and uid for the docker user:

root@DockSTARTer:/# id abc
uid=1000(abc) gid=1000(abc) groups=1000(abc),100(users)

**Comment by ionutm80** [comment]
Nobody can help, please?

**Comment by nemchik** [comment]
You're expecting `/home/ionut/media/movies` to exist inside the container. This will not be present because folders are mapped as volumes into specific locations inside the container. In your `~/.docker/compose/.env` file you can find (near the top) the `MEDIADIR_MOVIES` variable and set it to `/home/ionut/media/movies` and then run `ds -c` to apply the changes. Once you do this you can go into Radarr and tell it to look for `/movies` and this will map to `/home/ionut/media/movies` and should work. You could then move any existing media from `/mnt/medialibrary/movies` to `/home/ionut/media/movies`.

**Comment by nemchik** [comment]
p.s. no worries opening an issue. this is more of a support discussion than a bug or feature request, so the best place to get help is going to be our discord chat https://discord.gg/YFyJpmH which is mentioned in our readme and our website on the homepage (mirror of the readme) and the support page https://dockstarter.com/basics/support/

**Comment by ionutm80** [comment]
Hi Eric and thanks for your feedback. I have done exactly what you said but Radarr Docker still cannot import the movie from the downloads folder to the /home/ionut/media/movies, same as before when the movies forlder of Radarr was mapped in the default path: /mnt/medialibrary/movies. The problems resides I think in the fact that I'm mounting a dataset from FreeNAS within that folder. Radarr Docker see the movies, can import them and when I add a new movie it can create the folder for the movie inside the mounted share but cannot move the movie file to this folder.

Please see below the permissions on the folder 

- from the Ubuntu VM host:
ionut@ubuntu-vm:~/media$ ls -la
total 105
drwxr-xr-x   3 root  root  4096 Jul 10 05:01 .
drwxr-xr-x   7 ionut ionut 4096 Jul 10 05:01 ..
drwxrwxr-x 163 ionut ionut  163 Jul 10 05:20 movies

ionut@ubuntu-vm:/$ id ionut
uid=1000(ionut) gid=1000(ionut) groups=1000(ionut),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lxd),998(docker)

- from inside the Radarr Docker:

drwxrwxr-x 163 abc  abc   163 Jul 10 08:20 movies

root@DockSTARTer:/# id abc
uid=1000(abc) gid=1000(abc) groups=1000(abc),100(users)

As you can see both the host user (ionut) and Radarr Docker user (abc) have the same UID=1000 and GID=1000.

The dataset from FreeNAS is shared with NFS and mounted in /etc/fstab:

192.168.1.81:/mnt/Homeserver/Media/Temporary_Movies /home/ionut/media/movies nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0

The share in FreeNAS has Maproot User as Ionut with UID=1000 and Maproot Group as shares with GID=1000.

If I do not mount the FreeNAS dataset everything works as intended, Radarr Docker is capable to move the downloaded movie from downloads folder to movies folder. Once I mounted the dataset from FreeNAS something changes and Radarr Docker cannnot longer move files into the movies folder but can still add empty movies folders.

Sorry but I'm completely lost here!

**Comment by ionutm80** [comment]
Ok, I have managed to solve the issue, it was a permission issue on FreeNAS side, the dataset I was mounting was owned by multiple jails. I created a new dataset specifically for Ubuntu VM and voila, everything works like magic.
