### ISSUE TITLE
Duplicati and External Hard Drive

### ISSUE THREAD

**Issue by markiljas** [GhostWriters/DockSTARTer#962]
Hello,

I've been having trouble figuring out how to make backups to external drive with Duplicati. I have backup set up for all DockSTARTer files to Dropbox via Duplicati, but I also wanted to setup a whole system backup to my external drive (which is mounted and formatted for Ubuntu).

However, when I have to choose a folder path there are no disks seen, only computer. I tried entering path manually, but after I am prompted do I want to create that folder, I am hit with: Failed to connect: Access to the path "/mnt/Backup" is denied.

Is it not possible to do backups to external drive for some reason or am I missing something painfully obvious?

Thanks!

**Comment by angrycuban13** [comment]
Can you please join our Discord and share your `.env` file showing global settings as well as your Duplicati settings

**Comment by markiljas** [comment]
Okay, did that, thanks!
