### ISSUE TITLE
Update Ouroboros Docs

### ISSUE THREAD

**Issue by jodfie** [GhostWriters/DockSTARTer#967]
assuming you had ouroboros off (bear with me)
recreated containers means variables changed in your .env or a new image was already pulled somehow
if you did not pull the image then something else might have
if you want to pull new images run ds -c pull
new images CAN mean updates to the app itself, but can also mean updates to the dependencies in the container

with ouroboros on (or watchtower or anything like that)
your containers will be updated to the latest images automatically, but compose has no idea what's updated
compose keeps track separately, and ouro/watch don't update compose's method of tracking
so compose recreates containers that are already up to date
no big deal it's basically just a restart, and you were planning on running ds -c expecting some kind of updates anyway

**Comment by angrycuban13** [comment]
#968

**Comment by angrycuban13** [comment]
Merged.
