### ISSUE TITLE
Add Dozzle docker for easy log review

### ISSUE THREAD

**Issue by rubadub-github** [GhostWriters/DockSTARTer#972]
add a new docker container for reading docker logs -- DOZZLE.
https://hub.docker.com/r/amir20/dozzle
https://github.com/amir20/dozzle

-----

  dozzle:
    image: amir20/dozzle:latest
    hostname: ${DOCKERHOSTNAME}
    ports:
     - 9999:8080
    container_name: dozzle
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
     - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /var/run/docker.sock:/var/run/docker.sock
     - ${DOCKERCONFDIR}/dozzle:/root/config
     - ${DOCKERSHAREDDIR}:/shared

**Comment by angrycuban13** [comment]
I like this one. I'll deploy it locally, test it and possibly add it to the list of apps :)

**Comment by angrycuban13** [comment]
#977 should close this one out after merging.

**Comment by angrycuban13** [comment]
Merged to master.
