### ISSUE TITLE
new dozzle container has an issue with the DOZZLE_BASE env setting

### ISSUE THREAD

**Issue by rubadub-github** [GhostWriters/DockSTARTer#989]
# Bug report

DOZZLE_BASE${DOZZLE_BASE}

missing =
===========================================

**Describe the bug**
when setting a custom DOZZLE_BASE directory (/dozzle in this example) it breaks dozzle.  

**To Reproduce**
add dozzle in DS and customize the app setting and change the base dir
![ds_instance](https://user-images.githubusercontent.com/68559237/88232343-50441f80-cc3b-11ea-8e39-43bc4fd6553a.jpg)
![override](https://user-images.githubusercontent.com/68559237/88232345-50dcb600-cc3b-11ea-9c2d-c509fbebd32f.jpg)

- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**System**
(please complete the following information):

- OS: [e.g. Debian]

**Additional context**

**Comment by nemchik** [comment]
Thanks! will be fixed in #990
