### ISSUE TITLE
Gui Improvements

### ISSUE THREAD

**Issue by TommyE123** [GhostWriters/DockSTARTer#99]
- [x] When Prompting to select desired apps. If enabled in `.env` then enable UI as well.
- [x] Set permissions on folders/files (755/644)
- [x] Set ownership on folders/files (user:group)
- [x] Prompt to run `docker-compose up -d` using UI rather then Terminal prompt.

**Comment by nemchik** [comment]
The last point there `Prompt to run docker-compose up -d using UI rather then Terminal prompt.` is proposed in #98

**Comment by nemchik** [comment]
FYI #104 provides functionality for permissions and ownership. In its current state it only applies to the `${SCRIPTPATH}` but in reality should probably apply to any folder from the `.env` file.

**Comment by nemchik** [comment]
I'm going to close out this issue and take the remaining tasks off the todo list and create cards in the projects as needed. For reference here was the remaining list.

- Prompt to enable/disable reverse proxy per app in letsencrypt config
- Check for apps using the same port
- Possibly prompt to select which apps should be configured to use a VPN (depending on how we end up handling VPN)
